### ISSUE TITLE
Syntax error, unexpected P_S, expecting IDENT_FB_INDEX '('.

### ISSUE THREAD

**Issue by hhezart** [J2Kbr/GtunerIV#10]
More of a question: what is the FFB_x datatype?
I'm getting following compiler error when I use the below ternary operator:

ffb_set((FALSE ? FFB_1 : FFB_2), 100.0, 80);

GPC error: 8t6-destiny.gpc(330): syntax error, unexpected P_S, expecting IDENT_FB_INDEX '('.

**Comment by J2Kbr** [comment]
FFB_\* and LED_\* are unsigned integer data type. However, its value represent a index position different from the referencing number. Functions like ffb_set and led_set must be used with explicit reference to LED_\* or FFB_\* in its first parameter. 
by your example, you can:

```
if(FALSE) ffb_set(FFB_1, 100.0, 80);
else ffb_set(FFB_2, 100.0, 80);
```
