### ISSUE TITLE
Option in IDE to be able to quickly toggle between button references and their actual names (e.g. BUTTON_14 to "Triangle")

### ISSUE THREAD

**Issue by PablosScripts** [J2Kbr/GtunerIV#100]
In theory, the best way to code would be using the standardized button references like BUTTON_14 instead of Triangle or Triangle_button whatever other reference you might use.

The problem is it's very difficult to remember them all. 

I was thinking it would be great if there was a shortcut key (e.g. F12) that you could press which automatically toggles the name based on your console of choice.  

Here is a mockup of my concept: 

https://i.imgur.com/bCIQigj.jpg

**Comment by prototypeGtuner** [comment]
Yes or something like that with a keystroke :)  You press the Triangle and it writes BUTTON_14!

**Comment by J2Kbr** [comment]
With the improvements made on the GPC Input Reference (Gtuner IV 0.100B) #113, I believe this issue can be closed, at least temporarily until we have enough time to test if the solution provided by the new GPC Input Reference offers an satisfactory solution for this issue.
