### ISSUE TITLE
Interactive Configuration UI should be brought to the front when you click the icon

### ISSUE THREAD

**Issue by PablosScripts** [J2Kbr/GtunerIV#101]
Scenario: 

1) You click the Interactive Configuration UI icon, and the pop-up appears. 

2) You then click on Gtuner, which forces it to come to the foreground. The Interactive Configurator window is now behind Gtuner. 

3) Repeat step #1 - the Interactive Configuration window no longer appears. The only way to make it appear again is to minimise Gtuner. 

This was tested on a Mac and presumably this is the same on PC.

**Comment by J2Kbr** [comment]
This issue was not affecting the Windows version. Fixed on Mac version, Gtuner IV 0.100B
