### ISSUE TITLE
Metainfo version not compile for 08 and 09

### ISSUE THREAD

**Issue by UK-Wildcats-Fans** [J2Kbr/GtunerIV#103]
I did some more testing.  The metainfo sub version works if I use just an 8 but not when I use 08.  Odd thing is that it worked with all version of 01 to 07 until I got to 8.  It does not work for 08 & 09 but works again for 10

Original Topic
[http://www.consoletuner.com/forum/viewtopic.php?f=27&t=5562](url)

**Comment by J2Kbr** [comment]
The lexer assumes that any number starting with 0 is octal, so the digits 8 and 9 are not allowed. For the version number you don't need add the leading 0, for example: numerically speaking 08 is same as 8. When displaying the sub-version an leading 0 is automatically added in cases of one digit numbers.
