### ISSUE TITLE
No "Cancel" option in file close prompt

### ISSUE THREAD

**Issue by PablosScripts** [J2Kbr/GtunerIV#105]
When you have made changes to a file, and then proceed to close it without saving first, the prompt that is displayed doesn't give you the option to "Cancel". You can only **close and not save**, or **close and save**...there is no way to back out of the prompt. It's not a big deal but it's just unusual as almost every other application out there has a "Cancel" button. 

See the following screenshot: 

https://i.imgur.com/wCcyYy6.jpg

**Comment by J2Kbr** [comment]
Cancel option for close file events (Code Editor and Input Translator) added on Gtuner IV 0.100B
