### ISSUE TITLE
Output Panel - Add multiple select and or copy all to rightclick menu

### ISSUE THREAD

**Issue by Scachi** [J2Kbr/GtunerIV#106]
When posting error in the forum it is hard to copy the output panels content to a post.
This has to be done line by line or with a screenshot.
Adding the option to select multiple lines in the output panel and using right click->copy to copy all the select lines would be very helpful.

**Comment by PablosScripts** [comment]
Very good idea.

**Comment by J2Kbr** [comment]
Select and copy multiple lines on output panel.
Selection modifiers keys: Ctrl and Shift.
Feature implemented on Gtuner 0.100B
