### ISSUE TITLE
When I change Config UI settings, the message in the Output Panel is duplicated

### ISSUE THREAD

**Issue by PablosScripts** [J2Kbr/GtunerIV#107]
I tested this like 5 times to make sure I wasn't accidentally double clicking the "Save and Run" button but it is definitely happening. Please see the attached screenshot:

https://i.imgur.com/YeAqUu7.jpg

Also note that this is on Mac, I can't remember whether this was a problem on PC.

**Comment by J2Kbr** [comment]
This bug was also affecting the Windows version. Fixed on Gtuner IV 0.100B
