### ISSUE TITLE
Add a "Reset to Default" button on the Controller Remapper

### ISSUE THREAD

**Issue by PablosScripts** [J2Kbr/GtunerIV#108]
When I've made mistakes I always have to revert each field one by one, it takes forever!!

Please see the following mockup: 

https://i.imgur.com/RiYpycx.jpg

**Comment by J2Kbr** [comment]
I believe add an button to reset is not necessary, as by closing and re-opening the "Controller Remapper" section (click twice on the bar named "Controller Remapper") the mapping are all reverted to its default values. This is also valid for all the other sections (Meta Info, Keyboard Mapping, Mouse Mapping and Mouse XY Converter)
