### ISSUE TITLE
Publish Wizard - Description textbox should scale verticaly

### ISSUE THREAD

**Issue by Scachi** [J2Kbr/GtunerIV#11]
When resizing the "Publish Wizard" window the description textbox should scale verticaly with the window.
Or is this that we don't put to much informations in there ?

Maybe a "description" field in addition to the "shortdesc" for a more detailed description which can be shown with a click on a [show more] button when browsing the online resources.

**Comment by J2Kbr** [comment]
A small height scaling was added to the description textbox - Gtuner IV 0.91

Side note: you can have a post with more detailed information about your script in the ConsoleTuner community forums and link it using the DocURL field.
