### ISSUE TITLE
Possible Input Reference bug on Mac

### ISSUE THREAD

**Issue by PablosScripts** [J2Kbr/GtunerIV#112]
http://www.consoletuner.com/forum/viewtopic.php?f=25&t=5680#p42250

**Comment by J2Kbr** [comment]
The keyboard shortcut (F1) is stopping to work on Mac if the GPC Input Reference is not the active window, even after it regains the status of active window. After 30min of investigation and research, I didn't find anything that could explains that. As workaround I programmed the GPC Input Reference to automatically close it-self if the active window changes. This solution is working on Mac and Windows and, to be honest, I liked this new behavior. :)
