### ISSUE TITLE
Ideas to enhance the usability of the Input Reference option

### ISSUE THREAD

**Issue by PablosScripts** [J2Kbr/GtunerIV#113]
Discussion here: 

http://www.consoletuner.com/forum/viewtopic.php?f=25&t=5680#p42247

A quick summary of the ideas: 

1) But would it be possible to have the windows positions saved ? Same for the interactive configuration window. Because i use Gtuner IV with 2 screens and these boxes are centered and split on each screen

2) The ability to click anywhere on the row, not just the left side would be good too:)

3) Add user tip about being able to press F1: http://www.consoletuner.com/forum/viewtopic.php?f=25&t=5680#p42248

**Comment by J2Kbr** [comment]
The GPC Input Reference was re-written on Gtuner IV 0.100B

1. Dynamic load the table contents and better presentation;
2. Retain the window position and size during current session;
3. Insert the GPC Designator when an row is double clicked (the code editor must have focus)
4. Update a combo-box of GPC Designators when an row is double clicked (the combobox must have focus)

With these improvements I am also closing the issues #58 and #100 as their are related.
