### ISSUE TITLE
Interactive Configuration - Refresh/reread values from pmem after Save&Run and OK

### ISSUE THREAD

**Issue by Scachi** [J2Kbr/GtunerIV#114]
For my The Division script I have added some adjustable presets for anti recoil and fire mode settings for different weapons.

To accomplish that I have added one checkbox and one combobox per weapon slot:

Anti Recoil Preset PRIMARY
[ ] Load preset
[Weapon selection Combobox]

Anti Recoil Preset SECONDARY Weapon
[ ] Load preset
[Weapon selection Combobox]

Anti Recoil Preset SIDEARM Weapon
[ ] Load preset
[Weapon selection Combobox]

To load a  weapon preset, I select one weapon by name from the primary weapon selection combobox and check its checkbox.

In the scripts init function I am reading and handling the "Load preset" checkbox values.
If it is checked, I reset this flag and read the preset values from several arrays and apply them to their variables to really work for anti recoil and firemodes/timings.
I am writing them back to their corresponding pmem byteoffset positions, too. So if I close and reopen the Interactive Configuration window all the combobox/sliders/checkboxes read the correct values according to the loaded preset so the can be adjusted by the user if they need to.

Current problem:
When the "Save&Run" button is pressed the Interactive windows is still showing the old values that have already changed by the init function.

Is it possible for the script/T2 to send a refresh command back to GTuner so it refreshes the Interactive Configuration values to show the current active values ?
This would allow me to send a refresh/reload command when I have finished to apply and written back my preset values to their byteoffset pmem positions.

My experimental The Division script version with preset support is attached.

[the_division_presets_scachi.zip](https://github.com/J2Kbr/GtunerIV/files/758562/the_division_presets_scachi.zip)

**Comment by J2Kbr** [comment]
Instead of create an dedicated build-in function for this purpose, I decided utilize the `printf` to send commands from the Titan Two to Gtuner IV (`GCMD`). This approach is much more flexible, allows easy extend with more commands and does not requires firmware update.

To refresh the Interactive Configuration the GCMD is:

`printf("GCMD:InteractiveConfiguration.Refresh");`

Implemented on Gtuner IV 0.100B
