### ISSUE TITLE
The ability to tell which port the input originated from

### ISSUE THREAD

**Issue by PablosScripts** [J2Kbr/GtunerIV#117]
Example use case: 

You have both a PS4 and XB1 controller connected simultaneously. You have a script to transform the XB1 controller into a PS4 one (to use touchpad, share button etc), but when you pick up the PS4 controller instead, you need all this functionality to be ignored. 

More info here: 

http://www.consoletuner.com/forum/viewtopic.php?f=26&t=5750#p42875

And here: 

http://www.consoletuner.com/forum/viewtopic.php?f=26&t=5798

**Comment by seededplyr** [comment]
as describe here (https://www.consoletuner.com/forum/viewtopic.php?f=26&t=6359&p=47192#p47192) I plan to use the arduino leonardo as a second controller for activating some combos while still using the DS4 on port A as the primary controller, therefore it would be helpful if i could code something like get_val(USBA.BUTTON_4) {//do something}
get_val(USBB.BUTTON_4) {//do something else}
of course in whatever way/method you see fit, (im not a programmer at all).

**Comment by J2Kbr** [comment]
As I commented on the forums, mostly like this is not possible to be implement, as it would require changes on the very core of the firmware code, with implications on many other parts of the firmware code.

The original design of the device was made to merge the inputs of multiple controllers into a **single structure**. GPC scripts have access only to this normalized data structure, which does not makes distinction of which controller an given input came from.

As you well noted, this is different from #136.  What we are discussing on #136 is perfectly possible.
