### ISSUE TITLE
Publish Wizzard

### ISSUE THREAD

**Issue by ChaosInTheVoid** [J2Kbr/GtunerIV#118]
I keep getting invalid username and password depite copying and pasting known values into the box.

**Comment by Scachi** [comment]
The username might be case sensitive, have you checked that ?

**Comment by ChaosInTheVoid** [comment]
As stated cut and paste from known values so no I did a password reset to check

**Comment by Scachi** [comment]
Depends where the "known values" came from.
I can login in the forum with uppercase or lowercase or mixed case.
Login with the Publish Wizard only works for me with the username typed in exactly as it is shown left of the Forums "Logout" Button, for me that is "Scachi" <- only that works.

**Comment by ChaosInTheVoid** [comment]
Bizzare... I entered in Camel Case, and I login to forums in camel case, but the actual login is in sentance case.

I nearly always create usernames in CamelCase
