### ISSUE TITLE
Issues with switch and wait inside of combo blocks

### ISSUE THREAD

**Issue by PaulaTheKoalaCT** [J2Kbr/GtunerIV#119]
The following code will result in the compile error: Illegal operation 'wait'.

```
combo test
{
	switch (0)
	{
	}
	
	wait(20);
}
```

Removing the switch statement will allow it to compile just fine.

**Comment by J2Kbr** [comment]
Compiling bug with nested jumping tables - fixed on Gtuner IV 0.100B
