### ISSUE TITLE
SD card file access for scripts

### ISSUE THREAD

**Issue by Scachi** [J2Kbr/GtunerIV#120]
Allowing to store some configuration values in an extra file would be cool.

As an example:
For "The Division" I am trying to add some weapon preset values for anti recoil and fire modes (burst/rapid).
As the list of available weapons is long and storing all the values for all weapon in an array would take to much memory in the script, it would be great if I can store those values per weapon in an extra file (something like slot1.wtf) and access only the lines of one weapon I need to read and assign the values to the variables in the script.

In the interactive configuration I would create a combobox with the list of weapon names for the user to select a preset according to the users weapon.
On script execution (init) I would search the file for the entry and assign the values to the variables somehow (fopen/fread/fscanf)
This way I would just need the memory to store the values of the selected weapon(s), not all available weapons.

Example file content (in whatever style (ini,csv,...):
[weapon1]
recoil1v=10
recoil1l=1
recoil1r=0
recoiladd1time=300
recoiladd1val=940
recoiladd1max=55
recoiladd2time=2000
recoiladd2val=540
recoiladd2max=65

[weapon2]
recoil1v=14
recoil1l=0
recoil1r=0
recoiladd1time=320
recoiladd1val=980
recoiladd1max=36
recoiladd2time=3000
recoiladd2val=640
recoiladd2max=55

Maybe this would also allow to publish my division script as bytecode, but still giving the user the option to modify their favorite weapon values in the configuration file to their needs.

Not sure if I have explained it well enough to understand this idea.

**Comment by J2Kbr** [comment]
I've been considering and thinking if it would be possible to have builtin functions to allow access files on the sd-card, much like as your suggestion. But the file system library utilized on the firmware is very bare bones to keep the library footprint small and the performance as best as possible.

The efforts required and downsides of implement the fopen, fread, fwrite, fclose, etc functions will not worth, it is an very niche need. Even the case you described, you can -alternatively- make use `const arrays` to store these information without external files, something on these lines:
```
#define recoil1v        0
#define recoil1l        1
#define recoil1r        2
#define recoiladd1time  3
#define recoiladd1val   4
#define recoiladd1max   5
#define recoiladd2time  6
#define recoiladd2val   7
#define recoiladd2max   8

const int weapon1[] = {
    10,     // recoil1v
    1,      // recoil1l
    0,      // recoil1r
    300,    // recoiladd1time
    940,    // recoiladd1val
    55,     // recoiladd1max
    2000,   // recoiladd2time
    540,    // recoiladd2val
    65      // recoiladd2max
};

const int weapon2[] = {
    14,     // recoil1v
    0,      // recoil1l
    0,      // recoil1r
    320,    // recoiladd1time
    980,    // recoiladd1val
    36,     // recoiladd1max
    3000,   // recoiladd2time
    640,    // recoiladd2val
    55      // recoiladd2max
};

int weapon[9];

init {
    pmem_load();
    // Load weapon profile based on the user's configuration
    if(pmem_read(0) == 1) {
        memcpy(&weapon, &weapon1, sizeof(weapon));
    } else if(pmem_read(0) == 2) {
        memcpy(&weapon, &weapon2, sizeof(weapon));
    }
}

main {
    // then use the selected weapon profile like this:
    // weapon[recoil1v]
}
```
