### ISSUE TITLE
sort scripts via the window top menu ?

### ISSUE THREAD

**Issue by prototypeGtuner** [J2Kbr/GtunerIV#122]
Sometimes i have a lot of scripts opened and it's annoying to sort them. I can enlarge the GPC script window to both screens but would it be possible to sort scripts via the "window" top menu ?

**Comment by PablosScripts** [comment]
This is a cool idea. Maybe bring the last updated script to the first tab.

**Comment by J2Kbr** [comment]
Feature added on Gtuner IV 0.100B
