### ISSUE TITLE
Share data between slots / Allow script to take up the space of more than one slot

### ISSUE THREAD

**Issue by Scachi** [J2Kbr/GtunerIV#123]
I am hitting the bytecode limit with my The Division script and I am thinking about ways to solve this / get access to more space -> forum link: http://www.consoletuner.com/forum/viewtopic.php?f=26&t=5865

 I have tried to optimize the code to take up less space, it helped a bit but I still need more space to get all my ideas in. I'll try to finish my script in the next few days and see if I can modify/optimize it somehow to fit into one slot.

Accessing the segment display for a more user friendly in-game configuration adds a lot of bytecode size to the script as a lot of the adjustment/configuration code does too.
So it would be great being able to slit my script into two parts. One part/slot for gaming, one part/slot for configuration.
Or allowing a script to take up the space of two slots (pmem also) would be much easier, well.. for me ;-)

Splitting the script into two part should allow me to read the pmem data of a different slot
something like pmem_load(1) or adding some global space to write to for exchanging data.

**Comment by J2Kbr** [comment]
The variants with argument of `pmem_load()` and `pmem_save()` were added on Gtuner 0.100B and firmware 0.84B
```
pmem_load(uint8 slot_no);
pmem_save(uint8 slot_no);
```
