### ISSUE TITLE
Gtuner IV on Mac crashing a lot

### ISSUE THREAD

**Issue by PablosScripts** [J2Kbr/GtunerIV#125]
I have the latest OS (Sierra) with all the latest patches and updates, and I would say 99% of the crashes come from simply navigating through the file explorer.

Also when I try to drag and drop a file from a package (such as a .git file from the main GTIV application via Finder), this causes a crash 100% of the time.

**Comment by J2Kbr** [comment]
I was able to reproduce the crashing related with opening GIT files on Mac, fixed on Gtuner IV 0.100B

I think it was also related with the opening GIT files from File Explorer, so I will close this issue.
