### ISSUE TITLE
Make it mandatory to enter at least x characters into the description when publishing a script

### ISSUE THREAD

**Issue by PablosScripts** [J2Kbr/GtunerIV#128]
There are currently scripts with no descriptions...I have no idea what some of them are. And if they're bytecode we'll never know. The online resources page is going to get clogged up with junk and confusing to navigate if we get too many of these scripts.

**Comment by Scachi** [comment]
+1
I was just about to enter this myself ;-)

**Comment by J2Kbr** [comment]
Starting from Gtuner IV 0.100B, every work being published must have a description.
