### ISSUE TITLE
Add debuging commands to output values and strings

### ISSUE THREAD

**Issue by Scachi** [J2Kbr/GtunerIV#13]
More a reminder, as you have posted it yourself in the forum.

Please add some debuging commands to output values and strings on the output panel and/or device monitor.

Using the output panel is ok, but make it hard to recognize changes on multiple values as it scrolls down.
Adding some debug field (maybe as an view menu option to show/hide them) like the strace fields in the t1 gtuner would be great.

**Comment by J2Kbr** [comment]
printf function added to Gtuner IV 0.92 Beta and Titan Two firmware 0.72 Beta.
