### ISSUE TITLE
use remapper_swap with  variables ?

### ISSUE THREAD

**Issue by Scachi** [J2Kbr/GtunerIV#131]
A lot of T1 script/gamepacks seems to use the swap command with variables as arguments,
as they change the variables a lot with button remapping. To easily convert them to the T2 it would be great when remapper_swap accepts variables too. Right now it seems to only accept "defines".

**Comment by Scachi** [comment]
It looks like the swap command from the T1 works not the same way as the remapper_swap from the T2, is that true ?

**Comment by J2Kbr** [comment]
Correct. The swap for the Titan Two configures the Input Translator, which is evaluated at controller driver level (not during the script execution, as it happens on Titan One).

For code conversion you can use the following Titan Two function. Please note this function reproduces exactly what Titan One does with the swap command.
```
void swap(uint8 inputA, uint8 inputB) {
	fix32 tmp;
	
	tmp = get_val(inputA);
	set_val(inputA, get_val(inputB));
	set_val(inputB, tmp);
	
	return;
}
```

**Side note:** for performance reasons the identifiers are passed as direct parameter of the remapper_swap() opcode, therefore stack values can't be used.
