### ISSUE TITLE
Implement turn assist function (for mice)

### ISSUE THREAD

**Issue by PablosScripts** [J2Kbr/GtunerIV#132]
XIM has a "turn assist" function, which simulates someone holding in one direction on the stick. 

For example if you are in a tank and turning the turret left, if you are using a mouse, you would have to keep swiping non-stop to achieve the same result. "Turn assist" means you can swipe left once and it will just keep going left until you press or release a nominated deactivation key. 

This is also very useful for weapon wheels where you need to peg the stick in one direction for a long time.

More information here: 

http://xim4.com/community/index.php?topic=40611.msg504932#msg504932

PS if you do implement this you should probably use a different term, as "Turn Assist" was invented for XIM. Suggested terms: 

1) Auto Turn
2) Auto Peg
3) Simulated Stick Peg
4) Console Style Turning
5) Simulated Stick Turn
6) Turret Turn

**Comment by PablosScripts** [comment]
Another good way to think about it is this: 

Imagine trying to use a mouse to steer a car. Ideally you would just turn to the left or right, but the way it works with mice is you need to keep swiping to the left to turn left. You can't just hold it left. Turn Assist removes the need to keep swiping.

**Comment by J2Kbr** [comment]
This feature, at current stage of Mouse support, is more suitable to be implemented via script. I will be working in a header file for this functionality, initially for Gamepacks but possible will also publish the code on Gtuner. ;)
