### ISSUE TITLE
Crash on startup. Windows 10 Pro

### ISSUE THREAD

**Issue by GarethWright** [J2Kbr/GtunerIV#134]
GTuner Executed Window very briefly displayed before crash.
Event log 

Error	08-Mar-17 2:22:05 PM	SideBySide	35	None
Log Name:      Application
Source:        SideBySide
Date:          08-Mar-17 2:22:05 PM
Event ID:      35
Task Category: None
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      Garethw
Description:
Activation context generation failed for "D:\GTuner\Gtuner.exe".Error in manifest or policy file "D:\GTuner\lib\lib.MANIFEST" on line 3. Component identity found in manifest does not match the identity of the component requested. Reference is lib,processorArchitecture="AMD64",type="win32",version="1.0.0.0". Definition is lib,processorArchitecture="x86",type="Win32",version="1.0.0.0". Please use sxstrace.exe for detailed diagnosis.
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="SideBySide" />
    <EventID Qualifiers="49409">35</EventID>
    <Level>2</Level>
    <Task>0</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2017-03-08T14:22:05.411070100Z" />
    <EventRecordID>49168</EventRecordID>
    <Channel>Application</Channel>
    <Computer>Garethw</Computer>
    <Security />
  </System>
  <EventData>
    <Data>lib,processorArchitecture="AMD64",type="win32",version="1.0.0.0"</Data>
    <Data>lib,processorArchitecture="x86",type="Win32",version="1.0.0.0"</Data>
    <Data>
    </Data>
    <Data>
    </Data>
    <Data>
    </Data>
    <Data>
    </Data>
    <Data>
    </Data>
    <Data>
    </Data>
    <Data>
    </Data>
    <Data>
    </Data>
    <Data>D:\GTuner\Gtuner.exe</Data>
    <Data>D:\GTuner\lib\lib.MANIFEST</Data>
    <Data>3</Data>
    <Data>
    </Data>
    <Data>
    </Data>
    <Data>
    </Data>
    <Data>
    </Data>
    <Data>
    </Data>
    <Data>
    </Data>
    <Data>
    </Data>
  </EventData>
</Event>

**Comment by GarethWright** [comment]
sxstrace

=================
Begin Activation Context Generation.
Input Parameter:
	Flags = 0
	ProcessorArchitecture = Wow32
	CultureFallBacks = en-US;en
	ManifestPath = D:\GTuner\Gtuner.exe
	AssemblyDirectory = D:\GTuner\
	Application Config File = 
-----------------
INFO: Parsing Manifest File D:\GTuner\Gtuner.exe.
	INFO: Manifest Definition Identity is (null).
	INFO: Reference: Microsoft.Windows.Common-Controls,language="&#x2a;",processorArchitecture="&#x2a;",publicKeyToken="6595b64144ccf1df",type="win32",version="6.0.0.0"
	INFO: Reference: lib,processorArchitecture="&#x2a;",type="win32",version="1.0.0.0"
INFO: Resolving reference Microsoft.Windows.Common-Controls,language="&#x2a;",processorArchitecture="&#x2a;",publicKeyToken="6595b64144ccf1df",type="win32",version="6.0.0.0".
	INFO: Resolving reference for ProcessorArchitecture WOW64.
		INFO: Resolving reference for culture en-US.
			INFO: Applying Binding Policy.
				INFO: No publisher policy found.
				INFO: No binding policy redirect found.
			INFO: Begin assembly probing.
				INFO: Did not find the assembly in WinSxS.
				INFO: Attempt to probe manifest at C:\WINDOWS\assembly\GAC_32\Microsoft.Windows.Common-Controls\6.0.0.0_en-US_6595b64144ccf1df\Microsoft.Windows.Common-Controls.DLL.
				INFO: Did not find manifest for culture en-US.
			INFO: End assembly probing.
		INFO: Resolving reference for culture en.
			INFO: Applying Binding Policy.
				INFO: No publisher policy found.
				INFO: No binding policy redirect found.
			INFO: Begin assembly probing.
				INFO: Did not find the assembly in WinSxS.
				INFO: Attempt to probe manifest at C:\WINDOWS\assembly\GAC_32\Microsoft.Windows.Common-Controls\6.0.0.0_en_6595b64144ccf1df\Microsoft.Windows.Common-Controls.DLL.
				INFO: Did not find manifest for culture en.
			INFO: End assembly probing.
		INFO: Resolving reference for culture Neutral.
			INFO: Applying Binding Policy.
				INFO: No publisher policy found.
				INFO: No binding policy redirect found.
			INFO: Begin assembly probing.
				INFO: Did not find the assembly in WinSxS.
				INFO: Attempt to probe manifest at C:\WINDOWS\assembly\GAC_32\Microsoft.Windows.Common-Controls\6.0.0.0__6595b64144ccf1df\Microsoft.Windows.Common-Controls.DLL.
				INFO: Did not find manifest for culture Neutral.
			INFO: End assembly probing.
	INFO: Resolving reference for ProcessorArchitecture x86.
		INFO: Resolving reference for culture en-US.
			INFO: Applying Binding Policy.
				INFO: No publisher policy found.
				INFO: No binding policy redirect found.
			INFO: Begin assembly probing.
				INFO: Did not find the assembly in WinSxS.
				INFO: Attempt to probe manifest at C:\WINDOWS\assembly\GAC_32\Microsoft.Windows.Common-Controls\6.0.0.0_en-US_6595b64144ccf1df\Microsoft.Windows.Common-Controls.DLL.
				INFO: Did not find manifest for culture en-US.
			INFO: End assembly probing.
		INFO: Resolving reference for culture en.
			INFO: Applying Binding Policy.
				INFO: No publisher policy found.
				INFO: No binding policy redirect found.
			INFO: Begin assembly probing.
				INFO: Did not find the assembly in WinSxS.
				INFO: Attempt to probe manifest at C:\WINDOWS\assembly\GAC_32\Microsoft.Windows.Common-Controls\6.0.0.0_en_6595b64144ccf1df\Microsoft.Windows.Common-Controls.DLL.
				INFO: Did not find manifest for culture en.
			INFO: End assembly probing.
		INFO: Resolving reference for culture Neutral.
			INFO: Applying Binding Policy.
				INFO: Auto Servicing Policy redirected assembly version.
				INFO: Post policy assembly identity is Microsoft.Windows.Common-Controls,processorArchitecture="x86",publicKeyToken="6595b64144ccf1df",type="win32",version="6.0.14393.447".
			INFO: Begin assembly probing.
				INFO: Attempt to probe manifest at C:\WINDOWS\WinSxS\manifests\x86_microsoft.windows.common-controls_6595b64144ccf1df_6.0.14393.447_none_89c64d28dafea4b9.manifest.
				INFO: Manifest found at C:\WINDOWS\WinSxS\manifests\x86_microsoft.windows.common-controls_6595b64144ccf1df_6.0.14393.447_none_89c64d28dafea4b9.manifest.
			INFO: End assembly probing.
INFO: Resolving reference Microsoft.Windows.Common-Controls.mui,language="&#x2a;",processorArchitecture="x86",publicKeyToken="6595b64144ccf1df",type="win32",version="6.0.14393.447".
	INFO: Resolving reference for ProcessorArchitecture WOW64.
		INFO: Resolving reference for culture en-US.
			INFO: Applying Binding Policy.
				INFO: No publisher policy found.
				INFO: No binding policy redirect found.
			INFO: Begin assembly probing.
				INFO: Did not find the assembly in WinSxS.
				INFO: Attempt to probe manifest at C:\WINDOWS\assembly\GAC_32\Microsoft.Windows.Common-Controls.mui\6.0.14393.447_en-US_6595b64144ccf1df\Microsoft.Windows.Common-Controls.mui.DLL.
				INFO: Did not find manifest for culture en-US.
			INFO: End assembly probing.
		INFO: Resolving reference for culture en.
			INFO: Applying Binding Policy.
				INFO: No publisher policy found.
				INFO: No binding policy redirect found.
			INFO: Begin assembly probing.
				INFO: Did not find the assembly in WinSxS.
				INFO: Attempt to probe manifest at C:\WINDOWS\assembly\GAC_32\Microsoft.Windows.Common-Controls.mui\6.0.14393.447_en_6595b64144ccf1df\Microsoft.Windows.Common-Controls.mui.DLL.
				INFO: Did not find manifest for culture en.
			INFO: End assembly probing.
	INFO: Resolving reference for ProcessorArchitecture x86.
		INFO: Resolving reference for culture en-US.
			INFO: Applying Binding Policy.
				INFO: No publisher policy found.
				INFO: No binding policy redirect found.
			INFO: Begin assembly probing.
				INFO: Did not find the assembly in WinSxS.
				INFO: Attempt to probe manifest at C:\WINDOWS\assembly\GAC_32\Microsoft.Windows.Common-Controls.mui\6.0.14393.447_en-US_6595b64144ccf1df\Microsoft.Windows.Common-Controls.mui.DLL.
				INFO: Did not find manifest for culture en-US.
			INFO: End assembly probing.
		INFO: Resolving reference for culture en.
			INFO: Applying Binding Policy.
				INFO: No publisher policy found.
				INFO: No binding policy redirect found.
			INFO: Begin assembly probing.
				INFO: Did not find the assembly in WinSxS.
				INFO: Attempt to probe manifest at C:\WINDOWS\assembly\GAC_32\Microsoft.Windows.Common-Controls.mui\6.0.14393.447_en_6595b64144ccf1df\Microsoft.Windows.Common-Controls.mui.DLL.
				INFO: Did not find manifest for culture en.
			INFO: End assembly probing.
INFO: Resolving reference lib,processorArchitecture="&#x2a;",type="win32",version="1.0.0.0".
	INFO: Resolving reference for ProcessorArchitecture WOW64.
		INFO: Resolving reference for culture Neutral.
			INFO: Applying Binding Policy.
				INFO: No binding policy redirect found.
			INFO: Begin assembly probing.
				INFO: Did not find the assembly in WinSxS.
				INFO: Did not find manifest for culture Neutral.
			INFO: End assembly probing.
	INFO: Resolving reference for ProcessorArchitecture x86.
		INFO: Resolving reference for culture Neutral.
			INFO: Applying Binding Policy.
				INFO: No binding policy redirect found.
			INFO: Begin assembly probing.
				INFO: Did not find the assembly in WinSxS.
				INFO: Attempt to probe manifest at D:\GTuner\lib.DLL.
				INFO: Attempt to probe manifest at D:\GTuner\lib.MANIFEST.
				INFO: Attempt to probe manifest at D:\GTuner\lib\lib.DLL.
				INFO: Attempt to probe manifest at D:\GTuner\lib\lib.MANIFEST.
				INFO: Manifest found at D:\GTuner\lib\lib.MANIFEST.
			INFO: End assembly probing.
INFO: Resolving reference lib.mui,language="&#x2a;",processorArchitecture="x86",type="win32",version="1.0.0.0".
	INFO: Resolving reference for ProcessorArchitecture WOW64.
		INFO: Resolving reference for culture en-US.
			INFO: Applying Binding Policy.
				INFO: No binding policy redirect found.
			INFO: Begin assembly probing.
				INFO: Did not find the assembly in WinSxS.
				INFO: Did not find manifest for culture en-US.
			INFO: End assembly probing.
		INFO: Resolving reference for culture en.
			INFO: Applying Binding Policy.
				INFO: No binding policy redirect found.
			INFO: Begin assembly probing.
				INFO: Did not find the assembly in WinSxS.
				INFO: Did not find manifest for culture en.
			INFO: End assembly probing.
	INFO: Resolving reference for ProcessorArchitecture x86.
		INFO: Resolving reference for culture en-US.
			INFO: Applying Binding Policy.
				INFO: No binding policy redirect found.
			INFO: Begin assembly probing.
				INFO: Did not find the assembly in WinSxS.
				INFO: Did not find manifest for culture en-US.
			INFO: End assembly probing.
		INFO: Resolving reference for culture en.
			INFO: Applying Binding Policy.
				INFO: No binding policy redirect found.
			INFO: Begin assembly probing.
				INFO: Did not find the assembly in WinSxS.
				INFO: Did not find manifest for culture en.
			INFO: End assembly probing.
INFO: Parsing Manifest File C:\WINDOWS\WinSxS\manifests\x86_microsoft.windows.common-controls_6595b64144ccf1df_6.0.14393.447_none_89c64d28dafea4b9.manifest.
	INFO: Manifest Definition Identity is Microsoft.Windows.Common-Controls,processorArchitecture="x86",publicKeyToken="6595b64144ccf1df",type="win32",version="6.0.14393.447".
	INFO: Reference: Microsoft.Windows.Common-Controls.Resources,language="&#x2a;",processorArchitecture="x86",publicKeyToken="6595b64144ccf1df",type="win32",version="6.0.14393.447"
INFO: Resolving reference Microsoft.Windows.Common-Controls.Resources,language="&#x2a;",processorArchitecture="x86",publicKeyToken="6595b64144ccf1df",type="win32",version="6.0.14393.447".
	INFO: Resolving reference for ProcessorArchitecture WOW64.
		INFO: Resolving reference for culture en-US.
			INFO: Applying Binding Policy.
				INFO: No publisher policy found.
				INFO: No binding policy redirect found.
			INFO: Begin assembly probing.
				INFO: Did not find the assembly in WinSxS.
				INFO: Attempt to probe manifest at C:\WINDOWS\assembly\GAC_32\Microsoft.Windows.Common-Controls.Resources\6.0.14393.447_en-US_6595b64144ccf1df\Microsoft.Windows.Common-Controls.Resources.DLL.
				INFO: Did not find manifest for culture en-US.
			INFO: End assembly probing.
		INFO: Resolving reference for culture en.
			INFO: Applying Binding Policy.
				INFO: No publisher policy found.
				INFO: No binding policy redirect found.
			INFO: Begin assembly probing.
				INFO: Did not find the assembly in WinSxS.
				INFO: Attempt to probe manifest at C:\WINDOWS\assembly\GAC_32\Microsoft.Windows.Common-Controls.Resources\6.0.14393.447_en_6595b64144ccf1df\Microsoft.Windows.Common-Controls.Resources.DLL.
				INFO: Did not find manifest for culture en.
			INFO: End assembly probing.
		INFO: Resolving reference for culture Neutral.
			INFO: Applying Binding Policy.
				INFO: No publisher policy found.
				INFO: No binding policy redirect found.
			INFO: Begin assembly probing.
				INFO: Did not find the assembly in WinSxS.
				INFO: Attempt to probe manifest at C:\WINDOWS\assembly\GAC_32\Microsoft.Windows.Common-Controls.Resources\6.0.14393.447__6595b64144ccf1df\Microsoft.Windows.Common-Controls.Resources.DLL.
				INFO: Did not find manifest for culture Neutral.
			INFO: End assembly probing.
	INFO: Resolving reference for ProcessorArchitecture x86.
		INFO: Resolving reference for culture en-US.
			INFO: Applying Binding Policy.
				INFO: Auto Servicing Policy redirected assembly version.
				INFO: Post policy assembly identity is Microsoft.Windows.Common-Controls.Resources,language="en-US",processorArchitecture="x86",publicKeyToken="6595b64144ccf1df",type="win32",version="6.0.14393.447".
			INFO: Begin assembly probing.
				INFO: Attempt to probe manifest at C:\WINDOWS\WinSxS\manifests\x86_microsoft.windows.c..-controls.resources_6595b64144ccf1df_6.0.14393.447_en-us_9fd1960e07a4d6a6.manifest.
				INFO: Manifest found at C:\WINDOWS\WinSxS\manifests\x86_microsoft.windows.c..-controls.resources_6595b64144ccf1df_6.0.14393.447_en-us_9fd1960e07a4d6a6.manifest.
			INFO: End assembly probing.
INFO: Parsing Manifest File D:\GTuner\lib\lib.MANIFEST.
	INFO: Manifest Definition Identity is lib,processorArchitecture="AMD64",type="Win32",version="1.0.0.0".
	ERROR: Component identity found in manifest does not match the identity of the component requested. Reference is lib,processorArchitecture="x86",type="win32",version="1.0.0.0". Definition is lib,processorArchitecture="AMD64",type="Win32",version="1.0.0.0".
ERROR: Activation Context generation failed.
End Activation Context Generation.

**Comment by J2Kbr** [comment]
This is an similar issue reported by Scachi in #82. In his case the error was not preventing the application to run.

Further looking at the log messages (thanks for posting), it seems you have installed in your computer another [assemblies](https://msdn.microsoft.com/en-us/library/windows/desktop/ff951640(v=vs.85).aspx) with same name and version Gtuner IV is configured to use: `lib`, `1.0.0.0` - which is creating an conflict.

Change the assemblies name on Gtuner IV at this point would be an dramatic procedure. However, in the hope of fix this issue, I changed the Gtuner's assemblies version to an higher value, so it should take preference over the other one you possible have installed.

I can't be 100% sure it will work, but I believe the chances are good, as such I am closing this issue. Please reopen if you are still facing this problem after update your Gtuner to 0.100B
