### ISSUE TITLE
GtIV / T2 update push nofications

### ISSUE THREAD

**Issue by PablosScripts** [J2Kbr/GtunerIV#135]
I think it would be useful to notify users when either the app or hardware needs an update. Most users aren't going to click the "Update" button unless prompted.

**Comment by PablosScripts** [comment]
I was just thinking, an alternative approach to push notifications would be to be notified via email. Upon account sign up, you could check a box to say "Notify me if Gtuner IV or Titan Two updates are available." and you'd get notified like that instead. Just a thought.

**Comment by J2Kbr** [comment]
Software and firmware automatic check for newer versions was added to Gtuner  IV 1.00RC

If an update is available, a message is printed in the output pane.
