### ISSUE TITLE
The ability to read HID information

### ISSUE THREAD

**Issue by PablosScripts** [J2Kbr/GtunerIV#136]
It would be good if we could actually get the HID information so that we could change logic based on the device that is plugged in.

For example I would like to have a single script that can change dynamically depending on whether I have a regular controller plugged in, compared to a XIM4 with a Sony Nav or a XIM4 with a regular keyboard. 

This was originally part of #117 but I thought it made sense to split it out as a separate Github entry.

**Comment by J2Kbr** [comment]
At some extent this functionality is provided by the GPC builtin function `port_status()`:
https://www.consoletuner.com/wiki/index.php?id=t2:port_status

The `device` parameter of this function can receive information about the actual connected device at some given port. At the moment is possible detect, for example, if the Xbox One controller is the Elite model, or if the PS3 controller is the Navigator. This ability can be extended to detect a wide variety of devices.

Please let me know if this satisfy your needs, if yes we close this issue and keep the work to add more detectable devices, If not, please give me more details of your needs beyond this. Thank you.
