### ISSUE TITLE
GPC Script IDE: Block marking Alt+LeftMouseButton

### ISSUE THREAD

**Issue by Scachi** [J2Kbr/GtunerIV#137]
I often use the block editing feature to copy/paste stuff.
The only problem with it that it limits the block selection to the length of the last selected line.
So I can't select all the Text (without the A/B/C) from a block like this as I would miss the 789 in the B line:

A Text123123
B Text123456789
C Text123123

The block selection should ignore the line length and just mark all the content to the mouse location, filling stuff without any content with whitespaces (I think this is what notepad++ does).

**Comment by J2Kbr** [comment]
Gtuner IV 0.104B enables virtual space (space beyond the end of each line) for rectangle selections.
