### ISSUE TITLE
If you do not add a blank line at the very end of your script, a warning is thrown

### ISSUE THREAD

**Issue by PablosScripts** [J2Kbr/GtunerIV#14]
Please see the attached warning message that is thrown. 

![2016-09-26_11-40-29](https://cloud.githubusercontent.com/assets/22415147/18820111/2091dbd2-83de-11e6-9d0c-399efb86319f.jpg)

**Comment by J2Kbr** [comment]
Gtuner IV 0.92 Beta removes the unnecessary "no newline, supplemented newline" warning.
