### ISSUE TITLE
Add ability to manually cancel out of a bad compile

### ISSUE THREAD

**Issue by PablosScripts** [J2Kbr/GtunerIV#144]
When you have a bug that is going to lead to 20 seconds of compilation errors and "ding" sounds, it would be good if you could hit a keyboard shortcut and manually cancel out of it. If there are lots of issues, yes you would want to see the results. However, there are many times when I know there aren't a lot of issues...it's just a missing bracket or something small, but it is still enough to trigger a really long compilation time.

**Comment by sillyasskid** [comment]
I don't think this is a actual issue with gtuner, I honestly have never experienced long compile times like you described. does your gtuner feel sluggish even with no scripts loaded? I either suspect your running gtuner on a low end machine, or maybe you are missing a few C++ redistributables.

**Comment by J2Kbr** [comment]
As commented by sillyasskid, the compilation time is very fast -- in the order of milliseconds. What I believe is causing the long compilation time is the beep sound, which is played whenever an error message is printed.

On Gtuner IV 1.00RC this behavior was changed and the beep sound is only played on the first error message. This should fix this problem. If not, please reopen this issue.

**Comment by PablosScripts** [comment]
Yes this is a great idea, when  you hear the ding sound repeatedly sometimes you think it's crashed. This is much better!
