### ISSUE TITLE
Feature Request- -Disable slots remote control

### ISSUE THREAD

**Issue by prototypeGtuner** [J2Kbr/GtunerIV#145]
Add a device option to be able to disable slot's remote control.

And a G8 alternate like in Gtuner Pro if possible.

**Comment by J2Kbr** [comment]
I remember, on the forums, to have suggested and opened the possibility of create an option to enable/disable the memory slot control using the controller. But the more I think about this more I am convinced it is better keep this as it is right now.

For example: if an user with this option disabled make an script using the combination Bumpers + PS/XBox and publish his/her work. The script will not work properly with someone with this option enabled.

Please also note that the memory slot control only is triggered by pressing the bumper button then the PS/Xbox button. The opposite does not triggers the memory slot control and could be used in your scripts, as you expressed on the forums. Hopefully this alternative will satisfy any needs you may have.

I am closing this GitHub for now, but still open to further discussion on this matter.
