### ISSUE TITLE
Ctrl-K to comment - feature request - (like N++)

### ISSUE THREAD

**Issue by seededplyr** [J2Kbr/GtunerIV#148]
Would be great if the IDE had the similar function to Notepad++ where highlight a few lines and then Ctrl-K will comment out those lines, and Ctrl-Shift-K will uncomment them.

**Comment by J2Kbr** [comment]
The shortcuts Ctrl+K and Ctrl+Shift+K to comment/uncomment a line, or selected lines, was added to Gtuner IV 1.0RC. Thank you for your suggestion.
