### ISSUE TITLE
Pressing the Esc button should close the Interactive Configurator UI

### ISSUE THREAD

**Issue by PablosScripts** [J2Kbr/GtunerIV#149]
Just a general usability improvement. I'm using Mac, not sure if this works on PC.

**Comment by J2Kbr** [comment]
On Windows `Esc` closes the Interactive Configurator window. I will be checking on Mac.

**Comment by PablosScripts** [comment]
I just tested this and I can see what's happened. Try this: 

1) Have both GT4 as well as another app opened (e.g. Chrome)

2) In GT4, open up an interactive configurator UI on any script (NOTE: this configurator UI must be opened via a script that is loaded in a slot, you cannot just press F9 on a script otherwise this problem doesn't happen). 

3) Toggle to the other app (Chrome) by pressing CTRL + TAB. 

4) Toggle back to the interactive configurator by pressing CTRL + TAB. 

5) Press the ESC button to close the UI. Notice that you can't.

**Comment by J2Kbr** [comment]
Bug fixed on Gtuner IV 1.00RC.
