### ISSUE TITLE
Pointer to array

### ISSUE THREAD

**Issue by hhezart** [J2Kbr/GtunerIV#15]
I declared a pointer and assigned an array to it, assuming array is a synonym for the location of the first element, but it didn't work:

<pre>
int8 *p;
int8 foo[10];
p = foo;
</pre>

I've also tried getting the address of the first element in the array but it didn't work either. Below is a code snippet where if primary is FALSE then the results become invalid:

<pre>
void getAntiRecoilCustom(bool primary, int8 *xAxis, int8 *yAxis)
{
    uint8 i = (primary? AR_PRIMARY_CUSTOM : AR_SPECIAL_CUSTOM) * 2;
    int8 *arr = (primary ? &_antiRecoilPrimarySettings[0] : &_antiRecoilSpecialSettings[0]);
    *xAxis = arr[i];
    *yAxis = arr[i+1];
}
</pre>

**Comment by J2Kbr** [comment]
You brought a point where the GPC script have a non-conventional behavior with respect arrays. Referring an array by only its name returns the value of the first element, same as indexing with [0]. To get the address of an array, or array element, the operator '&' must be used, example:

```
main {
    int8 foo[10];
    int8 *p = &foo;
    int8 *q = &foo[0];

    foo[0] = 88;

    set_val(BUTTON_20, *p);
    set_val(BUTTON_21, *q);
}
```

I also tested your second example and I couldn't reproduce the issue you described, please check the code below:

```
#define TRUE                !FALSE

#define AR_PRIMARY_CUSTOM   1
#define AR_SPECIAL_CUSTOM   2

int8 _antiRecoilPrimarySettings[] = { 0, 1, 2, 3,  4,  5 };
int8 _antiRecoilSpecialSettings[] = { 6, 7, 8, 9, 10, 11 };

int8 _xAxis, _yAxis;

main {
    getAntiRecoilCustom(FALSE, &_xAxis, &_yAxis);
    set_val(BUTTON_20, _xAxis);
    set_val(BUTTON_21, _yAxis);
}

void getAntiRecoilCustom(bool primary, int8 *xAxis, int8 *yAxis)
{
    uint8 i = (primary? AR_PRIMARY_CUSTOM : AR_SPECIAL_CUSTOM) * 2;
    int8 *arr = (primary ? &_antiRecoilPrimarySettings[0] : &_antiRecoilSpecialSettings[0]);
    *xAxis = arr[i];
    *yAxis = arr[i+1];
}
```
