### ISSUE TITLE
Feature Request - Y/X Axis Box in device manager for both input and output

### ISSUE THREAD

**Issue by seededplyr** [J2Kbr/GtunerIV#150]
similar to the Y/X box available in the controller settings on windows
![xbox_streaming_-_game_controllers](https://user-images.githubusercontent.com/8683682/27002438-c8279e1c-4e14-11e7-8419-b6e15ec1408a.png)

**Comment by J2Kbr** [comment]
XY plotting added to Gtuner IV 1.00RC-62. Device Monitor (CH1,CH2) and (CH3,CH4).
