### ISSUE TITLE
language error

### ISSUE THREAD

**Issue by toitoito** [J2Kbr/GtunerIV#151]
hi, every time I launched gtuner I receive this error:

System: Windows 7 SP 1 (6.1) (winnt 6.1.7601, x86_64, i386-little_endian-ilp32, LibGL)
OpenGL: C:/Windows/system32/opengl32.dll
Locale: Spanish, Spain
Gtuner: IV 0.105.1.560 ES:Automatic - Error loading language
Current Dir: C:/Gtuner
Data Dir: C:/Gtuner
Working Dir: C:/Gtuner/GPC
Device Selector: added 1 device(s), total of 1 device(s) detected
Connect: TITAN TWO [xxxxx] connected

**Comment by prototypeGtuner** [comment]
I can answer that is because it is only translated to French for now, other languages will be available later.

**Comment by J2Kbr** [comment]
Prototype is correct. Until the others languages are not added, the workaround to suppress this error is select English or French as language in the Gtuner IV Preferences.
