### ISSUE TITLE
Attempts to read from removable drives with no media mounted at startup

### ISSUE THREAD

**Issue by fade23** [J2Kbr/GtunerIV#154]
I have a multi-sd/cf card reader attached to my PC, which are defined in Windows disk management as removable media drives.  On startup of GTunerIV (RC1), it attempts to read all drives even though there is nothing mounted. OS is Windows 10.

![image](https://user-images.githubusercontent.com/578449/27661115-f99bcb1a-5c0d-11e7-85dd-4eee9e6cf82d.png)

This error message fires twice per drive.

**Comment by fade23** [comment]
Will also note that if, after cancelling through each error message to get to the main program page, if I try to remove one of these drives from File Explorer section, I get the following error:

![image](https://user-images.githubusercontent.com/578449/27661258-7260cbfe-5c0e-11e7-9674-ec6bb96c30f0.png)

**Comment by J2Kbr** [comment]
Unfortunately this is an issue that we can't fix on Gtuner IV. It is related with Windows. However, there are two workarounds:

1. On Gtuner IV, configure the working directory on the File Explorer area, this will prevent Gtuner to list the available drives at startup.

2. Edit the Windows Registry as described here:
https://www.accountexnetwork.com/blog/2013/08/fixing-the-there-is-no-disk-in-the-drive-error/
