### ISSUE TITLE
"Find/Replace" doesn't allow the "Replace with" box to be empty

### ISSUE THREAD

**Issue by seededplyr** [J2Kbr/GtunerIV#155]
Using the Find/Replace to replace something with nothing doesn't work because if the "Replace with:" box is empty the [Replace] & [Replace All] buttons are both greyed out

**Comment by PablosScripts** [comment]
I haven't had to use this yet but if this is true yeah this should definitely be fixed!

**Comment by J2Kbr** [comment]
Replacements with empty string is now allowed on the new revision of Gtuner IV 1.00RC
