### ISSUE TITLE
feature request, selecting a string highlights every occurrence 

### ISSUE THREAD

**Issue by seededplyr** [J2Kbr/GtunerIV#156]
this is another feature from notepad++ which would be nice to have inside the gtuner ide

![screenshot 62](https://user-images.githubusercontent.com/8683682/27767515-8cf9bae0-5f2c-11e7-8055-f76c10f3b0cb.png)

**Comment by J2Kbr** [comment]
Feature added to the new revision of Gtuner IV 1.00RC
