### ISSUE TITLE
Feature Request - Hotkey to "Clear All" Output Panel

### ISSUE THREAD

**Issue by seededplyr** [J2Kbr/GtunerIV#160]
similar to F12 for resetting the layout, a hotkey to clear the output panel would be appreciated. even down the road a hotkey section inside the preferences where we can set custom hotkeys would be great, but def a low priority feature request.

**Comment by J2Kbr** [comment]
We could easy add a hotkey to clear the output panel when this panel is active (with focus). However, this approach wouldn't be useful as usually others controls are active (i.e. code editor) when this action is desired and selecting the output panel first would defect the purpose as it would be just one step away from use the context menu. A global hotkey is more complicated and with implications that I prefer not deal in this case. As we already have a way to clear the output panel I am closing this request. Thank you for your understating.
