### ISSUE TITLE
GCMD:InteractiveConfiguration.Refresh not working for Run (test & debug)

### ISSUE THREAD

**Issue by Scachi** [J2Kbr/GtunerIV#161]
The printf command to update the interactive configuration does not update the interactive configuration ui when used while Run (Test & Debug).
printf("GCMD:InteractiveConfiguration.Refresh");

Is it possible to add this functionality ? Would be great to have the script fully functional no matter where it got started from.

**Comment by J2Kbr** [comment]
Functionality added to Gtuner IV 1.00RC-10
