### ISSUE TITLE
Interactive Configuration : New Control type request "graph"

### ISSUE THREAD

**Issue by Scachi** [J2Kbr/GtunerIV#162]
Having to deal with making configuration of a complex anti recoil script easier it would be very nice to have a control type for a graph with a configurable range for X axis, y axis, number of point the user may set/edit.
Resulting in a graph with spinboxes which gets upodates on dragging the coordinates or updates the points when changing the value directly.

I attached a mockup graph.
The blue points are coordinates that can be preconfigured something like this
item1x=0
item1y=20
item2x=1000
item2y=27

I know this sound very specific and is a lot of work, but I think it will be very useful for anti recoil configurations in general. Making the configuration more user friendly then before.
That would help a lot I think, at least for me
![interactive_graph](https://user-images.githubusercontent.com/22262242/28404618-579df3be-6d2a-11e7-8b1b-d07ddd17de49.png)
.

**Comment by sky418** [comment]
Ok, THX

**Comment by Scachi** [comment]
I think we can scratch that. I have done some more scripts with anti recoil and recognized that this won't help at all. Just to complicated I think.

**Comment by sky418** [comment]
I have made some to.
The whole idea, is good, but everything is stopped, by unstable game working (in lan mode example) and "errors" of game creators. Very unstable algorithm in !one! game (very often random for one weapon, in that way fine "onfly" tuning helps a little.), so making one for different games is unreal. But making for one specific weapon is real. The result is writing letters on the walls, by firing, if you have one weapon with stable algorithm, and game writen descriptions for it are  (in fact) equal in game (± %).
