### ISSUE TITLE
Feature Request - Allow creation of GIT files that allow mapping of multiple buttons to the same function

### ISSUE THREAD

**Issue by Munkee915** [J2Kbr/GtunerIV#163]
Currently if I try to map multiple buttons to the same function within the input translator, it will not allow me to save and use the file.  For instance, when mapping the paddles on the Elite controller, I want to map 1 paddle to do the same function as the B button, while still leaving the functionality of the B button in place.  But when mapping this way in Input Translator they are highlighted red and I am not allowed to save  and use the GIT file.  I would like to avoid having to connect the controller to the xbox remapper app every time I want to change setups for a new game or switching from PvE to PvP.  Would be nice to create custom GITs for each slot so I can switch on the fly.

NOTE: I have looked into handling this in scripting but since the code for some GPCs and all GPs are not made available it makes it difficult to integrate this code with some already existing solutions.  I would rather avoid having to rewrite a whole script just to add 1 piece of functionality.

**Comment by J2Kbr** [comment]
Unfortunately what you are requesting is not possible with Button Remapper. The mapping must be 1:1, it tells to the controller driver where to place the inputs. A 2:1 configuration would make the state of first input be overwritten by the second one.

However, this can be easily implemented with script, just add the following code to the very beginning of `main`, no other changes on the script code should be needed.
```
if(is_active(BUTTON_18)) {
    set_val(BUTTON_15, 100.0);
}
```
