### ISSUE TITLE
Firmware update issue on mac.

### ISSUE THREAD

**Issue by CrispyPixels** [J2Kbr/GtunerIV#166]
When updating the firmware on the Titan Two on a mac, the update window will close after the T2 is put into update mode with a "P" shown in the display. By telling it to update again it will correctly install the update. This happens independent of whether there is a Gtuner update or not.

**Comment by J2Kbr** [comment]
I added an extra check to avoid the update window to close when the device enters in programing mode. However, I couldn't test to confirm it will solve the issue. Please reopen if the problem persists after the Gtuner IV update 1.00RC-16. Thank you.

**Comment by CrispyPixels** [comment]
Just checked the new update (I really like having the DS4 touchpad and Share swapped by the way) same exact behavior: Tell it to check for update, a new version is found. I tell it to download and install, and the update window closes immediately after theT2 is put into boot loader mode. Reopening the window and telling it to update again installs the updates normally.
The issue seems to happen between putting the T2 into update mode, and actually downloading the firmware from the server. 
This issue happens regardless of whether or not there is an update for Gtuner.
