### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by lemanr** [J2Kbr/GtunerIV#169]
Sorry if this is possible now, but i dont find information in the forum

I suggest that will be possible to edit the profile 0, for example for a remapping button of a controller or that will be possible that the titan two, starts with the last profile used

In my case, i use a Xbox One Elite controller, and i modify the button mapping to use the touch button of a ps4 controller, i put this profile in profile 1 and i must select manually the profile every time

Thanks

**Comment by Scachi** [comment]
It is already possible to set the T2 to remember the last Slot used between power cycles.
Check the checkbox:
GTuner IV -> Device Configuration -> Device Options section  -> Recall loaded memory slot between power cycles.

**Comment by lemanr** [comment]
Ohhh!!

Perfect, many thanks and sorry for the post
