### ISSUE TITLE
GPC Script IDE pane - Bookmarks

### ISSUE THREAD

**Issue by Scachi** [J2Kbr/GtunerIV#17]
A bookmark function in the GPC Script IDE pane would be a great addition and help when creating bigger script to easily jump between positions.
The bookmarks don't need to be saved with the script.

I like Notepad++ bookmark handling & hotkeys a lot:
Ctrl+F2 to set a bookmark for the current line 
F2 to cycle through (jump to) all bookmarks forward direction
Shift+F2 to cycle through (jump to) all bookmarks reverse direction

**Comment by J2Kbr** [comment]
Bookmark margin, creation (`Ctrl+F2`) and navigation (`F2, Shift+F2`) added to Gtuner IV 0.100B

Left click on bookmark margin toggles the bookmarks. An Bookmarks sub-menu was added to top menu Edit, as well as an option on Preferences to enable/disable this feature.
