### ISSUE TITLE
Features Request - Macro Editor functions

### ISSUE THREAD

**Issue by prototypeGtuner** [J2Kbr/GtunerIV#172]
The Macro Editor is powerful and easy to use but lack some features like start the Macro from a defined position because if you have a 1 hour Macro file and you want to replay the last minutes it becomes an issue. An other thing that would be nice to do is to copy a section and been able to paste, overwrite or merge that section anywhere in the Macro!

**Comment by prototypeGtuner** [comment]
Also a way to be able to extend or compress a file, i mean if i have a Macro with 10 button presses in 100s it can be useful to run it to press 10 times in 10s or 200s!

**Comment by prototypeGtuner** [comment]
And been able to save a copy of a gmk like a gpc would be useful.

**Comment by prototypeGtuner** [comment]
And been able to delete several gmk at the same time in the Macro Explorer.

These are just some ideas, i have others to come!

**Comment by ant1th3s1s** [comment]
Filter out ACCEL, GYRO and STICK input before recording. Add simple tick boxes that indicate what the end-user wants to record, e.g

[ ] Button Presses
[ ] Stick Movement
[ ] Gyro Movement
[ ] Accel Movement

**Comment by ant1th3s1s** [comment]
Filter out set_val 0.0 button data on export from Macro to GPC combo.

**Comment by Chefmole** [comment]
Add a way to replay a macro at a faster speed

**Comment by J2Kbr** [comment]
Most request listed here were implemented on Gtuner 1.00RC-80. Some are already available or possible with alternative way.

**Comment by prototypeGtuner** [comment]
There is one or two things that could be nice. One is to load the active gmk into the sd card like the scripts and the other is reload the file to overwrite the changes after a mistake.

**Comment by J2Kbr** [comment]
Latest requests implemented on Gtuner IV 1.08, to be released soon.
