### ISSUE TITLE
Bugs: Output Panel "GPC error" line jumpto GPC Script Editor Line with folded areas

### ISSUE THREAD

**Issue by Scachi** [J2Kbr/GtunerIV#173]
I am used to put my interactive configuration in an extra comment area so I can fold it away if I don't need it.

When compiling and getting error messages like : 
`GPC error: destiny2_scachi.gpc(624): Declaration syntax error '('`
doubleclicking is jumping to the correct line normaly.

With some folded areas it seems to have problems, it looks like it is caused by my folded interactive configuration section. 
It looks like it tries to set the visible area to the line, ignoring that there is a big folded area and ending way below the correct line.
The edit cursor ends on the correct line.

To reproduce I have attached the current script where I am having this issue again.

Open the script

Fold the line 34: 
`/************************    Interactive Configuration******************************************************************
`
Hit compile
In Output Panel dblclick on `GPC error: destiny2_scachi.gpc(624): Declaration syntax error '('`

For me it jumps to the end of the script file.

[destiny2_scachi.zip](https://github.com/J2Kbr/GtunerIV/files/1308012/destiny2_scachi.zip)

**Comment by J2Kbr** [comment]
Bug fixed on Gtuner IV 1.00RC-18. Thanks for reporting.
