### ISSUE TITLE
Bug: pmem_save(slot)

### ISSUE THREAD

**Issue by Scachi** [J2Kbr/GtunerIV#175]
I have problems using the pmem_save(slot) function to save data to the specified slot.
It looks like it always write the data to the current active slot, as pmem_save() does when the slot parameter isn't used.

I have attached a zip with two scripts:
main.gpc
data.gpc

[main_n_data-gpc.zip](https://github.com/J2Kbr/GtunerIV/files/1309260/main_n_data-gpc.zip)

I put main.gpc in slot 1, data.gpc in slot 3.
Using the slot 3 Interactive configuration to specify a dataset to be written into slot 1 pmem and hit "Save and Run" button to actually run the dataset processing.

I would expect the data written into pmem of slot 1, but it always writes to slot3 (the current active).

Maybe you can find out what I am doing wrong in this small test script ?
Maybe I misunderstand how pmem_save(slot) is supposed to be working.

Thank you

**Comment by J2Kbr** [comment]
Fixed, the firmware update should be out as revision of 0.95B.
