### ISSUE TITLE
Feature Request: Interactive Configuration - set options "readonly"

### ISSUE THREAD

**Issue by Scachi** [J2Kbr/GtunerIV#176]
It would be a nice feature being able to use any config option as a "display only/readonly" item by setting a "readonly = true" flag, or something like this. (Later with more dynamic IC logic, disable/enable them dynamically)

I am currently playing around with using some items to display values calculated by the script back to the user / IC.

**Comment by J2Kbr** [comment]
The read only option is not available for the GUI controls in general (only for text input controls). The available alternative is disable the control element. By doing this will have the result you want, but the element will be grayed-out. Is this okay for your purposes?

**Comment by Scachi** [comment]
I am using a field for reporting configuration errors back to the user in my multi slot script example.
Having a text input field to use for this purpose (if I can set the text from within the script) would be great.
A grayed out field would take away the user focus to this field I think, missing the important info then.

I think this is a very specific use-case, so feel free to ignore it for now.
We can reopen/open a new issue if more scripters need/want such a feature.
