### ISSUE TITLE
Feature Request: Interactive Configuration - Color tag for shortdesc

### ISSUE THREAD

**Issue by Scachi** [J2Kbr/GtunerIV#177]
It is only possible to color the Title of an option at the moment.
When grouping options, it still is sometimes useful to color one of the grouped members differently.

I don't know if there is already a tag available for coloring `(like <b>for bold </b>),`
Something like that would be cool:
`Two <c #ff0000>red colored</c> words in the shortdesc text.
`

This would allow us to highlight parts of a text in a different color and to color members of a group in a different color, too.

**Comment by J2Kbr** [comment]
Apply color on the _shortdesc_ text is possible with `<font>` tag, example:

`shortdesc	= Use 'checkbox' for <font color="#FF0000">features</font> that can be enabled or disabled.`

In general all basic HTML tags can be used. 👍
