### ISSUE TITLE
Feature Request : fix16 datatype

### ISSUE THREAD

**Issue by Scachi** [J2Kbr/GtunerIV#178]
Hello,

is it possible to get something like a fix16 datatype for the Titan Two ?

fix32 is nice, but to store this into the pmem it takes 4 bytes,
For simple stuff I think it would be enough being able to store a decimal value between -100, 100  .. like 55.104 if we can get it to squeeze into 2 bytes (16 bits).

This would free up a lot space in pmem while still being able to store and use decimal values.

forum post link https://www.consoletuner.com/forum/viewtopic.php?f=26&t=6979

**Comment by J2Kbr** [comment]
Feature added to Gtuner IV revision 1.00RC-18. In addition to this it was also added an option 'decimals' to set the number of decimal digits to display, example:

```
[SPINBOXF EXAMPLE]
shortdesc	= Description here.
byteoffset	= 0
bitsize		= 32
control		= spinboxf
decimals	= 2
default		= 4000
minimum		= 100
maximum		= 50000
step		= 50
```

To store with 16 or 8 bits just set the bitsize accordingly, in this case an extra processing is required on the script, as the following for 16 bits storage.

```
int16 spinboxf_value16;
fix32 spinboxf_value;
init {
	pmem_load();
	pmem_read(0, &spinboxf_value16);
	spinboxf_value = (fix32)spinboxf_value16 / 256.0;
}
```
