### ISSUE TITLE
Feature Request: GPC Script IDE : Jump to matching bracket

### ISSUE THREAD

**Issue by Scachi** [J2Kbr/GtunerIV#179]
Request for another feature I am being used to have in notepad++ 

It would be nice to being able to jump to the corresponding opening/closing bracket { } 
when pressing ctrl+b if the cursor is located at a bracket - the ide already highlights it.

Another great addition would be what the arduino ide does there:
it displays the statement preceding the opening bracket in small text like popup/info window.

![bracketinfo](https://user-images.githubusercontent.com/22262242/30773894-6692671e-a07a-11e7-97c1-f88de35340fe.png)

**Comment by J2Kbr** [comment]
Ctrl+B for jump to matching brace added on Gtuner IV 1.00RC-20.

Thank you for your suggestions. 👍
