### ISSUE TITLE
Device Configuration Pane - T2 Reboot Button

### ISSUE THREAD

**Issue by Scachi** [J2Kbr/GtunerIV#18]
Is it possible to reboot/restart the T2 from within the GTunerVI software ?

My T2 seems suddenly stopped working correctly and unplugging/replugging the cable(s) just for rebooting is awkward if a click on a button in the GtunerIV software can do this too (maybe in the Device Configuration window).
My T2 isn't that easy to reach to un-/replug when I am sitting in front of my computer.

**Comment by J2Kbr** [comment]
As we discussed on the forums, I will close this issue for now. Please re-post here if this issue become relevant again.
