### ISSUE TITLE
Features Request - Shortcuts for Iterating & Manipulating Macro Editor Timeline + UI/UX improvements

### ISSUE THREAD

**Issue by dizzyziddy** [J2Kbr/GtunerIV#180]
![screen shot 2017-09-27 at 2 30 38 pm](https://user-images.githubusercontent.com/10507898/30898978-86091fac-a390-11e7-9e9b-450fc983706d.png)

Coming from applications like Aegisub (http://www.aegisub.org/downloads/), I'm used to having keyboard shortcuts when it comes to manipulating data on a given timeline, so I'll be able to perform tasks a lot more efficiently through the use of keyboard commands itself.

As such, is it possible for there to be keyboard shortcuts (user-defined would be a nice bonus!) for the Macro Editor for the following actions, assuming that those actions are already coded into the Macro Editor?

For the UI/UX improvements, I don't know what are the limitations of the .gmk filetype so I'm not sure if it allows for anything else extra other than input data.

Iterating through Timeline
* Move one frame forward
* Move one frame back
* Move X frames forward
* Move X frames back
* Start highlight selection on current frame
* End highlight selection on current frame

Manipulating Timeline
* Set Input to enabled/100 on current frame
* Set Input to disabled/0 to unpressed on current frame
* Interpolate current frame to next node
* Clear current frame/highlight's actions
* Undo/Redo last action (e.g. I accidentally deleted something and I want it back)

UI/UX
* Toggle Input display (e.g. GPC Button_4, PS4 R1, Xbox One RB, Nintendo Switch R, etc. With icons would be a nice bonus!)
* Add comments to current frame or range of frames (e.g. Frames X to XX, this is Ryu's LP Hadoken input)
* Custom Highlight to range of frames selected for easier identification of what it does (e.g. first range of inputs is highlighted in light blue, it's Ryu's LP Hadoken. second range of inputs highlighted in orange, it's Ryu's HP Shoryuken)

**Comment by J2Kbr** [comment]
Most of your suggestions were implemented on Gtuner IV 1.00RC-20 (to be released soon), the exceptions are the comments inclusion and range highlight, not possible due the gmk file format (highly optimized to run on the Titan Two). The changing of the display naming and the undo/redo operations will possible be implemented in the future.

With the timeline control active (with focus), the keyboard shortcuts are:

1. Left/Right move the cursor 1 millisecond back or forward respectively;
2. Crtl + Left/Right move the cursor to the next or previous node respectively;
3. Shift + Left/Right is used for selection;
4. Up/Down change the value of the node in the cursor position;
5. Plus create a new node in the cursor position (only one input must be checked);
6. Minus delete the node at the cursor position;
7. 'C' set/unset the node in the cursor position as "cutoff node";
8. 'I' set/unset the interpolation on the node at the cursor position.

Thank you for your suggestion. 👍
