### ISSUE TITLE
GPC Script IDE - Autocomplete with TRUE FALSE - Annoying = 1 / = 0

### ISSUE THREAD

**Issue by Scachi** [J2Kbr/GtunerIV#182]
I understand that this should help us to understand that TRUE = 1 and FALSE = 0 ,
but it is annoying that this gets written into the script when pressing tab.
Could this be changed that te information is still there, but on tab (complete) only TRUE or FALSE gets written into the script, please ?

Perhaps I am just lazy to not write TRUE or FALSE myself and just press the first character ant hit tab.

**Comment by J2Kbr** [comment]
Hi, I tested this on both PC and Mac and couldn't reproduce.  By pressing T followed by Tab, it only auto complete TRUE without '= 1' as you described, same for FALSE.

Please let me know how to reproduce the described behavior. thanks.

**Comment by Scachi** [comment]
This must have happened with an update.
Reinstalling (Download and unpack) GTuner IV into a fresh directory did fix this problem for me.

Before the new install it showed "TRUE=1" in the preview where you can select the completion and hit TAB, now it is only showing "TRUE" in this small window, so now it only completes to TRUE like it should.

**Comment by J2Kbr** [comment]
Thank you for confirming this is not a problem anymore. :)
