### ISSUE TITLE
Useability - Making copying of scripts from GPC Script IDE into slots more obvious

### ISSUE THREAD

**Issue by Scachi** [J2Kbr/GtunerIV#183]
Just as a reminder:

It was already discussed multiple time that the current way of copying script into slots isn't obious.

It would be nice to have an "Install" button near the "Compile" and "Run" buttons. Hitting the "Install" button would open a dialog to select the slot the script should be "installed" to.

Topics:
https://www.consoletuner.com/forum/viewtopic.php?f=26&t=6985&p=52018#p52015
https://www.consoletuner.com/forum/viewtopic.php?f=25&t=6933&p=51813&hilit=slot#p51813

**Comment by J2Kbr** [comment]
Feature added to Gtuner IV 1.00RC-20.

A new icon was added after "Compile" command, clicking on it popups a menu to select the memory slot to install the active work.
