### ISSUE TITLE
visual scripting

### ISSUE THREAD

**Issue by abufhad** [J2Kbr/GtunerIV#185]
can you please add visual scripting in GtunerIV #

**Comment by J2Kbr** [comment]
The implementation of visual scripting interface for GPC2 would require significant efforts and yet be limited to very basic operations, flow control and simple pre-built combos.

You can still use the Visual Script from [Gtuner Pro](https://www.consoletuner.com/titan-one-downloads/) to program the Titan Two.

In the Visual Scripting interface, click on the toolbar icon “_Visual to GPC_”, this command will generate the equivalent GPC code for the visual blocks, example:

```
//
// Tue Apr 17 2018 06:22:55
// Script generated by Visual to GPC
//----------------------------------------

main {
    if((get_val(PS4_R2)) && (get_val(PS4_L2))) {
        combo_run(Turbo_1);
    }
}

combo Turbo_1 {
    set_val(PS4_R2, 100);
    wait(40);
    set_val(PS4_R2, 0);
    wait(30);
    set_val(PS4_R2, 0);
}
```

All you need to do is copy and paste the code on Gtuner IV and add `#include <titanone.gph>` at the very beginning, example:

```
#include <titanone.gph>

//
// Tue Apr 17 2018 06:22:55
// Script generated by Visual to GPC
//----------------------------------------

main {
    if((get_val(PS4_R2)) && (get_val(PS4_L2))) {
        combo_run(Turbo_1);
    }
}

combo Turbo_1 {
    set_val(PS4_R2, 100);
    wait(40);
    set_val(PS4_R2, 0);
    wait(30);
    set_val(PS4_R2, 0);
}
```
