### ISSUE TITLE
When the output port is disconnected, the T2 should restart (?)

### ISSUE THREAD

**Issue by PablosScripts** [J2Kbr/GtunerIV#186]
Currently if you have an AC adapter plugged in, disconnecting and reconnecting the output cable will not restart the T2. E.g. if you are having problems and want to restart it. 

It's a bit annoying having to unplug both the power and output cables in order to perform a hard restart.

**Comment by Scachi** [comment]
Isn't it the power supply & prog cable that has to be removed ?

If I remember correctly you can force the P mode and leave it again to get something like a restart/reset of the T2 without pulling any cables.

**Comment by PablosScripts** [comment]
Na all of it has to be removed. 

Whenever I'm testing something or something isn't working, and need to restart the T2, I just unplug / replug the USB cable. 

However since I bought a power adapter, I notice that I have to unplug both of them now which is a pain. I think unplugging any one of them should reset it.

**Comment by prototypeGtuner** [comment]
I have had the same issue that i have solved with a remote socket switch. When i switch off the power supply the T2 restarts. It's an easy way to unfreeze the T2!

**Comment by J2Kbr** [comment]
With the power supply plugged the device always have power, so no reset will occur by unplugging the output cable. Alternatively, you can manually reset the device by pressing and hold both buttons for 2 seconds, then just press button again to leave the programming mode. this is a better approach as it will not wear-out the USB connectors and plug by repetitively unplug/plug.
