### ISSUE TITLE
Don't disconnect the T2 on sd-card read failure, ignore the sd-card and report error

### ISSUE THREAD

**Issue by Scachi** [J2Kbr/GtunerIV#187]
The Titan Two gets disconnected completely in GTuner on an sd-card read failure.
Instead of disconnecting the T2 completely, allow GTuner to report an error accessing the sd-card and ignore listing the sd-card slots (mark them red, or report the error in the output pane).

Maybe this would allow to format the sd-card from within gtuner even if it fails to mount/read the content itself ? This would make it a lot more user-friendly to get a sd-card working without the need of unplugging the sd-card and using an external reader to get it working again.

And I can still use the IDE to develop scripts without the need to remove the sd-card every time when running gtuner as the T2 itself can still run the slots from the sd-card without a problem, just GTuner fails t access its content.

**Comment by Scachi** [comment]
Seems like this is already done as of firmware 0.98.1.1 (12.12.2017) ? I got a sd card error reported one time and the T2 still stayed connected.
What is the correct procedure to try to reread the sd card ?
Reconnect the T2, eject/insert the sd-card again or is there a command / option to click to retry ?

**Comment by J2Kbr** [comment]
I have not - intentionally - fixed this issue. But glad to hear the seems now to be issue solved.

To re-read the sd-card, just unplug and plug it again from the Titan Two, while connected to Gtuner IV.

If the problem comes back, please comment here to reopen.

Thanks.
