### ISSUE TITLE
ACCEL_1_n   and GYRO_1_n swapped

### ISSUE THREAD

**Issue by Gandboss** [J2Kbr/GtunerIV#188]
When using a PS4 controller connected into Input A
In the left had Device Monitor pane.

The ACCEL_1_n  (PS4_ACCn) is displaying the GYRO_1_n values and 
the GYRO_1_n is displaying the ACCEL_1_n values.

**Comment by J2Kbr** [comment]
Hi Gandboss, thank you for reporting an issue. I checked the PS4 motion accelerators and gyroscope inputs and I believe everything is correct. The accels are directional forces, while the gyro are axial forces. I am closing this issue, if you have any comment or don't agree with my explanation, fell free to re-open. Thank you.

**Comment by Gandboss** [comment]
Jefferson
can you just double check this please.

Accel  parameters are giving a stable reading proportional to the handsets
static position - this seems wrong as that is consistent with the function
of a giro.

Whilst the Giro parameters are giving transient reading when the handset is
moving and this is consistent with the function of an accelerometer.

Thanks
Graham

(sorry I seem to have two accounts with you Gandboss & Celtic Magic Ill
close one)

Regards
Graham Law

*Celtic Magic*
www.celticmagic.org

**Comment by J2Kbr** [comment]
Hi Graham,

Please see this reference:

![image](https://user-images.githubusercontent.com/21229433/33455983-fe84b026-d604-11e7-8be7-396a2c5f155a.png)

The gyro only register a value when there is axial movement in one of the axis, while the accelerometer can measure force without movement (gravity), this is the reason ACCZ is -25 when the controller is, for example, resting on a table.

**Comment by Gandboss** [comment]
Ha!   Acceleration is gravity – how very pure Newtonian.   Sorry to have
diverted you.



BTW: I hope to deliver my first T2 as part of a system to help a near
paralysed young girl to play on her PS4.   Hopefully Ill get some video
clips & update you via your normal email next week if it goes ok.   Or
forum if you prefer.



Cheers

Graham

Regards
Graham Law

*Celtic Magic*
www.celticmagic.org
