### ISSUE TITLE
Feature Request - Script Activity Visualization

### ISSUE THREAD

**Issue by Fen-Ria** [J2Kbr/GtunerIV#194]
Would it be possible to have a way to show what parts of the script are actively being used/processed by the Titan when the script is loaded for testing and debugging via the Run GPC Script IDE button?

It would be extremely useful for finding issues that wouldn't be caught by the GPC Compiler, such as a script doing something it shouldn't due to incorrect scripting.

It would be even more useful if there was an adjustable refresh interval, and possibly a way to slow down the processing of the script, as instead of a CPU intensive real time visualization, a user could choose something less CPU intensive at the risk of missing something, or they might even get lucky and catch something they wouldn't normally notice due to the speed at which the script is normally processed.

Additionally, if a script were to stop functioning for whatever reason, you could have it show the lines of code that were active at the time it stopped functioning.

You could also use the output panel to show information on things like CPU errors/usage warnings or even problems with the script being used that might only arise when it's being run by the Titan Two due to a glitch.

Maybe you could even have it write everything to a text based log file afterwards, so a user could review it or share it on the forums to give additional details that they might not otherwise have.

If you need me to clarify something I have said, please let me know.

**Comment by J2Kbr** [comment]
After considering some approaches to implement this request, it was verified the addition of such debugging facilities would have significant impact (negatively) on the performance of the VM that runs the scripts, affecting even scripts that are not making use of it. I have also considered keep two copies of the VM, one for regular use and other for debugging scripts. Unfortunately the VM have big footprint and we don't have space on flash memory to keep both.
