### ISSUE TITLE
Feature Request - Average CPU Usage Visualization

### ISSUE THREAD

**Issue by Fen-Ria** [J2Kbr/GtunerIV#195]
Would it be possible to have a script show the average CPU usage of each line of code when the script is loaded for testing and debugging via the Run GPC Script IDE button?

Showing the average CPU usage as a number would be an effective way of doing so, and would be easily understandable.

If possible, maybe have an option to only show CPU usage for If, else if, and else conditions, with any if, else if, or else condition that is part of the result showing it's own usage, but contributing to the usage of the condition that allowed it to be checked.

For example, if there was one if condition that, when true, would check for two separate if conditions like so; "if (get_val(x)) { if (get_val(y)) {a+b}; if (get_val(z)) {c+d}; }" the first if condition would show the total CPU usage of all three if conditions and results, while the other two would only show the CPU usage of themselves and their results.

For example, "if (get_val(y)) {a+b};" would only show its own CPU usage, as would "if (get_val(z)) {c+d};", but "if (get_val(x)) { if (get_val(y)) {a+b}; if (get_val(z)) {c+d}; }" would show the total CPU usage of all three if conditions.

If you need me to clarify something I have said, please let me know.

**Comment by J2Kbr** [comment]
I've been thinking about this and researching some possible solutions. However, such facility would add too much overhead to control and register the CPU usage (clock ticks) for each operation of the script. We could create specialized functions to make the measurements only within defined bounds, but still the fact we have already used all hardware counters for other purposes, so there none available to register the clock ticks. I am closing this issue for now as it seems something not possible to implement, In case I find some viable solution this issue will be reopened. Thanks.
