### ISSUE TITLE
Input Reference - Make Nintendo Switch labels clearer

### ISSUE THREAD

**Issue by PablosScripts** [J2Kbr/GtunerIV#196]
Currently it's Accel vs. Joy Acc: 

https://i.imgur.com/kDqP6rw.png

This can be a bit confusing. Shouldn't it be Left Accel vs. Right Accel?

I can imagine people getting really confused by the description because both of them are actually Joycons! Because you only called one of them a Joycon I was left scratching my head for a few moments.

**Comment by J2Kbr** [comment]
The Left Accel and Right Accel would cause ambiguously when using the Pro controller. With Pro controller there is no differentiation from left/right, My idea was define only "Accel X/Y/Z" if the input can be from Joycon or Pro controller, and "Joy Acc X/Y/Z" if the input is sure to be from Joycon.

If you have another suggestion, please comment.
