### ISSUE TITLE
Feature Request - Keyboard Support - Retrieve values set by Key_Set() function.

### ISSUE THREAD

**Issue by Noxiferam** [J2Kbr/GtunerIV#197]
There is currently no way to retrieve the virtual status/value of a key previously set by the Key_Set() function. Having an analogue to the Key_Status() function that allows the retrieval of that information would be useful in many circumstances.

Best regards,

**Comment by J2Kbr** [comment]
Gtuner IV 1.00RC-35 add new functions `key_get()` and `mouse_get()` to retrieve the values set by _key_set()_ and _mouse_set()_.

The original _key_get()_ was renamed to `key_check()`.
