### ISSUE TITLE
Feature Request - Ability to disable script re-running on new report from controller

### ISSUE THREAD

**Issue by Fen-Ria** [J2Kbr/GtunerIV#198]
I have found out that having a script re-run on receiving new information from the controller can actually break certain scripts if one uses a controller that constantly sends new reports due to gyros or accelerometers.

It actually seems to be what is breaking a script I used quite often, and I noticed it might be caused by the fact that I was using a ps4 controller, as when I plugged in a wired 360 controller and tested it then, it worked fine.

Here is a link to the post on the forums I made when I discovered this:
https://www.consoletuner.com/forum/viewtopic.php?f=26&t=7565&p=57821#p57779

The post includes a small script that can be used to show how certain controllers can break some scripts, as well as images of the differences between having a PS4 or 360 controller plugged in, as well as one where no controllers are used.

I have also discovered that rapidly pressing buttons or moving the thumb-sticks on any controller connected to the Titan Two, even if it is not a PS4 controller, can also interfere with certain scripts to a similar extent, as doing so duplicates or nearly duplicates how a PS4 controller constantly sends new reports to the Titan Two, which in turn causes the script to constantly re-run.

The most easily affected scripts seem to be larger ones, especially those that use combos, functions, or timers that do not or can not reference the system time to ensure it runs properly, or where referencing the system time isn't enough to keep it running the way it is supposed to.

My assumption is that when re-running a script upon receiving a new controller report, it will re-run the script even if it is already in the middle of running instead of letting it finish it's current run.

Please inform me if my assumption is incorrect.

If it is not, then will need the ability to turn off the having a script re-run upon receiving a new report from a controller, or at the very least force it to wait till the script has finished it's current run, or it can and will cause issues with scripts as they get larger and more complex.

If you have any questions or need me to clarify something, please let me know and I will do my best to provide you with more information.

**Comment by J2Kbr** [comment]
> My assumption is that when re-running a script upon receiving a new controller report, it will re-run the script even if it is already in the middle of running instead of letting it finish it's current run.  Please inform me if my assumption is incorrect.

This assumption is incorrect, the script finishes the current execution before run again for the new received report from the controller(s).

As this issue is related/duplicated with J2Kbr/TitanTwo#106, I am closing this one.
