### ISSUE TITLE
Feature Request - Macro Recorder - Custom sampling rate.

### ISSUE THREAD

**Issue by Noxiferam** [J2Kbr/GtunerIV#199]
The Macro Editor can be used to create/edit macro files with a resolution of 1ms but the Macro Recorder samples the data at a rate of 100ms. While this is fine for most situations, in some cases having a more precise reading of the inputs would be preferable (especially on long recording) as it would drastically reduce the amount of time required to manually edit the input's timing.

Would it be possible to implement an option to modify the sampling rate of the Macro Recorder?

**Comment by J2Kbr** [comment]
The rate of the Macro Recorder is 10ms (not 100ms). I appreciate your suggestion, but change the sampling rate of the Device Monitor / Macro Recorder is not possible due limitation of the USB interface, we already have it almost saturated.

What I plan to do is implement a set of functions to enable scripts to save the macro file direct on the Micro SD-Card with 1ms resolution. The file can then be copied to the computer and edited using Gtuner IV.
