### ISSUE TITLE
Interactive config presets/settings based on a string for copy/paste

### ISSUE THREAD

**Issue by Scachi** [J2Kbr/GtunerIV#205]
It would be nice to be able to share all the interactive configuration settings of a script/slot with other users via copy/paste in a single string, something like you seems to have in the  top-left corner in the Mouse XY converter. 

This would help to debug problems other users have with a script a lot, too.
I could requests their IC setting string and paste it on the same script in my T2 on a memory slot and have the same settings active.

Full discussion: https://www.consoletuner.com/forum/viewtopic.php?f=26&t=8145

It would be useful if I can omit IC values from the "IC setting string" for some settings.
Like I have a script with fire-modes and anti-recoil, but want to set the anti-recoil only,
That would require the string to be somewhat human readable.
If the anti-recoil byteoffsets are 1 , 2 and 5
Like `#1:14#2:33#5:2`

Where 
`#1:14` = 1: is the byteoffset
`#1:14` = 14: is the value for the byteoffset

Allowing a printf statement to set preset values in the same logic would make using presets easier too:
So I can do a single printf statements to set multiple values of different types:
`printf("GCMD:IC.Set:#1:14#2:33#5:2");`

Some individual gpc code for setting multiple pmem values with a single string: https://www.consoletuner.com/forum/viewtopic.php?f=23&t=8228

**Comment by J2Kbr** [comment]
Added to Gtuner IV 1.00RC-55

The string representing the configuration is the pmem array in hex format, example:

`GIVICFG:000000000100000000FFE2FC18`

Is possible change only specifics byte(s) by providing the byte offset (similarly as suggested by you)

`GIVICFG:#10:FFFFFF`

This will set 3 bytes to 255 starting from position 16. The other bytes are not changed.

`GIVICFG:#10:FFFFFF#02:010203040506070809`

Here we are doing same as previously and also setting 9 bytes from position 2 with values 1, 2, 3, 4, 5, 6, 7, 8, 9. 

If the configuration string does not specify a byte offset (like first example), the byte offset is assumed to be 0 and the configuration array is set to 0 before apply the values from the configuration string.

When publishing a work is now possible add configuration suggestions on the description with the HTML tag `<code>`, example:

`<code>GIVICFG:#0A:FFFFFF#02:010203040506070809</code>`

This tag will format the configuration string in a special container with a button to easy copy.

Updating the Interactive configuration is also possible via script with `GCMD:InteractiveConfiguration.GIVICFG`, example:

`printf("GCMD:InteractiveConfiguration.GIVICFG:0000000001FF9C0000FFE2FC18");`

**Comment by prototypeGtuner** [comment]
What a great feature!

Is it possible to have the configuration suggestion code in the IC like in the work description?

**Comment by J2Kbr** [comment]
One click predefined configurations on Interactive Configuration added to Gtuner IV 1.00RC-58
