### ISSUE TITLE
GTuner crash/non responsive when compiling uncomplete function declaration

### ISSUE THREAD

**Issue by Scachi** [J2Kbr/GtunerIV#206]
I had a bigger script, was copying some stuff around and forgot that I had this piece of an uncomplete function declaration at the end of the script:

```void CfgStr(uint8 length, char```

I hit F7 and the GTuner windows got unresponsive. I waited a couple of minutes but had to close the application the hard way.

**Comment by J2Kbr** [comment]
Fixed on Gtuner IV 1.00RC-50. Thank you for reporting.
