### ISSUE TITLE
Add "just pressed" events for keyboard, and controller inputs

### ISSUE THREAD

**Issue by AJSinc** [J2Kbr/GtunerIV#207]
Similar to the "event_press" feature of the T1, it would be nice to have the same for keyboard keys, and maybe an updated on for the T2. 

These functions would only return true once when they key was just pressed. Otherwise it would return false.

- "key_just_pressed" (ASCII keyboard)
- "button_just_pressed" (XB1/PS4 etc controllers)

**Comment by Scachi** [comment]
There already is "event_active" for buttons.
I made an example, based on some code from J2kbr, some time ago that adds some similar functions for keys: https://www.consoletuner.com/greslib/?w242

**Comment by AJSinc** [comment]
Thanks, that helps a lot!
