### ISSUE TITLE
Add option to set user key to exit KB Capture's Capture Mode

### ISSUE THREAD

**Issue by AJSinc** [J2Kbr/GtunerIV#208]
Maybe I've missed the option, but as of now it seems Ctrl + Esc is the only key combo to exit capture mode. If would be great to have an option to exit capture with a single key, for example hitting F12 would exit capture mode. 

Thanks,
Snap

**Comment by PoshLemur** [comment]
+1 Would like to have this, or the ability to set a custom exit key.
Using my keyboard, I normally have Ctrl bound to Circle and Esc bound to Options. Both tend to conflict poorly with whatever game I'm playing. Like when I'm waiting in queue for a multiplayer match where Circle will cancel it. Pressing Ctrl + Esc causes me to accidentally exit the queue.

**Comment by J2Kbr** [comment]
The key or key combination to exit capture mode can now be customized with Gtuner IV 1.00RC-80 (Tools:Preferences).
