### ISSUE TITLE
Add ability to link to script doc via Interactive Configurator

### ISSUE THREAD

**Issue by PablosScripts** [J2Kbr/GtunerIV#210]
I think this will become even more important once the mobile app comes out. 

Currently, if a user doesn't see the "DOC" icon when they download a script, they may never see it again. What I have done is I've added a link to my doc page in my Interactive Configurator description, but you can't click it. Please see the ideas I have below: 

https://i.imgur.com/GQSGshb.png

**Comment by J2Kbr** [comment]
This is already possible (Idea 2).

In the shortdesc you can include links with `a` tag, example:

`<a href="http://www.consoletuner.com/wiki/index.php?id=t2:gamepacks:farcry_5">Online Instructions</a>`
