### ISSUE TITLE
Feature Request - Software Control to Reboot Titan Two Adapter

### ISSUE THREAD

**Issue by ciphray** [J2Kbr/GtunerIV#211]
Occasionally have issues with connectivity on both bluetooth and the xbox one wireless adapter (persists even if the controller battery is pulled still thinks controller is connected and the disconnect bluetooth does nothing when this happens), pulling the power adapter out and plugging back in to reboot it always corrects this, would be nice to have a control to do this without playing with the hardware itself

**Comment by J2Kbr** [comment]
Thank you for your suggestion.

Force reboot of the device can be achieved with the following code:

`while(TRUE);`
