### ISSUE TITLE
Search not including decimals

### ISSUE THREAD

**Issue by PablosScripts** [J2Kbr/GtunerIV#212]
I had the following string in my code "4.00" and searched for "4.00", and it ended up searching for every instance of "400" as well.

**Comment by Scachi** [comment]
It seems to handle the . like regexp goes ( and I like that )  as searching for "4.00" find 4.00 and 4000 (but not 400)
Searching for "4\\.00" only finds 4.00 for me.

**Comment by J2Kbr** [comment]
Scachi is 100% correct, The search is regex enabled and, as such, "." is a wildcard that matches any character. Use backslash "\." to search for the actual dot character.
