### ISSUE TITLE
Input Translator "QoL" Improvements

### ISSUE THREAD

**Issue by AJSinc** [J2Kbr/GtunerIV#214]
I have a suggestion for the Input Translator section of GtunerIV. As of now, it all shows up as generic "BUTTON_1", "BUTTON_2", etc. Would it be possible to have a combo box with options such as "Generic", "Xbox One", "PS4", etc (maybe you could add a directory to the T2 install area so users can add their own controller definitions and have it show them in the combo box too) so it shows those controller definitions instead?

One other QoL change I can think of is the keyboard/mouse input translator area too. As of now, it is a combo box with a huge list of keys. Maybe instead of this, 2 more options could be added to the current combo box to get the users input for keyboard keys or mouse buttons (similar to MaxAim's way for the Titan One). I understand you can type to sort of find what key you want, but it would be easier to just have it get the user input key. An option for mouse smoothing similar to MaxAim's/XIM would be appreciated too!

**Comment by J2Kbr** [comment]
I am avoiding console specific denominations to not recur in an common issue we have with the Titan One, where users assumes that scripts with PlayStation references will not work on Xbox and vice-versa. This frequently generate requests of script conversion in our forums.

However, Gtuner IV have a QoL facility for this. By pressing F1 a popup window will open with the GPC designators and corresponding console inputs. This window not only works for quick reference, but also to help with code creation and combo box selection. If you are working on a script code, by double clicking an entry in the reference table will insert the corresponding GPC designator on the code. Similarly, if a combo box of GPC designators is the active component (with focus), by double clicking an entry in the reference table will make the corresponding GPC designator to be selected.

As for your second request, this is already in my to do list. ;)

Thank you.
