### ISSUE TITLE
"event_active" does not work while the T1 header is included

### ISSUE THREAD

**Issue by AJSinc** [J2Kbr/GtunerIV#215]
I'm not sure if this is intentional, but "event_active" does not ever return true with the T1 header included. Because of this I have to use "event_active", which isn't a big deal, but is weird behavior to me.

**Comment by AJSinc** [comment]
I stated part of this wrong, I have to use "event_press" instead of "event_active", which is weird, especially since event_press is just a macro function..

**Comment by J2Kbr** [comment]
I tried reproduce this issue, but worked as expected.

Please note `event_active()` expects the Titan Two button references (BUTTON_1, BUTTON_16, etc), while `event_press()` expects the buttons references defined in the `titanone.gph` header file (PS4_CROSS, XB1_Y, etc). Perhaps mismatching one with the other is what is causing the issue.

If is not the case, please comment to reopen this issue and also provide an small example code which I can test.

Thank you.
