### ISSUE TITLE
Online Resource Tab - Reduce spacing for the shortdesc ul / li listings

### ISSUE THREAD

**Issue by Scachi** [J2Kbr/GtunerIV#217]
I think it looks like a waste of space at the moment.
Half the height for the spacing may still look good enough for good readability.

This is how it looks for me in Windows 10:
![shortdesc_ul_li spacing](https://user-images.githubusercontent.com/22262242/39244787-08753556-4892-11e8-8f79-7532cfc0da63.jpg)

**Comment by J2Kbr** [comment]
The issue was the automatic conversion or line breaks (\n) to `<br>`. The behavior was changed to not make the conversion right after a HTML tag and it should solve the issue with `<ul>` and `<li>`.
