### ISSUE TITLE
Output Panel - "Clear Selection" does not work

### ISSUE THREAD

**Issue by Scachi** [J2Kbr/GtunerIV#218]
Right clicking on a line or selection in the output panel and selecting "Clear Selection" isn't doing anything.

Copy and Clear All is working fine.

**Comment by J2Kbr** [comment]
When an message is selected in the Output Panel it is highlighted with a different background color. Clear Selection just unselect the message to remove the different background color. I see the naming can cause confusion. It was renamed to "Unselect" on Gtuner IV 1.00RC-58.
