### ISSUE TITLE
Feature Request - GTuner IV Plugin Programming

### ISSUE THREAD

**Issue by Scachi** [J2Kbr/GtunerIV#219]
A plugin programming option would be great so we can develop funny little tools that do stuff like parsing the text of the output panel 
and run commands on string matches like controlling a music player from within a T2 script 
or start/stop record/play of macros on the fly from within a script.

**Comment by Scachi** [comment]
Will the API allow doing stuff like that ? Feel free to close this if this is the case.

**Comment by J2Kbr** [comment]
Plugins as know in other applications like Notepad++ are very complicated to implement on multi-platform software. For this reason I have no plans to support plugins with Gtuner IV. However, printf() messages from the Titan Two will be available via the API, which should be enough for what you are describing.

There is also this approach:

https://www.consoletuner.com/forum/viewtopic.php?f=26&t=9080

Not sure if you saw on the forums, very interesting.
