### ISSUE TITLE
Feature Request - printf command to record/playback macros in GTuner IV

### ISSUE THREAD

**Issue by Scachi** [J2Kbr/GtunerIV#220]
When playing the game I often find myself in a situation like: 
Oh, so I have to press this button combination a 100 times just for this situation or get up, go to pc and do some scripting to extend my current script, but I am lazy and don't want to get up now ...

Having the option to start a macro recording and play/stop it from within a script via a printf statement would be nice. 
Record macros and play them back without the need to touch the PC or edit the script, letting GTuner do the work.

So I can use simple printf statements to have in-game adjustable macros for scripts/slots:
printf("GCMD:MacroRecordStart:MacroName:AllsThe ButtonsInputsINeedOrJustEverything:RecordIntervall);
printf("GCMD:MacroRecordStop);
printf("GCMD:MacroPlay:MacroName);
printf("GCMD:MacroPlayLoop:MacroName);
printf("GCMD:MacroPause:MacroName);
printf("GCMD:MacroStop:MacroName);

**Comment by J2Kbr** [comment]
The next Gtuner (1.00RC-62) and FW (0.98B-55) releases feature a new GPC function: `macro_rec("filename.gmk");`

With this function you will be able to have the script to record the macro and then play it back without rely on Gtuner IV.

The suggested GCMD would not work very well, specially for the play, pause and stop cmds as this would unload your script to play the macro file.

PS.: macro_rec() have 1ms resolution, in oppose of Gtuner IV that samples at 10ms.
