### ISSUE TITLE
DS4 ACCEL / GYRO

### ISSUE THREAD

**Issue by briankincaid** [J2Kbr/GtunerIV#221]
The ACCEL and GYRO mappings are mislabeled in Gtuner IV device monitor

This might affect existing scripts, but the GYRO is clearly mapped to Accel

**Comment by J2Kbr** [comment]
The accelerometers registers the instantaneous acceleration in the direction of X, Y and Z axis. If the controller is left standstill on a flat surface you can note the X and Y are 0 and Z is -25. 25% is equivalent to 1G, so Z is registering the earth gravitational acceleration.

On the other hand, the gyro register the centripetal acceleration on the X, Y and Z axis. If standstill all gyros will be 0, only registering values if there is rotational movement in one or more axis.

I rechecked this and the Device Monitor is registering correctly for PS4 controller.
