### ISSUE TITLE
GTuner IV API / documentation

### ISSUE THREAD

**Issue by briankincaid** [J2Kbr/GtunerIV#222]
I would like to call GTunerIV from another programming language.  Can we get some API documentation to set this up?

I would like to send 'virtual input' to GTuner IV to be treated as an input device and sent to the Titan 2

**Comment by J2Kbr** [comment]
The API is planned to be implemented soon and the documentation for it will be available in the Titan Two wiki: https://www.consoletuner.com/wiki/

Thank you for your suggestion.
