### ISSUE TITLE
Add the "Install" button command to the top-menu

### ISSUE THREAD

**Issue by Scachi** [J2Kbr/GtunerIV#223]
The Install command is only available as a button in the compiler-toolbar, would be nice to have it available via the top-menu in the "Compiler" section too.

Its a lot easier to tell people where to find the command in the menu than as an icon if they ask how to compile & install a custom script posted in the forum.

**Comment by J2Kbr** [comment]
The Compiler menu have items related only with script code, while the action Install can also be applied to other files, such as GIT. The best context for this is the File menu. Added on Gtuner IV 1.00RC-62.
