### ISSUE TITLE
Output panel - clicking on gpc warning line creates error popup (Open File Error)

### ISSUE THREAD

**Issue by Scachi** [J2Kbr/GtunerIV#224]
Someone posted a script (attempt to merged two scripts into one), the gpc file is attached:
Code is also posted at the bottom of this post: https://www.consoletuner.com/forum/viewtopic.php?f=26&t=8719&p=63674#p63539

There is some macro redefinition problem in this script (fixing the code itself doesn't matter here)
When compiling it the output panel reads:
```
GPC error: error.gpc(9): Can't open include file 'light_k.gph'
GPC warning: error.gpc(611): The macro is redefined
GPC warning: error.gpc(612): The macro is redefined
GPC warning: error.gpc(613): The macro is redefined
GPC warning: error.gpc(614): The macro is redefined
GPC error:     previously macro "L_Y" defined as: #define L_Y STICK_2_Y 	/* error.gpc:32	*/
```
Double-clicking on the first warning (line 611) jumps to the correct line.
But double-clicking on the second (line 612) it opens a popup for me:

![grafik](https://user-images.githubusercontent.com/22262242/39719356-46596b7a-5239-11e8-8f95-da62d009cd3b.png)

[error.zip](https://github.com/J2Kbr/GtunerIV/files/1981098/error.zip)

**Comment by J2Kbr** [comment]
Issue fixed on Gtuner IV 1.00RC-60. Thank you for reporting.
