### ISSUE TITLE
Page break not auto added to <shortdesc> if there is a preceding </b> tag

### ISSUE THREAD

**Issue by PablosScripts** [J2Kbr/GtunerIV#226]
A few updates ago you added the ability for `<shortdesc>` to auto-add page breaks, so you no longer needed to use the `</br>` tag. 

So this: 

```
Line 1

Line 2
```

Would be displayed like this: 

```
Line 1

Line 2
```

That works great. However I have found that if Line 1 contains a `</b>` tag, this doesn't work. 

So this: 

```
<b>Line 1</b>

Line 2
```

Becomes this: 

```
Line 1
Line 2
```

This is not so good, the space between the two lines has gone. The way to "fix" this is to add a space after the `</b>` tag. 

So this: 

```
<b>Line 1</b> [single space right here]

Line 2
```

Becomes this: 

```
Line 1

Line 2
```

So there is a work around, but it's not ideal. Here's an actual screenshot of my code to show you what I mean:

![image](https://user-images.githubusercontent.com/22415147/39872467-66523ff0-54ab-11e8-921e-9d2172124526.png)

**Comment by J2Kbr** [comment]
I was going to suggest the exactly workaround you pointed out (add space), alternatively you can explicit add the `<br>` tag.

I know this is not ideal but there are many cases were is not desirable automatically add `<br>` after another HTML tag, as described in the GitHub #217.
