### ISSUE TITLE
shortdesc info control with MULTILINE html tags problem

### ISSUE THREAD

**Issue by Scachi** [J2Kbr/GtunerIV#227]
I have no idea why this isn't working in every info multiline control
when using the script below and hitting F9 for preview:

```
#pragma METAINFO("htmltest", 1, 0, "Scachi")

/*
<cfgdesc>

[Test 1 Works]
shortdesc	= <<<MULTILINE
<b>123</b>
123
<b>123</b>

MULTILINE
control		= info


[Test 2 works]
shortdesc	= <<<MULTILINE

<b>123</b>

MULTILINE
control		= info


[Test 3 works not]
shortdesc	= <<<MULTILINE
   some text in the first line breaks the html parsing 
<b>123</b>

MULTILINE
control		= info

[Test 3 works not]
shortdesc	= <<<MULTILINE
   some text in a line breaks the html parsing <b>this text is hidden</b>
   and this is shown as text: <b>123</b> 
MULTILINE
control		= info

</cfgdesc>

*/

main {
}
```

**Comment by J2Kbr** [comment]
Fixed on Gtuner IV 1.00RC-62 by explicit forcing HTML parsing for shortdesc.

**Comment by Scachi** [comment]
This seems to break existing shortdesc multiline content and require to use 
```<br>```
tags for all line breaks.
How should I handle this correctly ? This is a screenshot from my Destiny 2 script (available in the Online Resource)

![grafik](https://user-images.githubusercontent.com/22262242/42011084-147f4c92-7a92-11e8-8a6a-d3e9d4cb7042.png)

**Comment by J2Kbr** [comment]
Gtuner 1.00RC-63 automatic add break tag before new lines on shortdesc.
