### ISSUE TITLE
Feature Request - Interactive Configuration - Button name translation

### ISSUE THREAD

**Issue by Scachi** [J2Kbr/GtunerIV#228]
It would be nice to be able to write something like this
```
[Demo]
shortdesc	= Toggle this with hold BUTTON_8 + tap BUTTON_10
byteoffset= 0
bitsize		= 1
bitoffset	= 0
control		= checkbox
default		= 1
item			= Enable
```
and have it to show up with the button names the user is used to, like if he is on PS4 (output protocol set or automatically recognized as ps4):
![grafik](https://user-images.githubusercontent.com/22262242/39957232-e0612fa0-55ef-11e8-88e7-b983ff4154c1.png)

Maybe marking it with a small icon/graphic/background graphic would be cool too.

**Comment by prototypeGtuner** [comment]
I thought of something like that but would use icons of each button depending on the platform used but it will require to be able to display icons in the IC.

**Comment by Scachi** [comment]
Great idea, showing the button icons of the controller of platform connected/configured looks cool and everybody will understand them right away.
Could also be used to solve this: https://github.com/J2Kbr/GtunerIV/issues/253

**Comment by J2Kbr** [comment]
Hi Guys, there are few challenges to implement this request.

First is how to determine which type of labeling to use (GPC, PS4, Xbox, etc), would be user selectable? based on connected controller (which)? on connected console? and if there is no device connect to Gtuner IV/Air? etc. Then find a way to track and replace the "keywords" with acceptable performance, not only the description fields, but also on controls (e.g. the list options of a combo-box).

However, the main issue is do all that on Gtuner IV and Gtuner Air. Both applications relies on the same configuration descriptor, but the backend implementation that built and control the interactive configuration interface are completely different, which makes very challenging find a solution that works and has consistent behaviors for both applications. I will close for now, if eventually we find a way to implement we reopen. Thanks.
