### ISSUE TITLE
Add a feature to list all the unused combos, functions and variables

### ISSUE THREAD

**Issue by PablosScripts** [J2Kbr/GtunerIV#23]
Over time a lot of junk builds up and it's difficult to pin point what needs to be cleaned up. It would be good to have a spell check style feature where it lists all the unused parts of your code for you to go and manually clean up.

**Comment by J2Kbr** [comment]
Implemented on Gtuner IV 0.95B. After the second-pass, an list of unreferenced variables, functions, combos and/or labels will be printed if applicable.
