### ISSUE TITLE
Request: Reload File in IDE

### ISSUE THREAD

**Issue by PoshLemur** [J2Kbr/GtunerIV#230]
I like to do my programming in 3rd party editors such as Atom. It would be extremely helpful to have the ability to make Gtuner reload a file tab, currently I have to close the file in Gtuner and reopen it to get the file to update in the IDE.

My idea of how it could be implemented.
Gtuner > Right click on tab > **Reload File**
Gtuner > File > **Reload Active Tab**
Gtuner > Tools > Preferences > Script Editor > [Checkbox] **Reload files automatically when file is updated.**

**Comment by J2Kbr** [comment]
The first suggested option (Reload from the Tab context menu) added to Gtuner 1.00RC-62.
