### ISSUE TITLE
Add version number to tab

### ISSUE THREAD

**Issue by PablosScripts** [J2Kbr/GtunerIV#232]
When I'm making changes, I like to make a note about which version it pertains to, e.g. 

```
// v4.05, added this or that
(code change here)
```

However I find myself having to constantly scroll back to the top of my file to see the pragma metainfo to see what version I'm on. It would be good if this was displayed in the tab. See the mockup below.

![image](https://user-images.githubusercontent.com/22415147/40286244-c2d4db26-5ce8-11e8-8fa6-41807748d31d.png)

**Comment by J2Kbr** [comment]
Feature implemented on Gtuner IV 1.04. When the mouse cursor is over the code editor tab, a tooltip with file info + script metainfo (if present) is shown.
