### ISSUE TITLE
Feature Request - Device Monitor : LED_1..4 Color visualisation as  it will be displayed by the lightbar

### ISSUE THREAD

**Issue by Scachi** [J2Kbr/GtunerIV#235]
It is useful to see the different LED_1 .. _4 values set as it is right now
but I would be helpful to have it displayed as a color too, is this is possible and you can find a good place for it.

This would help to see the actual color during coding/script testing without looking at the controller or t2 that might be placed somewhere away from the computer so it is hard to see ( I am using long usb extension cables).

**Comment by J2Kbr** [comment]
Gtuner IV 1.00RC-68 adds a discrete bar to display the current Titan Two / Dualshock 4 lightbar color:

![device monitor lightbar color](https://user-images.githubusercontent.com/21229433/42813301-ed3040b0-8996-11e8-8523-49425c3582da.png)

**Comment by Scachi** [comment]
This is working great.
The only issue i have that settings the T2 brightness to 50, the LED of the T2 is much brighter than the lightbar visualization.

Setting brightness to 25 is still good visible on the T2 itself, on the lightbar visualization it is impossible to tell the color shown.

 It may be just my monitor brightness, don't know. Would be great if you can test it if it is the same for you and maybe adjust the lightbar visualization to match the brightness for lower values better ?
