### ISSUE TITLE
Feature Request - GPC Script IDE : hover tooltip for #define's

### ISSUE THREAD

**Issue by Scachi** [J2Kbr/GtunerIV#236]
It would help speeding up coding a bit if a define would have a tooltip on hover where I get information about the value/content of a define.

Example, having something like this:
#define _AC22   1
#define _AD289  2
#define _AD334  3
#define _EAT17  4
#define _EX044  5
#define _EX048  6
#define _EX051  7

and using one of them later in the code and I may need to lookup the value of it for some cross referencing I have to scroll to the define to get.
With the feature requested it would save me from scrolling around and would show the value in a tooltip when the mouse is over _EX044, it would show ": 4" for example 

Don't know if this possible at all, well I can just change my define to _EX044_5 to have the same effect but that would require to change the name each time I want to change the value of a define

**Comment by PoshLemur** [comment]
Would love to see this! +1

I imagine this would be pretty difficult to program though. The cursor would need to know what text if any is below it, from what I can tell the whole script editor in GtunerIV is just a QTextEdit using QSyntaxHighlighter.

**Comment by J2Kbr** [comment]
Feature implemented on Gtuner 1.04, works on defined values within the current file, as well as from included header files.
