### ISSUE TITLE
Feature Request: Native Support for Key_Event_Active / Key_Event_Release (KBM)

### ISSUE THREAD

**Issue by PoshLemur** [J2Kbr/GtunerIV#238]
I realize there are some scripts written by you and enhanced by the community to add an event_active and event_release trigger for keyboards and mice. However I've found all of the implementations somewhat lacking. Your script is lightweight but not very robust. Buffy's adaptation is more robust but also prone to performance issues.

I feel having more _native_ Keyboard/Mouse support (if possible) would go a long way towards making the Titan Two more viable than it already is for us KBM players.

**Comment by AJSinc** [comment]
I've since fixed the performance issues/optimized it a bit. The issues was the "key_event_active", I had it checking too see if it was active, event without the key itself being active. Checking whether the key is active first improved performance by ~20%
https://www.dropbox.com/sh/hc4m2s0m04dhzii/AACYcctVbiIIlop466cGCsyOa?dl=0

Overall, due to the power of the CPU of the T2, I do not believe an actual solution can be made.

**Comment by PoshLemur** [comment]
Thanks Buffy I'll check your updated version! When was this file updated? I have yours and J2Kbr's version that I pulled about a month ago. I've been doing some extensive rewrites to them to add functionality and reduce the CPU usage, but I've been finding it a difficult balance of sacrificing stability for performance. Especially when monitoring more than 10 keys.

I'd still like a native key_event_active and key_event_release built into the T2 though, if at all possible.

**Comment by AJSinc** [comment]
I updated it after J1Kbr added the ability to use sizeof with arrays. I'd be interested in seeing what extra functionality you've come up with.

**Comment by PoshLemur** [comment]
Sure, I'll post it on the forum in that thread. Maybe you can help me fix it, I was working on some optimization a couple of weeks ago to try and bring the CPU usage from currently 160%~ down to 20%.
It worked but simultaneously broke one of my additions, haven't had the time to look into it much since then.

**Comment by J2Kbr** [comment]
As the request was fulfilled with PoshLemur's header file, I am closing this issue. (Thank you PoshLemur)
