### ISSUE TITLE
Ignore Controller Input (KB/M capture)

### ISSUE THREAD

**Issue by AJSinc** [J2Kbr/GtunerIV#239]
It'd be nice to have an  option "Ignore controller input" with the KB/M capture. Sometimes a drift in the controller can negatively affect the KBM capture, althought sometimes I do like to use the controller so it'd be nice to have it as a toggle.

**Comment by briankincaid** [comment]
Yes when using a PS4 controller for authentication I would sometimes like to be able to ignore certain inputs from that controller (like acceleration so I can use it directly)

Best regards,
Brian (Daniel) Kincaid

On Jul 7, 2018, at 12:37 PM, AJSinc <notifications@github.com<mailto:notifications@github.com>> wrote:


It'd be nice to have an option "Ignore controller input" with the KB/M capture. Sometimes a drift in the controller can negatively affect the KBM capture, althought sometimes I do like to use the controller so it'd be nice to have it as a toggle.

**Comment by J2Kbr** [comment]
This feature is available via Input Translator, which can be activated with GIT file or via script with remapper_disable() function. To disable the inputs from the authentication controller (or only the right stick), select the option "Disabled" and check only the port the controller is connected (i,e, USB-B). OR, with a script:

```
init {
    remapper_disable(STICK_1_X);
    remapper_disable(STICK_1_Y);
    remapper_mask(RMP_USB_B);
}
```
