### ISSUE TITLE
Add global setting to dim LED's on T2

### ISSUE THREAD

**Issue by PablosScripts** [J2Kbr/GtunerIV#24]
Personally I didn't find this a huge issue but I was surprised to see almost everyone mentioning how bright they are. Therefore I suspect when this is released, the vast majority would prefer them to be dimmer.

I would add a few settings, and set the default to be a few notches below where it is now.

**Comment by J2Kbr** [comment]
Feature partially implemented on Gtuner IV 0.93 Beta and Titan Two FW 0.76 Beta.
The Device Configuration pane now features "Default LED Intensity", which can be used to set the default lightbar intensity of DS4 controllers and, in future update, will also affect the intensity of the Titan Two lightbar.

**Comment by J2Kbr** [comment]
Firmware 0.77B implements intensity on Titan Two's lightbar. Configurable on Gtuner IV, by the control above described; or by script, using led_set command.
