### ISSUE TITLE
Emulating the 360/XB1 Chatpad

### ISSUE THREAD

**Issue by AJSinc** [J2Kbr/GtunerIV#240]
I know this may seem a bit silly, but would this be possible? I know it'd be a bunch of extra buttons, but it'd be nice to be able to forward actual KB inputs to the console (games like Fornite, ARK, Conan, Minecraft, etc) all accept keyboard inputs, and the chatpad acts as a USB keyboard.

Aside from this, the chatpad could also be used to activate macros and such.

**Comment by prototypeGtuner** [comment]
There is also the PS3 chatpad , this one use Bluetooth.

**Comment by J2Kbr** [comment]
For better relevance, I will be moving this request to Titan Two firmware GitHub.
