### ISSUE TITLE
shortdesc control with MULTILINE <pre> tag problem

### ISSUE THREAD

**Issue by hhezart** [J2Kbr/GtunerIV#241]
Issue #227 added automatic break tag before new lines on shortdesc but it has introduced a side effect where extra line breaks are displayed in the `<pre>` tag.
```
[MOD Toggle]
control		= info
shortdesc   = <<<MULTILINE
<pre style="background-color:#f5f5f5;">
 Away From KB: L2 + SHARE
 Weapon Reset: L2 + DOWN
</pre>
MULTILINE
```

**Comment by J2Kbr** [comment]
Fixed on Gtuner 1.00RC-68
