### ISSUE TITLE
Console-specific guidance

### ISSUE THREAD

**Issue by PablosScripts** [J2Kbr/GtunerIV#242]
I notice on the forums, the problem of not using the correct communication method always comes up, example:

https://www.consoletuner.com/forum/viewtopic.php?f=2&t=9412

If the output protocol is set to a console with specific setup needs, or it is auto detected somehow, why not provide some in-app guidance to users? It could be through the compiler area (like you do with update notifications), or a pop-up, or something else, which would reads something like "Remember do X, Y and Z if you are using a PS4 Pro...". This will make the customer experience better and reduce the number of pointless support requests.

**Comment by prototypeGtuner** [comment]
If i remember the wiki could be integrated in Gtuner IV and could help to have a quick access to all the documentation.

**Comment by Scachi** [comment]
I don't know how this feature is named correctly..
Other programs have something like "first usage notifications", when the program is started for the first time it shows some important usage notes, or startup tips where you have a checkbox to "stop showing tips at startup".
Or a first start does  start a wizard where you do select the "primary/main use for console :" and get a selection of "PS4/XBOX/whatever" where you click on it and it shows the important notes as a short text as possible to grab the users attention like "Set on PS4 communication method ..".
That is just one click more at very first start of GTuner but will help new users a lot.

This will also help with this -> https://github.com/J2Kbr/GtunerIV/issues/228

**Comment by J2Kbr** [comment]
The implementation from #253 should also solve this latest request. Thanks.
