### ISSUE TITLE
Interactive Configuration : config presets & collapsible =2 -> bug or feature

### ISSUE THREAD

**Issue by Scachi** [J2Kbr/GtunerIV#243]
Using the config control in a grouped collapsible=2 section does show the buttons greyed-out instead of hiding them. Not sure if this is the way it should be or if this is a bug.
Unfolding it and fold it again does hide the buttons correctly.

This if what my Helldivers script (available at the online resource) looks like (with F9 preview) with the config control grouped to a collapsible=2 section Loadout Tracking - Stratagems Inventory:

![grafik](https://user-images.githubusercontent.com/22262242/42677475-28d45c00-867c-11e8-839b-195b4ccf033e.png)

Unfold and fold it again it hides the buttons correctly:
![grafik](https://user-images.githubusercontent.com/22262242/42677573-7296495c-867c-11e8-909f-3862f71eba7d.png)

**Comment by prototypeGtuner** [comment]
Same for me with this code:

[Suggested Settings]
collapsible = 1
shortdesc	= One click predefined configurations:
control		= config
item        = ONLINE :
item        = OFFLINE:

Like you when collapsible is set to 2 the items are greyed-out but it works fine when it is set to 1.

**Comment by J2Kbr** [comment]
Issue fixed on Gtuner IV 1.00RC-68.
