### ISSUE TITLE
Feature Request / QoL - Have Gtuner IV "Online Resources" section sorted by game

### ISSUE THREAD

**Issue by AJSinc** [J2Kbr/GtunerIV#244]
I believe this would be more of a QoL improvement to Gtuner IV. Instead of people asking for specific scripts  (which already exist) for games and such, it'd be easier for them to just find the game in Gtuner and see if it exists there. 

The way I imagine it would be replacing "Gamepacks" tab (Input translators, and script tabs could also be removed) with "Games", and instead just having the game title, and clicking on the title would lead to a games "hub".

Within each games hub, there could be an official gamepack and ST at the top. then it could show user submitted files for that game.

It would also be easier for people to request new games to have added support/scripts.

**Comment by prototypeGtuner** [comment]
There is a powerfull search function with keywords in the Online Resources, just type the name of the game. When a script is published the publisher can add several keywords to help the users to find what they are looking for.

**Comment by AJSinc** [comment]
The problem with that is every dev does not name games/keywords the same way. There are a bunch of different ways people abbreviate Call of Duty titles, CoD WW2, CoD WWII, Call of Duty WW2 etc. Having everything sorted in a game hub saves the users trouble, hence a QoL improvement.

**Comment by prototypeGtuner** [comment]
It's the publisher's work to add all the possible keywords for the published work, you can add dozens.

**Comment by Scachi** [comment]
Some help in getting the keywords right would be nice.
On Thingiverse when publishing something new and adding keyword to it it will tell how many time that keyword had already been used and list other similar names with a counter of their usage.
So a publisher gets an idea what keywords to use.
That is all online on Thingiverse via browser.. so GTuner IV might have to fetch and store the keywords locally or test and report them when publishing.

**Comment by prototypeGtuner** [comment]
Yes i am agree with you, that would be cool and useful.

**Comment by prototypeGtuner** [comment]
I'm facing a problem related to the search function, i can't find anything about the last of us. Neither  the Gamepack nor the Modpack. It works with "tlou" or "thelastofus" keywords but how to find the+last+of+us if common words and words with less than 3 characters are omitted from the search?

**Comment by AJSinc** [comment]
Exactly why I think it'd be nice if Gtuner had " game hubs". At the very least every supported game would be sorted in alphanumeric order.

**Comment by J2Kbr** [comment]
> I'm facing a problem related to the search function, i can't find anything about the last of us. Neither the Gamepack nor the Modpack. It works with "tlou" or "thelastofus" keywords but how to find the+last+of+us if common words and words with less than 3 characters are omitted from the search?

The name of this game is an extreme case: `the`, `last`, `of` and `us` are all considered common words and ignored by the SQL server for performance reasons.

**Comment by prototypeGtuner** [comment]
Yes this game is an extreme case!

**Comment by Scachi** [comment]
What about using a search like "the last of us", or "the last" to use the complete string to search for all the words in this specific order, exact match, does sql support that ?
With additional tip in "no results found" info to search for multiple words as a single string using quotes.

**Comment by J2Kbr** [comment]
Gtuner IV 1.08 adds support for regular search against the title of published works, with query format: `[the last of us]`.
