### ISSUE TITLE
session state issue

### ISSUE THREAD

**Issue by prototypeGtuner** [J2Kbr/GtunerIV#245]
I have an issue with a project file where each time i open the file all the scripts are sorted by name. For example my TLOU project file works fine, there is 13 GPC opened and everything is saved correctly but with my SFV project file there is 27 GPC opened and neither by the project file or by closing Gtuner IV, all the scripts are sorted by name on next launch.

About that, would it be possible to have a Recent Project Files like the Recent Files? or to have the project files in the Recent Files?

**Comment by J2Kbr** [comment]
As for your first request, unfortunately the QT framework does not provides means to keep the code editor order after manually rearranged. It always returns the sub-windows list in the creation order. What you can do is open each file following the desired sequence and then save as project file.

Related with your second request, it was added to Gtuner 1.00RC68.
