### ISSUE TITLE
Feature Request - Input Translator - Copy/Paste for more/all settings

### ISSUE THREAD

**Issue by Scachi** [J2Kbr/GtunerIV#246]
At the moment we can only copy/paste from the MouseXY converter. Is the deadzone config included ?

It would be useful to have that option for keyboard keys and mouse buttons too.
Or a general copy/paste for the Input Translator where one can select what to apply from or copy to clipboard.

Like I have an Input Translator for game X and want it to use for game Y but use your MouseXY and Deadzone settings from the Online Resource.

The options right now are to use my X and copy/paste the mouseXY settings from your file or alter your git by hand to match my keyboard mapping again.
Being able to copy the keyboard key settings from one file to another would help.

**Comment by J2Kbr** [comment]
Copy-paste capability added to all input translator configurations (remapper, keyboard/mouse mappings, mouse xy)  on Gtuner IV 1.00RC-70.  Deadzone is included for Mouse XY.
