### ISSUE TITLE
Feature Request - Forum link to specific entry to open GTuner IV Online Resource

### ISSUE THREAD

**Issue by Scachi** [J2Kbr/GtunerIV#247]
Having the "Scripts Documentation (Titan Two)" is really nice and the possibility to link from within GTuner IV to that documentation post is fine too.

I miss having this option the other way around: posting the documentation and link to the Online Resource directly, so a user can click on this link it will open GTuner IV's Online Resource Tab and show the Script/Gamepack/Header (only or at first thing listed) ready to click/drag and drop or download/install.

I know there is the greslib link https://www.consoletuner.com/greslib/ but it is basic information about the script without a direct link to open it within GTuner IV.

This would be make the whole process a bit end-user friendly I think.

**Comment by J2Kbr** [comment]
I've being researching and testing potential solutions for this request for over 4h now. Unfortunately, Qt does not provides any multi-platform API capable to implement this feature. There is a class named QDesktopServices, which I thought could do the trick, but it works only within the application and does no responds to external stimulus.

I will be closing this issue, as no multi-platform solution exists for this features. Thanks.
