### ISSUE TITLE
Return from IF-ELSE statement

### ISSUE THREAD

**Issue by PoshLemur** [J2Kbr/GtunerIV#248]
This should work.

```
bool is_x_greater_than_y(int x, int y) {
    if (x > y) {
        // some extra steps here.
        calculate_pi();
        return TRUE;
    }
    else {
        return FALSE;
    }
}
```

However it will currently error out:
GPC error: <script>(<line>): Function must return a value '<function>'.

**Comment by Scachi** [comment]
Does this work with (real) c ?
Haven't one to use it like this ?
```
bool is_x_greater_than_y() {
    if (x > y) {
        return TRUE;
    }
    return FALSE;
}
```

**Comment by PoshLemur** [comment]
Yes this works with C compilers like mingw. Can't speak for others though.
Heres a functional C example.

```
#include <stdio.h>
#include <stdbool.h>

bool is_x_greater_than_y(int x, int y) {
    if (x > y) {
        printf("YUP!\n");
        return true;
    }
    else {
        printf("NOPE!\n");
        return false;
    }
}

int main() {
    is_x_greater_than_y(50, 25);
    return 0;
}
```

**Comment by PoshLemur** [comment]
@Scachi yes you are absolutely correct that is a shorter and more efficient way for handling it. I feel that the GPC compiler should still be able to handle these types of semantics without error though.

**Comment by J2Kbr** [comment]
The GPC compiler does not makes code execution analysis to resolve cases like this. i.e. check the existence of `return` statement inside ``if`` and inside the ``else`` to determine with certainty the _function_ has a returning value in all cases.
