### ISSUE TITLE
GTuner crashing on Block-Select a single line from right to left with cursor

### ISSUE THREAD

**Issue by Scachi** [J2Kbr/GtunerIV#249]
I often use the block-selection via keys leftShift+leftAlt+cursor and recognized some crashing of gtuner because of this but couldn't reproduce it until now.

Doing a block selection with the keys leftShift+leftAlt+cursorLeft from right to left on a single line crashes for me after a couple of selected characters.

GTuner stops responding an after 3-5 seconds the window silently closes without any windows "window/program unresposive" message.

Windows 10 64bit, all required win-updates installed

**Comment by J2Kbr** [comment]
Fixed on Gtuner IV 1.00RC-70
