### ISSUE TITLE
"New File" Button - Dialogs Directory value

### ISSUE THREAD

**Issue by Scachi** [J2Kbr/GtunerIV#25]
Currently the "New File" buttons dialog box set the directory to the last used one.
I almost always end up with the new file created in the wrong directory (maybe I am the only one) as I always think that selecting a directory or file in the "File Explorer" pane would set the pre-selected value in the New file dialog box.

Its a bunch of more clicks to be able to set the directory only via the browser button right of the directory field like it is now.

This is so much easier:
Action1 Click - Select directory in "File Explorer" pane
Action2 Click (or ctrl+n) - New gpc file dialog
Action3 Keyboard input to enter file name
Action4 Keyboard "Enter" key = DONE

Please preset the Directory value for new files to the directory selected in the file explorer or to the parent directory of the selected file.

**Comment by J2Kbr** [comment]
Implemented on Gtuner IV 0.95B. The global property "last directory" is automatically updated according the selected directory in the File Explorer., resulting in the behavior above described.
