### ISSUE TITLE
Gtuner crash when using Russian symbols in path

### ISSUE THREAD

**Issue by Scachi** [J2Kbr/GtunerIV#250]
Gtuner crash when using Russian symbols in path ( added to github for user LuckyGamerTV )

Forum post : https://www.consoletuner.com/forum/viewtopic.php?f=25&t=9589

Video: https://youtu.be/dUwpvZpV9ss

**Comment by J2Kbr** [comment]
Fixed on Gtuner IV 1.00RC-70
