### ISSUE TITLE
Input Translator "collapse" visual like deletes instead - very confusing

### ISSUE THREAD

**Issue by Scachi** [J2Kbr/GtunerIV#251]
Maybe it is only me but I get very confused by the Input Translators design/function of the icon that looks like I might be able to collapse one mapping type but I get a prompt if I want to delete it.
I can't get used to, it is against all other usage of a presentation like that somewhere else in any other program. The Interactive Configuration uses the same visual presentation to un-/collaspe something and not to delete it.

Clicking on the "Keyboard Mapping" word I would expect it to fold/unfold, not to delete it.
It will fold/unfold when it is empty only atm.
Can we that to fold/collapse and on the right most side of that bar a trash icon do delete it instead ?

![grafik](https://user-images.githubusercontent.com/22262242/43353889-00c4545a-9242-11e8-87e0-026c8c878f9a.png)

**Comment by J2Kbr** [comment]
This interface is basically a 1:1 representation of the input translator file (`.git`). Due the size constrains for git files in the internal device's memory (slots 1 t 3, only 170 bytes available for input translator), the git file can contain or not a configuration section. For example, if the meta information section is closed means it will not included in the git file at all, not even a single byte. The same is valid for all sections. When closing a section that contains any data, Gtuner will open a confirmation dialog warning the user that data will be lost (removed from git file).

I understand this behavior is different from what we have on the Interactive Configuration for scripts, where the intention is only to hide some section to make the interface cleaner.

Let's keep this as it is right now, as changing the design concept for this interface would also require save the section state (opened or closed) and adding extra controls to remove a section from the git file. Hope this decision is okay and understandable. Thanks.
