### ISSUE TITLE
Feature Request - Input Translator - Reorder the mappings of one type by drag & drop

### ISSUE THREAD

**Issue by Scachi** [J2Kbr/GtunerIV#252]
Right now it is not possible to get a quick overview of (example) all keyboard mappings done in the IT.
If I start to do a mapping for a game and recognize that I forgot a specific mapping the order gets very chaotic.
It would be a great help to be able to reorder the listing manually by drag and drop an specific entry to a new position.
The only option right now is live with it or start from scratch.

![grafik](https://user-images.githubusercontent.com/22262242/43354051-32a4d38e-9245-11e8-9376-cd50270d705e.png)

**Comment by J2Kbr** [comment]
Feature implemented via drag-and-drop, Gtuner IV 1.00RC-70.

**Comment by Scachi** [comment]
Dragging one item onto the other does exchange their positions at the moment.
When I add a missing or new remapping and want to place it in its position I'd like to, it would be more helpful to place the dragged item below/above the item is dropped onto and not exchange their positions.
If it is placed above or below the target I only need to drag&drop two items at maximum to place it between to existing items.
Right now I have to touch each one in the list if I want to keep the order and just want to put it in between to items.

Can you change the exchange to place below or above dropped onto item?
Or is there a key to hold down to place the dragged item between/above/below target and not mirror/exchange their positions already ?

**Comment by J2Kbr** [comment]
Reopening this issue to implement the "insert between" suggestion.

**Comment by Scachi** [comment]
I don't know if I explained that right. 
I think the exchange like handling that is currently active isn't needed at all.
If you are able to replace this method to one of 
a) "inserting it above" 
or 
b) "inserting it below" 
the dropped item would be just perfect. No need to do both of them, just the one that is easier to implement.
With this method, I only need to do a drag and drop once or twice at maximum to get it into the place I want it to without messing up the existing order.

**Comment by J2Kbr** [comment]
First, I 100% agree that "inserting it above" or "inserting it below" are the best and more intuitive solution for reordering the maps. However, after revisiting the code that handles this, I remembered why used only a simple swap operation.

Let me explain: each mapping line is implemented as object (having its own C++ class), at higher level there is a linked list with pointers for each object used mainly to save the mappings to the GIT file. This linked list is dissociated from the UI layout. The UI layout is controlled by the Qt framework.

My point is: swap values between two objects via drag-and-drop -as currently implemented- is easy. For "inserting it above" or "inserting it below" I would have to propagate this operation to higher levels to reorder the linked list, then delete all existing mapping lines from UI and finally rebuild the UI following the new mapping order. This definitive can be implemented, but would be a lot of work.

I am wondering how often an user needs rearrange the mapping order, my feeling is so not much and the currently solution is good enough, what do you think?

**Comment by Scachi** [comment]
I understand that this is a lot of work code wise in this case.
Having the swap option as it is right now is better than not being able to reorder them at all.
...

The current input translator readability is a nightmare to anyone not used to the button_numbers - like every new user ! 
Try to forget your knowledge of it for a few minutes... and start with a fresh brain T2 wise:

You are searching the forum/documentation for how to use keyboard & mouse..you find out that you have to use the input translator and that there are already some available for download.
So you download and open it wondering what key to press and ..you have no idea.
You have to look up each single button_ number..but how ? **You need to know** to press F1 or open the list by menu, having to write them down by hand.

I think there is a point why Sony or MS decided to name the button like RT or R2 instead of 1..21 ;-)

Having the other reordering option is something that would be useful and way more user-friendly.
If it is too time consuming and you have to focus on something else I am fine with it.
It is your choice of what and when to do after all ;-)
Maybe it would be nice to have a "long term improvement/feature list" (if you don't have one already for yourself) and put that and similar stuff on this list.
I think the overall usability of GTuner IV & Titan Two can be improved a lot, documentation and/or program wise. But I understand that that stuff is very time consuming.

.....
An idea that I just got while writing the above:
The ability to print out the IC is great..
Could something like that be added to the Input Translator ?
I am thinking about something like that, in the order of the controller usual layout maybe/GPC Designator F1 list ?
This way it would always be the same order, multiple keys for a single button should be listed one after the other.
Mappings done:
Keys A,S,W,D to BUTTON_1..whatever
Mouse Button .... whatever.

Clicking on an Icon/Button/Combobox will open a list for the selected console 
![grafik](https://user-images.githubusercontent.com/22262242/48933282-03f18b00-ef00-11e8-97e9-bef8fa3907d1.png)
to get the button names in a nice list, printable, ending up with something like that:
![grafik](https://user-images.githubusercontent.com/22262242/48933164-96ddf580-eeff-11e8-98b1-5ba574e6b202.png)

This can be optimized later on with a graphical representation of the controllers and mapped inputs or something like that.

**Comment by J2Kbr** [comment]
The implementation from #253 should also solve this latest request. Thanks.
