### ISSUE TITLE
Feature Request - Input Translator - Show button names according to console selected/detected

### ISSUE THREAD

**Issue by Scachi** [J2Kbr/GtunerIV#253]
If I download an Input Translator from the Online Resource it is very difficult to understand the mapping done if one don't know the BUTTON_ names by heart.
One has to press F1 to see the translation. While that windows is open one can't scroll trough the keybinds done so one has to close, scroll, open... 

A scripter/coder might get used to the BUTTON_ names and known them by heart ( I can't ) and a new user has just no idea about what "real" button it is on the controller.

One option to solve this problem would be to display the names translated automatically according to "the first time configuration wizard run" settings made or during the "console specific guidance" like proposed: https://github.com/J2Kbr/GtunerIV/issues/242
That would also help to solve other issues:
https://github.com/J2Kbr/GtunerIV/issues/228

Or display the translated button names right of the BUTTON_ name boxes then:
![grafik](https://user-images.githubusercontent.com/22262242/43354260-17107912-9249-11e8-883d-3196ec4e3929.png)

If I want to have an overview of the mappings printed out I have to write that down myself.
With the button translation shown it would be nice to be able to print that out too.

**Comment by briankincaid** [comment]
What if we hover mouse over BUTTON_11 and it gives a tool tip of the platform mapping

Best regards,
Brian (Daniel) Kincaid

On Jul 28, 2018, at 2:34 AM, Scachi <notifications@github.com<mailto:notifications@github.com>> wrote:


If I download an Input Translator from the Online Resource it is very difficult to understand the mapping done if one don't know the BUTTON_ names by heart.
One has to press F1 to see the translation. While that windows is open one can't scroll trough the keybinds done so one has to close, scroll, open...

A scripter/coder might get used to the BUTTON_ names and known them by heart ( I can't ) and a new user has just no idea about what "real" button it is on the controller.

One option to solve this problem would be to display the names translated automatically according to "the first time configuration wizard run" settings made or during the "console specific guidance" like proposed: #242<https://github.com/J2Kbr/GtunerIV/issues/242>
That would also help to solve other issues:
#228<https://github.com/J2Kbr/GtunerIV/issues/228>

Or display the translated button names right of the BUTTON_ name boxes then:
[grafik]<https://user-images.githubusercontent.com/22262242/43354260-17107912-9249-11e8-883d-3196ec4e3929.png>

If I want to have an overview of the mappings printed out I have to write that down myself.
With the button translation shown it would be nice to be able to print that out too.

**Comment by Scachi** [comment]
No, this won't help at all to understand the mapping at a glance. 
One would have to hover over every item. With the 8th mapping I hover the mouse I would have already forgotten the first one. This isn't user friendly.

I might just me being dumb if nobody else has a hard time reading and remembering the mappings from the Input Translator for a game ;-)

**Comment by AJSinc** [comment]
I also agree this should be an option.

**Comment by PoshLemur** [comment]
I agree with this idea and would like to see something to this degree implemented in all areas of the program where the IO identifiers are used.

**Comment by J2Kbr** [comment]
Feature implemented on Gtuner IV 1.08 (to be released soon). The console based labels are applied on all controls the IO identifiers are used in the Input Translator editor. Works similarly as the selection of the IO designators can be selected on Device Monitor.
