### ISSUE TITLE
KMG Capture - Joystick Trigger Issue.

### ISSUE THREAD

**Issue by sillyasskid** [J2Kbr/GtunerIV#255]
When using KMG Capture, with a Xbox 360 or an Xbox One Controller.

Its not possible to hold down both triggers simultaneously. Holding either trigger individually works as expected.

Also, pressing the trigger all the way, does not achieve 100% activation in the device monitor. It seems to to stop at ~99.61. 

https://www.consoletuner.com/forum/viewtopic.php?f=25&t=9644

**Comment by J2Kbr** [comment]
Gtuner IV 1.00RC-74 access XInput API to proper read the triggers state of Xbox controllers.
