### ISSUE TITLE
feature request - Device Monitor Channels

### ISSUE THREAD

**Issue by prototypeGtuner** [J2Kbr/GtunerIV#256]
I will have a wish about the plotted channels. For example if there is 4 entries plotted and i want to trace only one i have to disconnect the others entries from the channels, and drag back right after that and so on.

Would it be possible to click on the channel to enable/disable the tracing?

**Comment by J2Kbr** [comment]
Feature added on Gtuner IV 1.00RC-74 via context menu (right-click) on the plot channels. Available for the waveform graph and XY plotting.
