### ISSUE TITLE
Feature Request - GPC Script IDE - Find/Replace usage improvement

### ISSUE THREAD

**Issue by Scachi** [J2Kbr/GtunerIV#257]
When the cursor is in the main GPC Script IDE panel and I press CRTL+F the cursor/input focus jumps to the find/replace panel, that is fine.
Leaving this panel is not that easy, you have to use the mouse or press shift+tab.

I would like to have the Escape key to leave the find/replace panel to get back to the main script ide panel.
It is much easier to hit and it is the key I always press intuitive.
As far as I notice the escape key doesn't do anything else at that moment in the find/replace panel.

Perhaps I am used to this by using Notepad++ often. ctrl+f open a search window, escape closes it and I am back ready to continue typing.

**Comment by J2Kbr** [comment]
Feature added to Gtuner IV 1.00RC-70. thanks.
