### ISSUE TITLE
Feature Request - GPC Script IDE - Find/Replace in selection only

### ISSUE THREAD

**Issue by Scachi** [J2Kbr/GtunerIV#258]
I can't find how to replace in selection only.
Isn't that possible at the moment ?

If there isn't space left to make a "in selection only" checkbox maybe just check if there is a selection in the IDE and then just use that on "Replace All" silently

or get a popup when a selection if found with the options to cancel/selection only/all

or dynamically rename the "Replace All" to "Replace Sel" if a selection is active 

or make it a right-click context on the "Replace All"

or remove the Find/Replace Panel completely and make if a popup when hitting ctrl+f 
then there will be enough space to get a replace in selection like it is in a lot of other programs.

or tell me how "replace in selection" works at the moment, maybe I am just to blind to find it ;-)

Thank you for your patience with all my posts here, 

I really like your implementation of the Lightbar in the Device Monitor. I use it quite a lot and it looks great. Thank you !

**Comment by J2Kbr** [comment]
Replace All in selection added to Gtuner IV 1.00RC-80, as suggested: "_just check if there is a selection in the IDE and then just use that on "Replace All" silently_".
