### ISSUE TITLE
Interactive Configuration - config control problem

### ISSUE THREAD

**Issue by Scachi** [J2Kbr/GtunerIV#259]
I have created a new script for The Division, in the Online Resource "the division rev2" utilizing multiple config controls to be used as presets for 3 weapon slots per profile, 3 profiles with different byte-offsets.

The behavior of the handling of this control is not very useful at the moment.
Perhaps I am doing something wrong or do not understand how to use it properly .

The problem is that a click on a config item button does reset the byteoffset that aren't specified at all in its config string to the values the had when I opened the Interactive Configuration.
Hitting "Save and Run" doesn't change anything, 
The IC needs to be closed an reopened to let it not change undefined byteoffsets back to the value it was at the moment the Interactive Configuration was opened.

To get it working like I thought it would does require:
Go to the "Profile #1 Loadout" ->#1 Primary Weapon : Presets"
Click on a preset I want to use.
Click "Ok" or "Save and Run" AND NOW CLOSE the Interactive Configuration.
Now reopen it and go to the  "Profile #1 Loadout" ->#1 Secondary Weapon : Presets" and click on the preset I want to use. Click "Ok" or "Save and Run" again and AGAIN CLOSE the Interactive Configuration, reopen it again, go to the next preset...

The Interactive Configuration should only change the values for the controls that are defined by the byteoffsets and not change/reset anything else at all.
This way I can use multiple config controls in one Interactive Configuration to control different settings without having to save+close+reopen.
I could just click on all the presets of the controls I want to change and hit "Save and Run" or "OK" once when I have clicked whatever presets (config controls) I want to apply and be done.

**Comment by J2Kbr** [comment]
Issue fixed on Gtuner IV 1.00RC-70, thank you for reporting.
