### ISSUE TITLE
Macro Explorer - Name sorting - on every click horizontal scroll bar gets wider

### ISSUE THREAD

**Issue by Scachi** [J2Kbr/GtunerIV#260]
There seems to be some kind of bug in the Macro explorer when clicking on the "Name" with a single macro file present (haven't tested it with more items).

With each click on the "Name" sorting the horizontal scroll bar gets bigger/wider:

not clicked:
![1](https://user-images.githubusercontent.com/22262242/43990377-91a4b98c-9d5b-11e8-8192-8844782b3661.png)

clicked once:
![2](https://user-images.githubusercontent.com/22262242/43990379-994c2b48-9d5b-11e8-9729-4229ccebd7f4.png)

clicked twice:
![3](https://user-images.githubusercontent.com/22262242/43990383-9faaa1cc-9d5b-11e8-9277-caedcc29ce72.png)

**Comment by J2Kbr** [comment]
Fixed on Gtuner 1.00RC-70. Thank you for reporting.
