### ISSUE TITLE
Feature Request (Sugestion) - GTurner IV

### ISSUE THREAD

**Issue by lgbm** [J2Kbr/GtunerIV#261]
1) Stop option for GPC Script IDE
2) Run Macros in runtime into Macro Editor
3) Drag to adjust Macro lines into Macro Editor (like this https://gyazo.com/696c91b7ab4d548009a3ed315a147f9b)
4) INPUT/OUTPUT details into Device Monitor should be accessible from outside world

Kind Regards!

**Comment by J2Kbr** [comment]
Thank you for your suggestions.

1. You can stop the loaded script in the Memory Slot panel, by clicking the middle buttons at the top of this panel "Unload Memory Slot".
2. With the macro opened in the Editor, click the green play icon (Test and Debug) at toolbar to quick test the macro.
3. Suggestion annotated.
4. Not sure if I understood this request. Perhaps you are referring to the Open API that gives access to the device for any software. If yes, this is under development and will be out soon.
