### ISSUE TITLE
GTuner -> Preferences -> Test and Debug -> Autom. open Device Monitor -> Focus issue

### ISSUE THREAD

**Issue by Scachi** [J2Kbr/GtunerIV#262]
When creating scripts and testing them I hit F5 and get to the Device Monitor which is a nice feature.
Old me, I often forget to hit F4 to enter the capture mode and hit some keys I have mapped to a button to see that nothing happens.

The focus is still in the GPC Script IDE and I am typing stuff blindly before I recognize that I did forget to hit F4 once again. 
Now I have to remove the blindly typed characters from the script again before being able to compile it again.

Can we get the focus set to some button/field/whatever in the Device Monitor so I can't type anything into the script anymore by accident when the Device Monitor is shown ? Or you might have a more clever way to stop this from happening.

Maybe we can get the checkbox remembered in the "Automatic Enter Capture Mode" too ?
Right now closing and reopening GTuner IV, I have to set that checkbox again each time.

**Comment by J2Kbr** [comment]
Starting with Gtuner IV 1.00RC-70, the "Test and Debug" command also forces focus on Device Monitor if "Automatically Open Device Monitor" options is set.
