### ISSUE TITLE
Feature Request : MULTILINEHTML : Interactive Configuration, MULTILINE and HTML linbreak handling

### ISSUE THREAD

**Issue by Scachi** [J2Kbr/GtunerIV#263]
It is very hard to get something like a `<table>` integrated into the Interactive Configuration while keeping the code of it readable.

At the moment something like that, will result in two lines per tr because of the automatic linebreaks added be gtuner:
```<table border="0"><tr><td>Mod</td><td>Button Combo XBOX</td><td>Button Combo PS4</td></tr><tr>
<td>ON/OFF Rapid Fire:</td><td>LT + D-Pad LEFT</td><td>PS4_L2 + PS4_LEFT</td></tr>
<tr><td>ON/OFF Shot per burst:&nbsp;&nbsp;</td><td>LT + D-Pad UP</td><td>PS4_L2 + PS4_UP</td></tr>
<tr><td>ON/OFF Anti-Recoil:</td><td>LT + D-Pad DOWN</td><td>PS4_L2 + PS4_DOWN</td></tr> 
</table>
```
To have a tr in a single line (avoid automatic linebreak) I have to write everything into a single line that makes the IC code very hard to modify and read.

Can we get something like a "MULTILINEHTML" tag where we have to define linebreaks ourself ?
Or in addition to shortdesc, add a "htmldesc" where we can use the MULTILINE tag again.
This would make it possible to not break old multiline text and use it for simple stuff.
For move complex html stuff we can then use MULTILINEHML without having to fight automatic linebreaks.

**Comment by J2Kbr** [comment]
I believe to have found a solution for this without needing `MULTILINEHTML` or `htmldesc` tag. Same solution we already have for the tags `pre` and `code`, now extend to `table`, `tr`, and `td`. To be available on Gtuner IV 1.00RC-74.
