### ISSUE TITLE
Support for one click configuration sub-names

### ISSUE THREAD

**Issue by PablosScripts** [J2Kbr/GtunerIV#265]
See attached. Without such a feature it's impossible to tell which script is for which game. I find myself constantly double checking the settings to remind myself, so there must be a better way. I have come up with the following idea and mockup which leverages the new one click configuration feature that has recently been implemented. 

![subname](https://user-images.githubusercontent.com/22415147/44968342-bf062a00-af8a-11e8-8eed-75ae94d1cb41.jpg)

**Comment by Scachi** [comment]
What about script with multiple config controls in them for different settings ?
Which of them does control the controls the sub-names then ?
My The Division rev2 script uses 9 different config controls to setup different weapon loadouts for 3 profiles in a single script (per Profile one button for each of primary,secondary and sidearm weapon).
Doing an extra config control that only sets the script sub-name may be possible but limits the user to the available options the scripter/coder supplied,

I would like to be able to set the sub-name manually, like requested here already:
https://github.com/J2Kbr/GtunerIV/issues/216

**Comment by PablosScripts** [comment]
Yes you're right, I wasn't aware people were using multiple sub-configs like this, I'll close this one down.
