### ISSUE TITLE
No Output Panel record when pasting IC settings

### ISSUE THREAD

**Issue by PablosScripts** [J2Kbr/GtunerIV#266]
When you copy an IC setting, you get the following message: 

![image](https://user-images.githubusercontent.com/22415147/45074633-8485c400-b127-11e8-9d99-3f7e4ac67b9a.png)

However when you paste, you don't get a message at all.

**Comment by J2Kbr** [comment]
Starting from Gtuner IV 1.00RC-74, success/error messages are reported in the Output Panel for paste operation.

**Comment by PablosScripts** [comment]
I'm not sure if this is working. Copying an IC setting will generate a message (which always worked) but pasting it still doesn't seem to generate a message either?

**Comment by J2Kbr** [comment]
On 1.00RC-74 this was implemented for Input Translators. I have now did the same for Interactive Configurations on 1.00RC-80.
