### ISSUE TITLE
Using a "one click configuration" while previewing an IC will re-enable the OK button

### ISSUE THREAD

**Issue by PablosScripts** [J2Kbr/GtunerIV#267]
1) Open a script.
2) Click on Compiler > Preview GCD
3) At this point, the OK button is greyed out. This is how it should be.
4) Click on a one click config (see screenshot below, in this example I clicked on "Advanced Warfare")
5) Notice at this point the OK button is no longer greyed out, and pressing it will throw an error

![image](https://user-images.githubusercontent.com/22415147/45074799-2d342380-b128-11e8-8e5d-a1c0ffbf7f91.png)

![image](https://user-images.githubusercontent.com/22415147/45074815-41782080-b128-11e8-989f-83a90503084d.png)

**Comment by Scachi** [comment]
This might be OSX related

Using windows 10 x64
The OK button isn't greyed out for me when I hit F9 to preview the IC, 
Clicking ok works for me as it should., or how would you change the configuration of a test and debug script run ?
```Memory Slots: Updating Test and Debug configuration```

It would be nice to be able to use the "Save and Run" button with "Test and Debug", too.
Right now I have to click OK and restart the script myself.

**Comment by PablosScripts** [comment]
No I'm on Windows 10 (fully updated), I wasn't using my Mac at the time I tested this. 

Whether this is correct or not, there are still two things I think need addressing: 

1) It should not throw an error
2) It should be consistent, the OK button should always be greyed out, or never greyed out

**Comment by Scachi** [comment]
Sorry, I was just guessing about the OS.

I totally agree.

**Comment by J2Kbr** [comment]
I tried reproduce the issue and everything worked as expected. The state of the OK button is enabled. When the Interactive Configuration window opens, the OK button starts disabled and as soon as Gtuner receives the data related with that configuration from the Titan Two, the OK button is enabled. This should happen very quickly, in less than one second.
