### ISSUE TITLE
Interactive Configuration pmem handling - how it is supposed to work ?

### ISSUE THREAD

**Issue by Scachi** [J2Kbr/GtunerIV#269]
I am wondering how the Interactive Configuration is supposed to work with bits or bytes not used by the cfgdesc but used directly in a script.

It is somehow a mixed setup of Interactive Configuration I wondering about how I should handle that correctly or how the IC is supposed to handle it

Example:
I have a script with an Interactive Configuration, that IC only uses the byteoffset 0 / bitsize 8.
But I have to store other values to the permanent memory that the user shouldn't be able to change or not see at all.

When I install that script without pressing ctrl I understand that it should/would set the complete slots pmem to zero values.

But my script needs to remember some states that the user shouldn't care about and doesn't need to adjust or see at all as this is purely used for some state tracking inside of the script.

Right now it looks like it sets not defined bytes back to zero when I hit the [OK] button in the IC after adjusting available IC settings via the IC like a user would do.

If it is supposed to do that I think we really need an option to hide IC settings from the user to avoid unnecessary overloading of the IC with settings that never needs to be adjusted manually.

**Comment by J2Kbr** [comment]
On Gtuner IV 1.00RC-74 the collapsible parameter can be set to 3 to completely hide the item or grouped items in the Interactive Configuration Interface. With this option you can define a set of configurations for internal use, without expose these configurations to the user.

**Comment by Scachi** [comment]
Great solution ! Thank you very much.

**Comment by PablosScripts** [comment]
This is indeed a brilliant idea. I saw it in the patch notes. Love it!
