### ISSUE TITLE
GPC Script IDE - extend autocomplete function

### ISSUE THREAD

**Issue by Scachi** [J2Kbr/GtunerIV#27]
It would be great when the GPC Script IDE would also keep track of users define, variable, function (with arguments) and combo declarations.
Parsing included header files for those information would be a big help too.

This would speed up coding as I don't have to remember the exact name of my declarations and just select the correct one from the list.

**Comment by J2Kbr** [comment]
This feature is already present. It requires at least insert the first letter of any variable, define, etc and press Ctrl+Space to open the list. Please note the first letter is case-sensitive for variable, define, etc.

**Comment by Scachi** [comment]
Does this really parse the #included files like in the initial question ?
It looks like there is no autocomplete for functions from an included .gph file ?
Creating a new script file and adding xkeys.gph to it doesn't show the xkey_ function when hitting ctrl+space after xkey

![grafik](https://user-images.githubusercontent.com/22262242/46354846-ddca1000-c65f-11e8-9700-b0ba3a7fc490.png)

The xkeys header file is available in the online resource. 
Is some formatting of this file causing the autocomplete not to work or isn't that working at all with included files ?
