### ISSUE TITLE
Renaming scripts from inside Gtuner

### ISSUE THREAD

**Issue by seededplyr** [J2Kbr/GtunerIV#271]
If the script is open in the editor while trying to rename it there is an error:
----------------------------------------------------------------------------
The name "whatever.gpc" can not be used.
Try using another name, with fewer characters or no punctuations marks.
----------------------------------------------------------------------------

**Comment by J2Kbr** [comment]
If the work is opened, Gtuner IV 1.00RC-74 will close it to allow the file rename.
