### ISSUE TITLE
GTuner gets unresponsive when installing this script - compiling does work fine

### ISSUE THREAD

**Issue by Scachi** [J2Kbr/GtunerIV#274]
User hammer reported a problem with a script of Buffy when installing it to a slot.
I think you are already aware of it.

Post: https://www.consoletuner.com/forum/viewtopic.php?f=25&t=10442#p73352

For this script it looks like the macro's are not correctly working , the include to common.gph and that file includes all calling files by itself seems to go in a endless loop on installing.
On compiling everything seems to be working fine.
It is a bit strange that it also parses include statements from withing comments.
Here is my post about all that what I did find out:
https://www.consoletuner.com/forum/viewtopic.php?f=25&t=10442#p73401

Script attached.
[Fortnite_BR_org.zip](https://github.com/J2Kbr/GtunerIV/files/2520256/Fortnite_BR_org.zip)
[Fortnite_BR_changed_works.zip](https://github.com/J2Kbr/GtunerIV/files/2520257/Fortnite_BR_changed_works.zip)

**Comment by J2Kbr** [comment]
You was correct in your assumption, the issue was infinite loop at the function that scans the source files for a valid Configuration Descriptor. Fixed on Gtuner IV 1.00RC-74. Thank you.
