### ISSUE TITLE
Online Resource , add "protected terms" only Consoletuner staff can use

### ISSUE THREAD

**Issue by Scachi** [J2Kbr/GtunerIV#275]
The Online Resource is getting a bit messed up with user made scripts that are named "[GamePack]"..making user stumble about why those scripts are so much different from the other "Gamepack"s and/or thinking this might be an official one, wondering why they are not located in the "Gamepack" Tab of the Online Resource, ...

Long time ago, (during beta I think) there was some discussion to use the word "Gamepack" for official script releases. 
For scripters who need some special words can use the word "Modpack" / "ModzPack"..something like that.

Adding a filter for some specific keywords only usable by consoletuner staff would make this easier to handle. Getting back a message like "protected keyword in script name found", maybe with " please use .. instead" if one creates some translation table would be helpful for the person trying to submit something.

**Comment by J2Kbr** [comment]
I believe the best way to handle this is remotely, at the ConsoleTuner server during the validation of the data submitted by the user via Gtuner IV: by simple replacing the world Gamepack to Modpack or rejecting the submission with warning. The advantage of doing this on the server is I can make changes on the filters without needing update Gtuner IV.

**Comment by Scachi** [comment]
Do you still have this on your todo list ? Would be nice to cleanup the Online Resource, the sooner the better.
