### ISSUE TITLE
We need the ability to link to other scripts

### ISSUE THREAD

**Issue by PablosScripts** [J2Kbr/GtunerIV#276]
I want to be able to recommend my COD script users to download J2kbr's input translator file to use with mine, like this: 

https://i.imgur.com/r6vQUTU.jpg

But there are two problems with this:

1) There is no way to link to it. All I can do is write a textual description that tells users what to search for, but it would be better if I could simply link to it. 

2) Even if a user searches for it, it's difficult to locate the correct script. There are already quite a few BO4 scripts to choose from, for new users it's confusing trying to tell the difference between an input translator and a GPC file. So as you can see in my screenshot / mockup, I have made it so clicking the link searches not based on a keyword string, but on a script ID or some other type of hash. 

I also thought about making it a button like the "DOC" button. But this won't work because sometimes you want to link to multiple files. For example, for my For Honor script I had the choice of like 3 different input translators, such as regular controllers, arcade sticks etc. 

Also another idea - provide the option to "bundle". This would have two effects: the GPC + IT would be installed as a single package. Secondly, it would hide the IT from the Online Resources section, so you don't end up flooding the OR page with input translators for every script that you write. 

I believe features such as this will become increasingly necessary with the impending release of the mobile app. Things are too complicated right now and need to be scaled back and / or packaged up to provide users with a simpler interface into the content.

**Comment by J2Kbr** [comment]
Feature added to Gtuner IV 1.04.

To create Online Resources search link, use the following structure:
`[search:<search_querie>]<text_to_be_clicked>[/search]`

Example:
`[search:Fortnite]Link to search for Fortnite[/search]`
