### ISSUE TITLE
O programa não pode ser iniciado porque está faltando XINPUT1_4.dll no seu computador. Tente reinstalá-lo para resolver esse problema.

### ISSUE THREAD

**Issue by KiddLankaster** [J2Kbr/GtunerIV#277]
Bom dia
Utilizo Windows 7, e pelo que li a Xinput1_4 não é compativel com esse sistema operacional, agora não consigo iniciar o GTuner. Onde encontro a versão antiga ?

Obrigado.

**Comment by J2Kbr** [comment]
Fixed with 1.00RC-75, please re-download from our website.
