### ISSUE TITLE
Type-searchable combo boxes?

### ISSUE THREAD

**Issue by PablosScripts** [J2Kbr/GtunerIV#279]
When I have an extremely long combo box (e.g. all the keys on a keyboard for binding)....it's a bit of a pain to scroll through the whole list. 

Is it possible to make it so we can type-search for the key that we want? E.g. if we want to bind to CTRL then typing "ct" would jump directly to it in the dropdown.

Thanks

**Comment by J2Kbr** [comment]
Is already possible to jump to an specific item on combo-boxes using the keyboard: right click on the combo-box to it have the keyboard focus and then type what you want.
