### ISSUE TITLE
Lots of white text in Dark Mode on macOS

### ISSUE THREAD

**Issue by cmsj** [J2Kbr/GtunerIV#280]
Hey

I'm about to buy a Titan Two and thought I'd download the software and have a quick browse of the online resources. I've noticed that in quite a few places, when macOS is running in Dark Mode (new feature in this year's 10.14 Mojave release) the text in GTuner is white on white.

**Comment by cmsj** [comment]
<img width="1731" alt="screenshot 2018-11-23 at 22 09 04" src="https://user-images.githubusercontent.com/353427/48961437-71d39c00-ef6c-11e8-9f1b-a665e8fb9766.png">

**Comment by cmsj** [comment]
(by the way, thanks very much for making a Mac app, it's really nice of you to support us!)

**Comment by J2Kbr** [comment]
You are welcome. Gtuner IV revision 81 released this morning fix this issue. The application will run in light mode even if the system is configured to dark mode. This is temporarily solution until we implement full support for the new Mac dark mode.
