### ISSUE TITLE
Windows Issue: Don't Lock Open Files

### ISSUE THREAD

**Issue by PoshLemur** [J2Kbr/GtunerIV#281]
The reload has been implemented which is fantastic (1000 thanks)! But I can't make any use of it in Windows because GtunerIV is keeping the files locked. Preventing any program that's not being run as admin (all of them) from editing the files while open in GtunerIV.

Please prevent GtunerIV from locking open files. This is inhibiting my ability to program scripts and back up scripts using 3rd party tools.

![1](https://user-images.githubusercontent.com/39054593/48964402-2d8bd000-ef5b-11e8-9e97-0202fd5b99c8.png)
![2](https://user-images.githubusercontent.com/39054593/48964404-2d8bd000-ef5b-11e8-83cf-3ba105ec6562.png)

**Comment by J2Kbr** [comment]
Gtuner IV does not apply file lock. The file is simply opened in read&write mode without any locking, and kept opened while the corresponding editor is also opened. This is needed for integration with GPC compiler. 

Unfortunately, on Windows you cannot open a file that has already been opened with write permission.

**Comment by PoshLemur** [comment]
Would it be possible to have GPC close the file usage and reopen it when needed?
Most text editors I know of work this way. Including Notepad++ and Sublime Text both.

Checkout opportunistic locks 
https://blogs.msdn.microsoft.com/oldnewthing/20130415-00/?p=4663/
https://docs.microsoft.com/en-us/windows/desktop/FileIO/opportunistic-locks
