### ISSUE TITLE
Device Monitor - Scale timeline with mousewheel , "zoom"/center on mouse position

### ISSUE THREAD

**Issue by Scachi** [J2Kbr/GtunerIV#282]
The timeline scaling via mouse wheel works fine but it would be a lot more helpful if it would zoom in/out into the position of the mouse cursor on the X position of the line  instead of scaling it to the start point.
That would save a lot of zoom, scroll, zoom, scroll,... actions just to see some detail in the current viewable area.

**Comment by J2Kbr** [comment]
Implemented on Gtuner IV 1.00RC-84
