### ISSUE TITLE
Problema com último update

### ISSUE THREAD

**Issue by KiddLankaster** [J2Kbr/GtunerIV#283]
Boa noite

Depois do último update, ao abrir é apresentada a mensagem:

**A versão deste arquivo não é compatível com a versão do Windows em execução. Consulte as informações de sistema do computador para verificar se você precisa de uma versão x86 (32 bits) ou x64 (64 bits) do programa e entre em contato com o editor do software.**

VErsão 1,0,2,82

Windows 7 - 32 Bits
Obrigado

**Comment by J2Kbr** [comment]
Desde recentes updates, Gtuner IV mudou a arquitetura para 64-bits, a versão antiga 32-bits pode ser baixada pelo link que segue:

https://www.consoletuner.com/titan-two-downloads/

Procure por: "_Legacy Gtuner IV for Windows 32-bit (Win10, Win8.1, Win7): Gtuner IV 1.00RC-75_"
