### ISSUE TITLE
GTuner IV Online Resource submission of .gph files - version numbers ?

### ISSUE THREAD

**Issue by Scachi** [J2Kbr/GtunerIV#285]
Submitting .gpc files the #pragma line gets parsed for the version number.

How can I define the version number in an .gph file to have effect on the submission of gph files ?
It hard to keep track of the versions when I have to set the version number manually on submission each time.

**Comment by J2Kbr** [comment]
On the GPC file, place the `#pragma METAINFO()` line AFTER the header #includes, this will ensure the _metainfo_ of the GPC will be the last to be parsed and, therefore, the one that will be used for the GPC file. While you can still use the _metainfo_ on the header files.

**Comment by Scachi** [comment]
I am trying to submit a header file only.
When I add this line to the header file:
`#pragma METAINFO("ColorLED", 1, 01, "Scachi")`
and use "Tools->Publish Wizard" , the version number isn't recognized:
![grafik](https://user-images.githubusercontent.com/22262242/50394685-5b815180-075f-11e9-8155-5c2640f4c854.png)

**Comment by J2Kbr** [comment]
Sorry, I misunderstood your first message.

Okay, `#pragma METAINFO()` defines a data section in the compiled GBC file, which are used to display the information of the script on Gtuner IV (Device Monitor and Memory Slot interface). The _metainfo_ can be defined in GPH files to be included in the GPC file, but are not intended to define version of the header file, but instead of the resulting GBC file.

For reusable header files is not recommend include _metainfo_, as they can overwrite the meta information of the GPC file if the used in the incorrect order, as explained above.

As for your example above, not only the version is parsed based on the _metainfo_ (in the case of the GPH file), but also the name and the author.

**Comment by Scachi** [comment]
What i am requesting is an Option to set the Version for gph files somehow so it gets parsed by the wizzard  during gph file submission only. Right now I have to note the version by hand twice. Once in my gph file with within some  kind of comment and once when uploading it. That is prone to errors and totaly different than it is handled for gpc files. So I am looking for some kind of header file only pragma syntax like way that gets ignored when submitting a gpc script that uses a header file.

**Comment by Scachi** [comment]
Hello again, it would be nice to have that option added in the near future.
Having all the tags available specific for header files would be nice.
It could allow us to use something like 
**#gph_pragma**
 and 
**<gph_cfgdesc>** 
for all the content tags when posting something to the Online Resource as header file and only use those tags in this case.
like <gph_doc> ...

This would allow other user to use the header file in their project (non .gph) without messing up their own cfgdesc tag then as posting as scripts/bytecode should only parse the tags without the "**<gph_**" /  "**</gph_**"

**Comment by J2Kbr** [comment]
Gtuner IV 1.04 will also parse `title`, `version` and `author` metainfo tags. Example:
```
<title>Title of the work</title>
<version>2.30</version>
<author>Jefferson Koppe</author>
```
These tags are more useful for `gph` files, but can also be used with `gpc` files if the script does not have set `#pragma METAINFO`. 

`#pragma METAINFO` have priority over the above tags.

Configuring metatags on a `gph` file have no effect if the `gpc` that is including the header file have these tags set. This is also valid for `shortdesc`, `keywords`, `docurl` and `cfgdesc`.

**Comment by Scachi** [comment]
Great solution ! Thanks.
