### ISSUE TITLE
GT4 RC v. 1.0.2.86 force usb to full speed bug

### ISSUE THREAD

**Issue by Hyphen-x** [J2Kbr/GtunerIV#287]
@J2Kbr **There is one more issue with GT4 RC v. 1.0.2.86** and same as prior version that I kept forgetting to tell you. I don't know if it is intended but also w**hen I check and uncheck the box for forcing the usb to full speed this also causes a disconnect and reconnect** on both checking and unchecking the box. 
GT4 also blinks on and off and the computer uses the sound for connect and reconnect USB while something is active. And the disconnect/reconnect happens on the PS4 also.

The **drag and drop is working fine and configures fine.** I have not tested it in a game configuring on the fly but **thank you that was great** 

**Merry Christmas/Happy Holidays!**

**Comment by J2Kbr** [comment]
Merry Christmas Hyphen-x.

What you are describing is the expected behavior. The Titan Two needs to reset in order to change the PROG speed, that is why you see the device reconnection on Gtuner IV.
