### ISSUE TITLE
KMG Capture sometimes "skips" analog inputs

### ISSUE THREAD

**Issue by fossephate** [J2Kbr/GtunerIV#288]
I run a pretty complicated setup for a stream I run which involves the Gtuner IV's KMG Capture mode

for my setup I need to be able to control things from a python script, and so I use vJoy along with pyvJoy to simulate a controller to Gtuner IV, and sometimes the inputs get "stuck" and Gtuner doesn't get the latest 1 or 2 inputs, and without new inputs it'll continue to stay "stuck"

I suspect it's a problem with how Gtuner polls for inputs on gamepads, or it could be an issue specific to vJoy, right now my only solution is to send slightly randomized analog inputs and hope that if Gtuner doesn't pick up the change the first time it does the 2nd (which causes other problems for my setup)

as far as I can tell it only affects analog inputs, but it could affect buttons too (and I just haven't noticed it)

this is a pretty niche use case for Gtuner so I'd really appreciate it if you could look into this

**Comment by J2Kbr** [comment]
Gtuner IV relies on the Window's Raw Input API to receive the status of keyboard, mouse and joystick. This API is not based on polling, but on events. Windows will send events to Gtuner IV when the status of the input device changes.

I have tested with regular controllers (Xbox, PS4) and couldn't reproduce the reported issue.

My suggestion is program your python script to send regular reports even if there is no changes on the inputs, in this case just repeat the last report sent. This should solve the problem.

Please keep me updated on the results.

**Comment by fossephate** [comment]
The issue wasn't with Gtuner, it was with how I was updating the controller's state.
