### ISSUE TITLE
Feature Request - add switch joy con ir sensor as Point_y, Point_x input

### ISSUE THREAD

**Issue by donutunlimited** [J2Kbr/GtunerIV#289]
If it is not to much trouble could you assign the switch joy con IR sensor as point_1_X and point_1_Y input. The Joycon IR sensor is not just a simple input tracking device, it can also be use to pick up hand gestures and you can read more about in this article from kotaku.

 [https://kotaku.com/the-switch-joy-con-s-infrared-sensor-is-cooler-than-we-1822669059](url)

Having a device with same main feature as a wiimote would make using the joy con more popular in the console tuner community, since similar scripts with IR for wiimote could be used for the joy con. A gesture input system would be cool, imagine putting up the peace sign to execute a combo in front of the joy con. Another example would be using the joy con to track eye movements, another company has popularize eye tracking very recently. 

[https://tobiigaming.com/software/ghost/](url)

The Joy con IR input has many possibilities.  You can use lots of hand gestures with precision to get the job done, instead of wasting it on a slot or a button on your controller. Gestures would make gaming more accessible to disable gamers or multitasking steamers. On top of that the IR sensor of the joy con obliviously have a higher resolution than the wiimote ir sensor. Titan two has already brought a lot to the table, but it would be a nice have more options for motion controls in the future.
 
Thank you for your consideration.

**Comment by J2Kbr** [comment]
Request move here: https://github.com/J2Kbr/TitanTwo/issues/200
