### ISSUE TITLE
Issue: Single Instance Gtuner or Open New Files in Existing Process

### ISSUE THREAD

**Issue by PoshLemur** [J2Kbr/GtunerIV#290]
Please make GTuner a single instance application **or** make it so files opened from Explorer are opened in the current instance of Gtuner. Currently if I associate gpc/gph files with Gtuner they will each open in a new instance of Gtuner instead of opening as tabs.

In regards to single instancing Gtuner - which given the nature of Gtuner seems like the best idea to me.
There's already a open source library built for it in Qt5. See: https://github.com/itay-grudev/SingleApplication

**Comment by sillyasskid** [comment]
Support for more than one instance of GtunerIV is needed to control multiple Titan Two devices simultaneously though.

**Comment by PoshLemur** [comment]
> Support for more than one instance of GtunerIV is needed to control multiple Titan Two devices simultaneously though.

Ah good point, I didn't think of this. (Didn't think of someone needing to do that.)
Maybe a toggle-able option? Or just better file handling so that opening a GPC script does not open each in a new instance.

**Comment by seededplyr** [comment]
opening a gpc file should open in a instance of gtuner that is already running if there is one, this shouldnt affect people who need to run multiple instances of gtuner to control their multiple titan 2s

**Comment by PoshLemur** [comment]
Closing because one of the points was invalidated and the other is covered in issue 293.
