### ISSUE TITLE
Add File Path as Tab Tooltip and to the Statusbar 

### ISSUE THREAD

**Issue by PoshLemur** [J2Kbr/GtunerIV#291]
Please add a the full file path of the currently active tab to the tab tooltip when you hover the mouse over it and to the status bar. This would make it a lot easier to know which version of a script I am working on when I have multiple scripts with the same name open.

![tooltip](https://user-images.githubusercontent.com/39054593/51801963-8432b600-21f9-11e9-955c-f0b81c007f3f.jpg)

EDIT:
![tooltip2](https://user-images.githubusercontent.com/39054593/51802091-15565c80-21fb-11e9-9e48-25d382e926f5.jpg)

I did just discover that if I hover my mouse over the top left inside the line number row, it does pop up! Which is great, albeit not the most intuitive. I'd still argue that these two suggestions would make it easier to understand what file the user is on and more intuitive.

EDIT 2:
It would also be really nice if you have 2 files open with the same file name, then the Tab title would append the folder name to the tab.

For example if I have 2 scripts for Battlefield called bf.gpc both open in Gtuner and both belonging to a different Battlefield game and separated into different project folders. The tabs could be named like so

[ bf.gpc - BF5 ] [ bf.gpc - BF4 ]
Where BF5 and BF4 are the folder names of their respective files.

**Comment by J2Kbr** [comment]
Feature implemented on Gtuner IV 1.04. When the mouse cursor is over the code editor tab, a tooltip with file info + script metainfo (if present) is shown.
