### ISSUE TITLE
Interactive Configuration - Allow multiple controls to by displayed in a table

### ISSUE THREAD

**Issue by Scachi** [J2Kbr/GtunerIV#294]
It would be nice to be able to put  controls in rows&columns like in a table:
```
"Name"        | "Name"        | "Name"        | 
"Shortdesc"  | "Shortdesc"  | "Shortdesc"  | 
[Spinbox]      |  [Spinbox]    | [Combobox] |
```
Maybe something like a keyword   "align=right" to place the current one right of the previous one.. but it would be nice to have the options to get them displayed like in a table (same with for all rows in a column).
with some keywords like this
```
[sometablename]
control=table
columns=2
rows=2
shortdesc=text

[someentry]
control=spinbox
group = true
row = 1
column  =  1
shortdesc=some text

[another entry]
control=spinboxf
group = true
row = 1
column  =  2
shortdesc=some other text
```

**Comment by J2Kbr** [comment]
I was thinking in implement the ability to layout the controls horizontally for quite a while. This request was the motivation needed to finally work on that. :) Thanks.

With Gtuner Iv 1.00RC-90 is possible to group horizontally with `groupcol`. 

`groupcol` works similarly as `group`, but first create a new column to place the control. Is possible alternate the use of `group` and `groupcol` to create nice layouts.
