### ISSUE TITLE
Feature Request: Add Folder to File Tab Name When Multiple Files With Same Name Opened

### ISSUE THREAD

**Issue by PoshLemur** [J2Kbr/GtunerIV#295]
It would be really nice if the folder name was shown next to the file name if you have multiple scripts open with the same name.

Filename — FolderName

To keep tab sizes down there could be a max char length where the folder name string is just truncated.
E.g. `SomeReallyLongFolderName` would just become `SomeRea...`

![1](https://user-images.githubusercontent.com/39054593/52982195-9091d500-3399-11e9-9b19-64ed45c0900d.png)

This could make it immediately clear what file is being worked on when multiple files have the same name.

**Comment by J2Kbr** [comment]
By positioning the mouse cursor at the top-left corner of the GPC code editor you can check the full path of the file:
![image](https://user-images.githubusercontent.com/21229433/54086606-9db33b80-4329-11e9-8a5b-4cf4958f97e3.png)

**Comment by J2Kbr** [comment]
I have just see this: https://github.com/J2Kbr/GtunerIV/issues/291 (sorry for suggesting something you already know).
