### ISSUE TITLE
F9 and Interactive Configuration in include file not working

### ISSUE THREAD

**Issue by Scachi** [J2Kbr/GtunerIV#297]
It is working fine on the compiled version .gbc of a script that has the IC in a seperate file, but not with Debug & Run - F9 Preview from the main .gpc file. I have to switch to the file containing the IC first.
Is it possible to get this working with the F9 preview too ?
With the Preview and the IC in a seperate file I get when started from the main file: 
`Preview GCD: Configuration Descriptor not found or empty.`
If this is too much work I am ok with how it is right now, switching tabs or opening the IC file first isn't that complicated^^

**Comment by PoshLemur** [comment]
Can you explain F9 not working? I used my F9 key in a script a few days ago and it worked fine.

**Comment by J2Kbr** [comment]
Hi Scachi. This behavior is intentional. The F9 Preview checks only the active file for the Interactive Configuration descriptors.
