### ISSUE TITLE
GTuner IV 32bit Version: Update problem - block Update ?

### ISSUE THREAD

**Issue by Scachi** [J2Kbr/GtunerIV#298]
You mentioned that you will block the update for the 32bit version.
https://www.consoletuner.com/forum/viewtopic.php?f=27&t=10860&p=75307&hilit=32bit#p76151

Not sure if you already did that, but it looks like another user still has the problem of the 32bit version doing the update:
https://www.consoletuner.com/forum/viewtopic.php?f=27&t=12032&p=81405#p81405

**Comment by Scachi** [comment]
I think you have fixed it now:
https://www.consoletuner.com/forum/viewtopic.php?t=12032&f=27#p81405

**Comment by J2Kbr** [comment]
Correct, this was fixed at server side. thanks.
