### ISSUE TITLE
html tags and linebreak again

### ISSUE THREAD

**Issue by Scachi** [J2Kbr/GtunerIV#299]
Can you please add the handline of linebreak for the tags
```<h3>``` and alike too like you did for ```<table>``` and co ?
right now it is adding extra lines in.
Please check the handling of ```<hr>``` too.

**Comment by J2Kbr** [comment]
`<hr>`, `<h1>`, `<h2>`, `<h3>`, `<h4>`, `<h5>`, `<h6>` were added and will be available on the next Gtuner IV release. thanks.
