### ISSUE TITLE
GTuner Pro IV Light Party on Online Resources

### ISSUE THREAD

**Issue by MMachor** [J2Kbr/GtunerIV#3]
GTuner Pro IV has a "lighting party" on open.  Rainbow color effect flashes on all objects and text when viewing "Online Resources."  This has been reported by multiple users.  I have been able to reproduce once, but have not been able to again after that.  Current fix is to close GTuner Pro IV and re-open it.  This is an intermittent issue that can not be easily reproduced.  Does not seem to affect functionality at all.

**Comment by prototypeGtuner** [comment]
Happened 3 times for me, only when i change scripts order.

**Comment by J2Kbr** [comment]
There is a great chance this was caused by the lack of html sanitize of user input fields on published scripts. Making possible add java script code to manipulate the Online Library page elements. It was implemented proper sanitize.
