### ISSUE TITLE
KMG Capture + DS4 on PC: "Share" and "Touchpad Click" buttons are swapped

### ISSUE THREAD

**Issue by HeyItsLollie** [J2Kbr/GtunerIV#300]
When the DualShock 4 is connected to the PC (either via USB or bluetooth), and KMG Capture is used, GTuner IV shows that the the DS4's "Share" button is being mapped to "Touchpad Click" and vice versa.

**Comment by J2Kbr** [comment]
Replied here: https://github.com/J2Kbr/GtunerIV/issues/301
