### ISSUE TITLE
Feature Request: Allow KMG Capture to grab DS4 Touchpad, Accel, and Gyro

### ISSUE THREAD

**Issue by HeyItsLollie** [J2Kbr/GtunerIV#301]
I'd like to see KMG Capture grab a (PC-connected) DualShock 4 controller's touch pad, accelerometer, and gyro controls. It seems odd that KMG Capture doesn't capture all of the controller's available features.

**Comment by J2Kbr** [comment]
The standard HID drivers available on Windows does not support the PS4 specific functions (e.g. touchpad, motion sensors). This, unfortunately, is not something Gtuner IV can workaround (unless implementing a driver to access the PS4 controller directly, without using the APIs provided by the OS).

This is also the reason the `Share` and `Touchpad Click` are swapped. However, for this you can use a Input Translator or script to fix the mappings for button . 

Side note: the gamepad capture is fully build on top of the Windows API for HID Joysticks, which in general works very well for devices made for PC. Console gamepads have several "vendor" features that requires specialized drivers, in this case the best is connect the controller directly to the Titan Two.
