### ISSUE TITLE
Slot's infos not updated

### ISSUE THREAD

**Issue by prototypeGtuner** [J2Kbr/GtunerIV#302]
I see a lot of users complaining about scripts sometimes won't load in the slots but the issue i have is that the upload time is not updated but then i disconnect/reconnect the device from the toolbar the script is loaded and the upload time is correct.

Is it a bug or just me?

EDIT: same for the internal memory or the SD card.
EDIT2: same behavior when the slot was cleared, the script won't show in the slot but after a disconnect/reconnect the script is in the slot.

**Comment by J2Kbr** [comment]
All reported cases were fixed and will be available on the next Gtuner IV release (requires Titan Two firmware update).
