### ISSUE TITLE
lower required Ios version

### ISSUE THREAD

**Issue by prototypeGtuner** [J2Kbr/GtunerIV#304]
I'm an Android user and my Iphone is 4S, could Gtuner Air supports lower Ios version?

**Comment by prototypeGtuner** [comment]
Needs a Gtuner Air github.

**Comment by J2Kbr** [comment]
We now have Gtuner Air GitHub: https://github.com/J2Kbr/GtunerAir

Related with your request, unfortunately the Qt framework used by Gtuner Air requires minimum a iOS 10.0.
