### ISSUE TITLE
Feature Request: Code formatting

### ISSUE THREAD

**Issue by lavarsicious** [J2Kbr/GtunerIV#305]
As suggested in this [forum post](https://www.consoletuner.com/forum/viewtopic.php?f=25&t=12391), it would be helpful if Gtuner had a basic code formatting implementation.

For example, IDEs like Visual Studio have a basic *Format Document* (or selection) implementation via CTRL-K, CTRL-D. Jetbrains products have a *Reformat Code* option and [CLion](https://www.jetbrains.com/clion/) does an OK job of parsing gpc but obviously can't parse or doesn't support some of the language features.

I'm not looking for anything over the top - just a shortcut that'll clean up the basics like white space and braces. (though configurable tabs/spaces would be nice)

**Comment by J2Kbr** [comment]
Feature added on Gtuner IV 1.04. Thank you for your suggestion.

**Comment by lavarsicious** [comment]
You're awesome
