### ISSUE TITLE
Update Notification typo in output panel ?

### ISSUE THREAD

**Issue by Scachi** [J2Kbr/GtunerIV#306]
English isn't my first language, no idea if this is also correct..
The notification text is this atm:
```Update Avaliable: Titan Two.....```
shouldn't that read:
```Update Available: Titan Two.....```
?

**Comment by sillyasskid** [comment]
Yes you are correct, it should be spelled " **Available** ".

Also when you check for updates. You will see
" Newer Version Avaliable "

Should be corrected to
" Newer Version **Available**  "

**Comment by J2Kbr** [comment]
Fixed on Gtuner IV 1.03. Thanks.
