### ISSUE TITLE
Feature Request: Submitting to the Online Resource as .gpc should submit .gbc too

### ISSUE THREAD

**Issue by Scachi** [J2Kbr/GtunerIV#307]
I already got user contacting me asking how to access my script via GTuner Air.

To have all scripts available in GTuner Air we need the ability to submit our scripts to the Online Resource as bytecode or sourcecode and have it always include the bytecode upload too.

I don't think that there is an requirement to have this selectable for .gpc files.
When I submit a script as .gpc it should just submit as bytecode at the same time.

I don't want to have to upload all my scripts twice with different names (one as .gpc , one as .gbc) like myscript.gpc and myscript_Air.gbc just to have it available in GTuner Air.

**Comment by sillyasskid** [comment]
I thought it already did this though? 

When you publish a GPC script. Users have to option to download the script or drag and drop the script to a memory slot. 

Downloading the script gives you access to the GPC source file.

But if you were to Drag and Drop the script to a memory slot. 

This would only give you access to the .GBC file.

**Comment by Scachi** [comment]
No.. I think GTuner IV does compile it in the moment you Drag & Drop it to a slot if it was submitted as .gpc

**Comment by J2Kbr** [comment]
Feature added on Gtuner IV version 1.02

**Comment by Scachi** [comment]
Does this really need to be optional ? 
Shouldn't that be the default setting (it isn't checked for me on new projects) or even forced to always submit .gbc as this doesn't hurt anyone when it submits both when .gpc is selected only ?

**Comment by J2Kbr** [comment]
I believe have this optional to the user is better. For example, I have many published scripts that are basically code samples, which don't have utility using on Gtuner Air.

**Comment by Scachi** [comment]
Oh right.. good point.
