### ISSUE TITLE
New GPC function required - the ability to set mouse DPI

### ISSUE THREAD

**Issue by PablosScripts** [J2Kbr/GtunerIV#308]
I am now using the T2 for PC. On console, mouse DPI's need to be very high (3000 - 4000 is generally recommended for XIM), however on PC this is overkill. I need to constantly swap it back and forth again and it would be great if I could automatically set this in each script.

**Comment by sillyasskid** [comment]
The Mouse DPI setting in GtunerIV only effects Input translators. It is used with the mxyconverter. This setting serves no purpose on PC when using mouse_passthru()

**Comment by PablosScripts** [comment]
This makes sense, I will close this.
