### ISSUE TITLE
Expand or Collapse should be saved on a per-script basis

### ISSUE THREAD

**Issue by PablosScripts** [J2Kbr/GtunerIV#309]
Some scripts I have lots of code sections that I need to collapse in order to be able to see anything. I find myself having to press the collapse button every time I open the script, and then scroll down and selectively open up certain sections again. It becomes really annoying! However some scripts don't have many sections that need to be collapsed at all so I wouldn't want this to be either an expand all or collapse all by default. I propose that on a per-script basis, the collapse / open state of each script and script segments should be remembered (so basically the script is returned to the state exactly as you left it after closing).

**Comment by J2Kbr** [comment]
With "Save As Project" you can achieve the described behavior. A project will remember all opened files (one or more), the folding state as well as the scrollbar and cursor position of each file.
