### ISSUE TITLE
Feature Request: Limit the shown shortdesc text in the Online Resource..add a "show more" unfoldable

### ISSUE THREAD

**Issue by Scachi** [J2Kbr/GtunerIV#310]
The length of some <shortdesc>descriptions of published scripts seem to get very long.

Scrolling through them is kind of annoying as they are showing a lot of details already when one want to search the names/available scripts first.
For some I have to scroll two screens (2x1080 px) down until I can see the next download.

I like the layout/handling of GTuner Air in this case. It only shows the names first and on click it shows the details. 
But that may be a bit to restrictive for some users.

Maybe we can get something like it cuts off the text by an adjustable "row count" in GTuner IV..
or make this limit hard coded and add a "show more" link to unfold the complete text when I want to see it.

The default visible height can be limited to the count of rows shown on the right of each script:
![grafik](https://user-images.githubusercontent.com/22262242/57378309-c4181a80-71a4-11e9-9479-845210968ba5.png)

Without any limit it is getting out of control already.

**Comment by prototypeGtuner** [comment]
Yes some users like to show all details and updates history. It takes too much space for a pleasant navigation. I've been thinking about it for months, a way to fold that would be great. +1

I still don't have tried Gtuner Air but i'm happy it's folded!

**Comment by J2Kbr** [comment]
Feature implemented (server side). The height to trigger "Show more..." was set to 200px. Tried the suggested height but didn't work well, too much scripts were getting truncated, 200px seems to be a good balance. The Online Resources page may not render properly (for a while) in your Gtuner due the cache. On Gtuner IV 1.04 the cache is cleared at application exit.
