### ISSUE TITLE
T2 / LOGITECH X56

### ISSUE THREAD

**Issue by STE6256** [J2Kbr/GtunerIV#312]
Need to get T2 to correctly see the Logitech X56.
Currently T2 does not recognize all the buttons, toggles and switches.
X56 is comprised of a joystick and throttle (2 USB ports needed)

**Comment by J2Kbr** [comment]
HID configuration files for:

Mad Catz Saitek Pro Flight X-56 Rhino Stick 
and
Mad Catz Saitek Pro Flight X-56 Rhino Throttle

were added to Gtuner IV version 1.02 (to be release shortly).

**Comment by STE6256** [comment]
Awesome. Thank you very much
