### ISSUE TITLE
Clearing/overwritting a slot does not remove the existing Interactive Configuration of that slot

### ISSUE THREAD

**Issue by Scachi** [J2Kbr/GtunerIV#314]
GTuner IV 1.1.3.0

Clearing/overwriting a slot does not remove the existing Interactive Configuration of that slot.

I have a script with IC installed to slot 1.
I delete this script or overwrite this script with a new scripts that doesn't have an IC.
The IC configuration icon is shown for that slot. Clicking that icon will open the IC of the previous installed script.

I would expect GTuner IV to show no IC icon when the current script of that slot doesn't have an IC.
It should remove the IC of that slot when clear a slot or overwirting the slot without holding ctrl.

**Comment by Scachi** [comment]
There is something wierd going on.
I put a script onto slot 4.
I modified the IC of the script, didn't change the #pragma version number or name, and put it on slot 9.
Both, slot 4 + 9 are showing the new IC.
When I change the version number in the #pragma line it does handle both slots correctly, showing a different IC for slot 4 and slot 9.

**Comment by J2Kbr** [comment]
The Gamepack/Script configuration descriptor files are cached locally, on computer, and not on the device. The filename for the cache file is computed based on the `#pragma METAINFO` information (name, version, author). If any of these data changes, a new cache file is generated.

Multiple memory slots can share the same cached configuration file, in the case where `#pragma METAINFO` is exactly the same.

A cached configuration file is not deleted when a memory slot is cleared or overwritten, as others memory slots can be using that file.

If needed, you can manually delete the cached configuration files in the sub-directory `cache` (all files with extension .gcd).
