### ISSUE TITLE
Feature Request - Test and Debug : Option to clear Output panel on start of script

### ISSUE THREAD

**Issue by Scachi** [J2Kbr/GtunerIV#315]
An additional option (in Preferences->Test and Debug) to clear the Output Panel on start of the "Test and Debug" run before it compiles would be nice and save some time.
I often rightclick->"Clear All" in the Output Panel to clear it up at the moment.

**Comment by J2Kbr** [comment]
Feature added to Gtuner IV 1.02. Thank you for your suggestion.
