### ISSUE TITLE
Feature Request : Publish Wizzard : Save checkbox state "Include .. for GTuner Air" 

### ISSUE THREAD

**Issue by Scachi** [J2Kbr/GtunerIV#317]
Publish Wizard is saving if a script was submitted as bytecode or gpc but it doesn't save if the Gtuner Air checkbox was selected.
Please save the state of the "Include...Gtuner Air" checkbox too.

**Comment by Scachi** [comment]
Wouldn't the "GTuner Air" be located better at the top where "Publish Active Work" is ? 
Like have it named "Publish for GTuner Air"
It is hard to see at the bottom of a big list of include files:
![grafik](https://user-images.githubusercontent.com/22262242/61472470-c8bb3500-a984-11e9-8992-117ef8b9c3a2.png)


So when the "Publish as GPC Bytecode" is checked it can automatically check the "GTuner Air" too and set its state to greyed to indicate that "Publish as GPC Bytecode" will also make it available in GTuner Air ?
When not doing "Publish as GPC Bytecode" I can check the box manually.

Saving the state of the last Gtuner Air publish used will also save it as checked when I did publish it as bytecode before and switch over to source code publish  (as is was checked automatically). This way GTuner Air publish checkbox is almost automated.

**Comment by J2Kbr** [comment]
On Gtuner IV 1.04, the option to include bytecode for Gtuner Air is preserved on subsequent publishing (update) of the script.

**Comment by Scachi** [comment]
Have you considered moving the "include for GTuner Air" to "Publish Active Work for GTuner AIr" section at the top for better visibility ?
Take a look at my screenshot. When publishing as source code it is easy to miss.

**Comment by J2Kbr** [comment]
Yes, but for me it seems better keep the option to include for Gtuner Air next the Configuration Descriptor file (.gcd), as it is desirable -in most cases- to also include the `gcd` in this case, when available. The publishing interface is build dynamically and the `gcd` file can only be determined after parsing the `gpc` and all `gph` files.

**Comment by Scachi** [comment]
Ok. Thanks for explaining it.
It looks like 99% do publish their stuff as bytecode, so it doesn't matter much. They will never see that checkbox anyway.
Having the checkbox state preserved should be fine enough.
Thank you ;-)
