### ISSUE TITLE
T-Flight Hotas PS4 Descriptors

### ISSUE THREAD

**Issue by swoodbury1963** [J2Kbr/GtunerIV#318]
[USB DESCRIPTOR]
12 01 10 01 00 00 00 40 4F 04 7B B6 00 01 01 02 00 01 09 02 29 00 01 01 00 80 32 09 04 00 00 02 03 00 00 00 09 21 11 01 00 01 22 A0 00 07 05 84 03 40 00 05 07 05 03 03 40 00 05 

[STRING 1 DESCRIPTOR]
00 00 00 02 00 00 02 01 80 06 03 01 04 09 00 1A 
1A 03 54 00 68 00 72 00 75 00 73 00 74 00 6D 00 61 00 73 00 74 00 65 00 72 00 

[STRING 2 DESCRIPTOR]
00 00 00 02 00 00 02 01 80 06 03 02 04 09 00 1E 
1E 03 54 00 2E 00 46 00 6C 00 69 00 67 00 68 00 74 00 20 00 48 00 6F 00 74 00 61 00 73 00 

[INTERFACE 0 HID DESCRIPTOR]
00 00 00 02 00 00 02 01 81 06 22 00 00 00 00 A0 
05 01 09 05 A1 01 85 01 09 30 09 31 09 32 09 35 15 00 26 FF 00 75 08 95 04 81 02 09 39 15 00 25 07 35 00 46 3B 01 65 14 75 04 95 01 81 42 65 00 05 09 19 01 29 0E 15 00 25 01 75 01 95 0E 81 02 06 00 FF 09 20 75 06 95 01 81 02 05 01 09 33 09 34 15 00 26 FF 00 75 08 95 02 81 02 06 00 FF 09 21 95 36 81 02 85 05 09 22 95 1F 91 02 85 03 0A 21 27 95 2F B1 02 C0 06 F0 FF 09 40 A1 01 85 F0 09 47 95 3F B1 02 85 F1 09 48 95 3F B1 02 85 F2 09 49 95 0F B1 02 85 F3 0A 01 47 95 07 B1 02 C0 

[USB SNIFF]
00 00 00 01 00 00 01 00 00 05 00 0C 00 00 00 00 
00 00 00 02 00 00 02 01 00 05 00 03 00 00 00 00 
0C 
00 00 00 01 00 00 01 00 80 06 01 00 00 00 00 08 
00 00 00 02 00 00 02 01 80 06 01 00 00 00 00 08 
12 01 10 01 00 00 00 40 
00 00 00 01 00 00 01 00 80 06 01 00 00 00 00 12 
00 00 00 02 00 00 02 01 80 06 01 00 00 00 00 12 
12 01 10 01 00 00 00 40 4F 04 7B B6 00 01 01 02 00 01 
00 00 00 01 00 00 01 00 80 06 03 00 00 00 00 02 
00 00 00 02 00 00 02 01 80 06 03 00 00 00 00 02 
04 03 
00 00 00 01 00 00 01 00 80 06 03 00 00 00 00 04 
00 00 00 02 00 00 02 01 80 06 03 00 00 00 00 04 
04 03 09 04 
00 00 00 01 00 00 01 00 80 06 03 01 04 09 00 02 
00 00 00 02 00 00 02 01 80 06 03 01 04 09 00 02 
1A 03 
00 00 00 01 00 00 01 00 80 06 03 01 04 09 00 1A 
00 00 00 02 00 00 02 01 80 06 03 01 04 09 00 1A 
1A 03 54 00 68 00 72 00 75 00 73 00 74 00 6D 00 61 00 73 00 74 00 65 00 72 00 
00 00 00 01 00 00 01 00 80 06 03 02 04 09 00 02 
00 00 00 02 00 00 02 01 80 06 03 02 04 09 00 02 
1E 03 
00 00 00 01 00 00 01 00 80 06 03 02 04 09 00 1E 
00 00 00 02 00 00 02 01 80 06 03 02 04 09 00 1E 
1E 03 54 00 2E 00 46 00 6C 00 69 00 67 00 68 00 74 00 20 00 48 00 6F 00 74 00 61 00 73 00 
00 00 00 01 00 00 01 00 80 06 02 00 00 00 00 09 
00 00 00 02 00 00 02 01 80 06 02 00 00 00 00 09 
09 02 29 00 01 01 00 80 32 
00 00 00 01 00 00 01 00 80 06 02 00 00 00 00 29 
00 00 00 02 00 00 02 01 80 06 02 00 00 00 00 29 
09 02 29 00 01 01 00 80 32 09 04 00 00 02 03 00 00 00 09 21 11 01 00 01 22 A0 00 07 05 84 03 40 00 05 07 05 03 03 40 00 05 
00 00 00 01 00 00 01 00 00 09 00 01 00 00 00 00 
00 00 00 02 00 00 02 01 00 09 00 01 00 00 00 00 
00 00 00 01 00 00 01 00 81 06 22 00 00 00 00 A0 
00 00 00 02 00 00 02 01 81 06 22 00 00 00 00 A0 
05 01 09 05 A1 01 85 01 09 30 09 31 09 32 09 35 15 00 26 FF 00 75 08 95 04 81 02 09 39 15 00 25 07 35 00 46 3B 01 65 14 75 04 95 01 81 42 65 00 05 09 19 01 29 0E 15 00 25 01 75 01 95 0E 81 02 06 00 FF 09 20 75 06 95 01 81 02 05 01 09 33 09 34 15 00 26 FF 00 75 08 95 02 81 02 06 00 FF 09 21 95 36 81 02 85 05 09 22 95 1F 91 02 85 03 0A 21 27 95 2F B1 02 C0 06 F0 FF 09 40 A1 01 85 F0 09 47 95 3F B1 02 85 F1 09 48 95 3F B1 02 85 F2 09 49 95 0F B1 02 85 F3 0A 01 47 95 07 B1 02 C0 
00 00 00 01 00 00 01 00 21 0A 00 00 00 00 00 00 
00 00 00 02 00 00 02 01 21 0A 00 00 00 00 00 00 
00 00 00 01 00 00 01 00 A1 01 03 03 00 00 00 30 
00 00 00 02 00 00 02 01 A1 01 03 03 00 00 00 30 
03 21 27 04 10 08 00 00 00 00 00 00 00 00 00 00 00 00 0D 0D 00 00 00 00 08 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
00 00 00 02 00 04 
01 80 80 80 80 08 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 80 00 80 80 FF 80 80 00 00 80 80 00 00 00 00 00 00 00 00 00 
00 00 00 02 00 04 
01 80 80 80 80 08 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 80 00 80 80 FF 80 80 00 00 80 80 00 00 00 00 00 00 00 00 00 
00 00 00 02 00 04 
01 80 80 80 80 08 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 80 00 80 80 FF 80 80 00 00 80 80 00 00 00 00 00 00 00 00 00 
00 00 00 02 00 04 
01 80 80 80 80 08 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 80 00 80 80 FF 80 80 00 00 80 80 00 00 00 00 00 00 00 00 00 
00 00 00 02 00 04 
01 80 80 80 80 08 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 80 00 80 80 FF 80 80 00 00 80 80 00 00 00 00 00 00 00 00 00 
00 00 00 02 00 04 
01 80 80 80 80 08 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 80 00 80 80 FF 80 80 00 00 80 80 00 00 00 00 00 00 00 00 00 
00 00 00 02 00 04 
01 80 80 80 80 08 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 80 00 80 80 FF 80 80 00 00 80 80 00 00 00 00 00 00 00 00 00 
00 00 00 02 00 04 
01 80 80 80 80 08 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 80 00 80 80 FF 80 80 00 00 80 80 00 00 00 00 00 00 00 00 00 
00 00 00 02 00 04 
01 80 80 80 80 08 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 80 00 80 80 FF 80 80 00 00 80 80 00 00 00 00 00 00 00 00 00 
00 00 00 02 00 04 
01 80 80 80 80 08 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 80 00 80 80 FF 80 80 00 00 80 80 00 00 00 00 00 00 00 00 00 
00 00 00 02 00 04 
01 80 80 80 80 08 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 80 00 80 80 FF 80 80 00 00 80 80 00 00 00 00 00 00 00 00 00 
00 00 00 02 00 04 
01 80 80 80 80 08 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 80 00 80 80 FF 80 80 00 00 80 80 00 00 00 00 00 00 00 00 00 
00 00 00 02 00 04 
01 80 80 80 80 08 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 80 00 80 80 FF 80 80 00 00 80 80 00 00 00 00 00 00 00 00 00 
00 00 00 02 00 04 
01 80 80 80 80 08 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 80 00 80 80 FF 80 80 00 00 80 80 00 00 00 00 00 00 00 00 00

**Comment by swoodbury1963** [comment]
I pulled these per request and process described.

"With the latest Gtuner VI and Titan Two firmware is possible to capture all USB device enumeration and the first 2 seconds of the USB device communication with the console (assuming the USB device is supported by the console in use).

For that proceed as the following:

1) Unplug all controllers from the Titan Two;
2) Connect the output to the console;
3) Connect the Prog port to your computer;
4) Open Gtuner IV and go to top menu Tools -> "Fetch Descriptors ...";
5) Plug the USB device to any port at the front of the Titan Two;
6) Wait couple seconds for this window be update with the captured data;
7) Click on the button "Copy Descriptors" and send to me."

**Comment by swoodbury1963** [comment]
Any Status update?

**Comment by swoodbury1963** [comment]
Checking status.

**Comment by swoodbury1963** [comment]
Update please.

**Comment by swoodbury1963** [comment]
Thanks for the message reply on the forums!

**Comment by J2Kbr** [comment]
You are welcome. As this request is related with the Titan Two firmware, I am closing here on the Gtuner IV GitHub.
