### ISSUE TITLE
Feature Request - GPC Script IDE :  show specific commented blocks as collapsed by default 

### ISSUE THREAD

**Issue by Scachi** [J2Kbr/GtunerIV#319]
Is it possible to have specific commented blocks to be shown as collapsed by default via some keywords or character ? Like `/*^ some commented long multiline block */`
This would be useful to fold specific comments by default when opening a .gpc/.gph file.
Not project specific, I want this file specific.. so I can use it for header files I use in multiple projects and open them sometimes only as required to look some notes up.
That is why I suggest a character or keyword.

Like for comments with detailed description I need sometines only but down't want to put it into an external file as it is for a specific function/part of the code and I want to place it at its location ?

**Comment by J2Kbr** [comment]
Automatic fold comments starting with `/*^` added on Gtuner IV 1.04.

It is also possible use this char sequence to automatic fold any block, example:

```
combo GuardBreaker { /*^*/
    set_val(MOVEMENT_X, 0);
    set_val(MOVEMENT_Y, 0);
    set_val(RIGHT_FAST, 0);
    wait(130);
    set_val(MOVEMENT_X, 0);
    set_val(MOVEMENT_Y, -100);
    set_val(RIGHT_FAST, 100);
    wait(40);
}
```

this combo will also start folded when the GPC file is opened. ;)

**Comment by Scachi** [comment]
Awesome. Very cool that this can fold any block.
