### ISSUE TITLE
"File Explorer" pane - Delete directory and its content

### ISSUE THREAD

**Issue by Scachi** [J2Kbr/GtunerIV#32]
Its annoying that it is not possible to delete a directory with all its files.
Please allow this.
Maybe with a msgwindow like "Directory is not empty ! Delete anyway ? [Yes] [_No]" if you won't add recursive delete otherwise.

**Comment by J2Kbr** [comment]
Starting from version 0.100B, Gtuner IV has an new delete operation called "Move to Trash", which works on directories with or without contents. The "Move to Trash" is now the default delete operation. "Delete Permanently" still exists via context menu.
