### ISSUE TITLE
#pragma meta info "<author_name>" in wrong place when no login is configured

### ISSUE THREAD

**Issue by Scachi** [J2Kbr/GtunerIV#320]
When creating a File->New->Minimum GPC Script 
with no login configured in Tools->Preferences->Console Tuner
the author is placed in the wrong spot/the filename is missing:
`#pragma METAINFO("<author_name>", 1, 0, "")`

When you have a login configured it will be correct:
`#pragma METAINFO("asdf", 1, 0, "Scachi")`

**Comment by J2Kbr** [comment]
Fixed on Gtuner IV 1.04.
