### ISSUE TITLE
 Feature Request - GTuner IV "External App Launcher"

### ISSUE THREAD

**Issue by Scachi** [J2Kbr/GtunerIV#321]
As briefly discusssed via PM, here is the github entry for it..details from PM..:
> I know you said supporting plugins is too much work for a cross-platform software (https://github.com/J2Kbr/GtunerIV/issues/219).. What about an option to launch "external apps" from withing GTuner with the requirement that GTuner IV passes on the .gpc filename(s) in use only ? A single filename, the currently openend/active .gpc tab, would be enough I think.

Don't know where to place the menu entries in the top menu. Some ideas:
"Tools->Launcher->'List of entries (like File->Recent Files->)"
"Tools->Run->'List of entries (like File->Recent Files->)"
"Tools->External->'List of entries (like File->Recent Files->)"

Having a "SomeNamed" toolbar automatically containing buttons for the each Launcher entry would be cool to be able to start them with a single click. Assigning custom hotkeys to the buttons would be a useful addition but having the buttons would by handy enough I think.

Configure them via "Tools->Preferences"->"SomeName"->Entries
with options to set for each entry
- custom name for this entry to show
- path+filename to custom icon to show in toolbar
- path+programm.exe + optional argument (like "/f $1" forthe currently active gpc filename from the gpc ide editor)
- override/set working directory
- order the entries by name ? so i could name the first one "1_Customname" to show at first or specific position in list ? or option to directly sort the list in the Tools->preferences->"SomeName"

**Comment by J2Kbr** [comment]
External Tools added on Gtuner IV 1.04. Configuration via `Preferences -> External Tools`:
```
Configure one external tool per line, following the format:

    <tool_name>, <path_to_executable>, <optional_arguments>, <optional_shortcut>

Shortcuts are defined by key sequence, examples: F3, Ctrl+M, Ctrl+Shift+T. 
Optional separator between tools can be configured with '-'.

Replacement variables:

    $CURR_FILE$: Full path to currently active file
    $WORK_DIR$: Full path to working directory
    $DATA_DIR$: Full path to data directory
```
External Tools are accessible via `Tools -> External Tools`. Include on toolbar would be too much trouble. The optional shortcut -I believe- is good enough for quick access.

**Comment by Scachi** [comment]
Sounds great. Yes, I think the shortcut only solution is fine. Thanks !

**Comment by Scachi** [comment]
Nice one ! Works perfectly with IC-Bytetable on Control+Shift+B:
GTuner IV -> Tools -> Preferences ->Etxernal Tools :
```
IC-Bytetable, C:\Users\Username\Documents\T2\___T2_My_Stuff\00_AutoIT\IC-Bytetable\IC-Bytetable.exe, "$CURR_FILE$", Ctrl+Shift+B
````

**Comment by J2Kbr** [comment]
Awesome, I knew you would be happy. :) This integration is really great.
