### ISSUE TITLE
#define are getting parsed from within comments with #include "file.gph"

### ISSUE THREAD

**Issue by Scachi** [J2Kbr/GtunerIV#322]
Not sure if this is normal behaviour or not...
#define's are getting parsed from within comments via #include's

Create a file 1.gph that contains this
```
//#define TY 1
```
Save it. AFTER saving the file create a new file 1.gpc.

1.gpc content:
```
#include "1.gph"

#ifdef TY
main {
	
}
#endif
```
now CLOSE the file 1.gpc and REOPEN it for it to parse the header file.

Result: TY is defined.. main section is not shown greyish.

**Comment by sillyasskid** [comment]
Its not actually defined. Just appears to be.
The compiler is not actually parsing the definition

Try this, 
If it actually was defined it would not compile.
```
#include "1.gph"
#ifdef TY
#error TY is defined
main {
}
#endif
main { }
```

**Comment by Scachi** [comment]
So it is just the visual presentation of it being defined is not correct then.

**Comment by J2Kbr** [comment]
Gtuner IV 1.04 implements active monitoring of the definitions from included header files.
