### ISSUE TITLE
Feature Request: Add seconds and microseconds to timestamps in output panel

### ISSUE THREAD

**Issue by seededplyr** [J2Kbr/GtunerIV#323]
![2019-07-11_125652](https://user-images.githubusercontent.com/8683682/61098018-153bd780-a490-11e9-8e95-4fa4f07f9a7c.jpg)

Add seconds and microseconds to timestamps in output panel

https://www.consoletuner.com/forum/viewtopic.php?f=25&t=13043

**Comment by J2Kbr** [comment]
Added on Gtuner IV 1.04.

Enable precise timestamps under Tools -> Preferences -> Environment
