### ISSUE TITLE
Feature Request - Option to specifiy download directory (Online Resource)

### ISSUE THREAD

**Issue by Scachi** [J2Kbr/GtunerIV#324]
The current storage of downloaded stuff from the Online Resource fills up the set working directory.

An option to specify a "Online Resource" storage directory within the set "working directory" would be nice as I prefer a directory structe like this:
/some/path/to/my/T2 work dir/
/some/path/to/my/T2 work dir/"__Online Resource"/

Saving my own stuff directly in the "T2 work dir" then:
/some/path/to/my/T2 work dir/myscript1/myscriptfiles.gpc
/some/path/to/my/T2 work dir/myscript2/myscriptfiles.gpc
.
.

I know I could create it the other way around:
/some/path/to/my/T2 work dir/__mystuff
/some/path/to/my/T2 work dir/_download1
/some/path/to/my/T2 work dir/_download2

But in theory this isn't preventing a download from being saved into my own stuffs directory.
An option for a download directory would "lock" the download from getting saved into my own directory because of some name clash with somthing in the Online Resource.

Having setup a specific folder for the downloaded content would also enable easier checking for script+gamepack update notification. This is one feature I am really missing.
When doing a download you could create a specific file in this folder with update check informations (scriptname,version,author) or parse all directories and files for #pragma version numbers instead.

**Comment by prototypeGtuner** [comment]
+1 i don't use the work dir because of that, a way to choose the downloaded stuff directory would be nice.

**Comment by J2Kbr** [comment]
Gtuner IV 1.04 adds the option (`Preferences -> Environment`) to store downloaded contents into subdirectory `Downloads`, instead of prefix with '_'.

**Comment by Scachi** [comment]
The reason I asked it to be named prefixed with a "_" like "_Downloads" was to have it stay at a specific position in the directory listing and have it out of the way of my script directories.
Or an option to have its name configurable.
I don't know if anyone else would like to have it this way so I don't know if this is worth the work,

I can create a junction _Downloads -> Downloads with `mklink /j _Downloads Downloads` and hide the Download directory `attrib +h Downloads` to have it the way I would prefer it. I just have to test if gtuner will still be able to work correctly for downloading stuff in this case. But it shouldn't be a problem I think.

**Comment by prototypeGtuner** [comment]
Thanks for the downloads directory, i was wanting that since a while.

"Downloads" is fine but "_Downloads" would allow to stay at the top of the work dir..+1

**Comment by Scachi** [comment]
@J2Kbr Not sure if you missed that information, the wish for renaming it to _Downloads. 
Pease see the two last comments, Thank you.

**Comment by J2Kbr** [comment]
Yes, I read the suggestion. Still considering some possible options. I'd prefer not make this fully configurable as Gtuner would also have to make input parsing, verification, permission tests etc if the sub-directory can be arbitrarily set by the user. Also, not entirely happy with fixed '_Downloads', because I prefer just 'Downloads' in my working directory structure. :)

Using junctions, as alternative, should work. I am also considering a manual entry in the `Gtuner.cfg` file to set the subdirectory, so only 'determined' users will make this change.

**Comment by J2Kbr** [comment]
Okay, I am doing the manual entry in the `Gtuner.cfg`:
```
[Advanced]
downloads_subdir=_Downloads
```

**Comment by Scachi** [comment]
I don't like having too many options in GTuner preferences too. GTuner IV is already complex enough.
Having a manual entry in GTuner.cfg for such advanced/rarely used features sounds fine to me.
