### ISSUE TITLE
Feature Request - Gamepack&script update checking+notification

### ISSUE THREAD

**Issue by Scachi** [J2Kbr/GtunerIV#325]
Implementing issue #324 
could enable easier parsing and checking for available updates of gamepacks ands script.

It could be done by creating a new file in each downloaded scripts/headers directory with update checking informations (gamepack/script name,versionr,author) and lloking for those files only or
parsing the whole "download" folders content for #pragma lines and check the version number against the current one available at the online resource.

When the one or  more version numbers doesn't match mark them with some icon in the "File Exlorer" pane and a notification message to the user that there are updates available for downloaded scripts/used gamepacks.

Checking for updates by the information parsed from the connected Titan Two Slots would be nice too. This way you could check for gamepack updates are those aren't really stored in the local "download" folder.

**Comment by J2Kbr** [comment]
Implementing this request would be more challenging than it sounds. On the server, the works are indexed using user_id + unique_work_hash. This information are used by Online Resources for basically just start a download, but lost even before the files are received. The Online Resources panel is entirely generated on server-side, Gtuner IV just displays the results, with very little active work (save downloaded files, store into a memory slot, dialog to confirm deletion of a work).

For reference, Pablo also made a related request on #96.
