### ISSUE TITLE
Example "Configuration Descriptor", 1, 7, "Example" is missing key "collapsible"

### ISSUE THREAD

**Issue by Scachi** [J2Kbr/GtunerIV#326]
#pragma METAINFO("Configuration Descriptor", 1, 7, "Example")
Would be nice to have the key list complete. 
I think the only thing missing is "collapsible" in the "Valid Keys" list in the example script.

Wiki page:
https://www.consoletuner.com/wiki/doku.php?id=t2:gpc_scripting:interactive_configuration

**Comment by J2Kbr** [comment]
Updated. Thank you for reminding about adding collapsible to the example.
