### ISSUE TITLE
Feature Request - Interactive Configuration - add "Right-Click context entry" to reset a single control to its default value

### ISSUE THREAD

**Issue by Scachi** [J2Kbr/GtunerIV#327]
It looks like we can only reset all values to default values at the moment.
When I have adjusted some values and want to reset a single one later on it would be useful to be able to do that with the right mousebutton context menu on a the specific control I want to set to default if possible.

**Comment by J2Kbr** [comment]
Right-click context menu to restore the default value of individual controls was added on Gtuner IV 1.04.
