### ISSUE TITLE
Feature Request - KMG Capture: Option to enable/disable capturing keyboard in exclusive mode.

### ISSUE THREAD

**Issue by ghost** [J2Kbr/GtunerIV#328]
Following on from this forum post - [https://www.consoletuner.com/forum/viewtopic.php?f=27&t=9561&hilit=keyboard+exclusive&start=20](https://www.consoletuner.com/forum/viewtopic.php?f=27&t=9561&hilit=keyboard+exclusive&start=20)

Add the option to choose between capturing Keyboard in exclusive mode or not, when Mouse capture is disabled. This would make it possible to combine the Titan Two with something like voice control or any software the transmits key presses, to play all on one Windows machine. As it stands this is limited as keyboard key presses are still detected by games.

Perhaps an option to choose in **Preferences > KMG Capture** could work?

**Comment by J2Kbr** [comment]
Researching for a solution for this request, it was verified the Windows RAW HID Input API does not provides exclusive mode for keyboards (only for mice). Reference:

https://stackoverflow.com/questions/14306167/exclusive-mouse-keyboard-with-the-winapi
