### ISSUE TITLE
Split screen for code window 

### ISSUE THREAD

**Issue by hhezart** [J2Kbr/GtunerIV#33]
It would be great if we can have split screen for the code window. I'm close to 1200 lines of code and scrolling up/down is becoming tedious.

**Comment by J2Kbr** [comment]
With the inclusion of bookmarks on code editor (Gtuner IV 0.100B) #17 and considering that the implementation of an split-screen code editor would require a lot effort, as the framework in use does not support this feature, I believe this issue can be closed, at least temporarily until we have enough time to test if the solution provided by the bookmarks offers an satisfactory solution for this issue.
