### ISSUE TITLE
Resizing GTuner IV Window

### ISSUE THREAD

**Issue by Scachi** [J2Kbr/GtunerIV#330]
I run GTuner IV in a Window around 80% display width/non fullscreen most of the time.
Sometimes I switch to Full Screen mode and I think the resizing priority order of the panes needs some changes.

Left Section | Main Section | Right Section
------------ | ------------- | -------------
File_Explorer, Find/Replace | Online_Resource, GPC_Script_IDE, ... | Memory_Slots, Device_Configuration

**Behaviour of GTuner IV Resizing at the moment:**
- Maximizing the GTuner IV Window seems resize the "Left Section" (File Explorer) to cover the space that wasn't used before. 
- Returning to the previous window size by clicking the button again seems to resize the "Left Section" AND the "Main Section"

**Expected behaviour:**
I would expect the Window to change the size of the "Main Section" only when using the "Maximize/Reduce" button. 
I know I can press "F11" and restore its size but I still think GTuner should return to this previous size on its own in the case of using the "Maximize/Reduce" button. Using the F11 button in this case feels like a workaround.

**Comment by Scachi** [comment]
I have reinstalled GTuner IV and it seems to be working correctly now.

**Comment by Scachi** [comment]
No... it looks like it depend on the active tap in the main section.
The resizing isn't working when the "GPC Script IDE" is openend.
For all other tabs of the main section it is returning to its previous size correctly.

Please fix this if possible.

**Comment by J2Kbr** [comment]
Fixed on Gtuner IV 1.04
