### ISSUE TITLE
Feature Request: Publish Wizzard -> Publish to Online Resource Private Usage -> GTuner Air

### ISSUE THREAD

**Issue by Scachi** [J2Kbr/GtunerIV#331]
Being able to submit scripts for private use to the Online Resource would fill the gaps that we can't :
- use GTuner Air for script one doesn't want to share.
- send scripts from pc directly via bluetooth to the T2.

Private Use -> Script Only available to the user that submitted the script. No one else will have access to that content.

Limiting the private count of script may be needed to avoid user from filling up your server with thousand entries of private stuff they will  never use at all.
When limiting the count of private script it could be required to use an extra "Publish" entry for that and not fill up the Publish Wizzard with more options and checkboxes.

Idea:
Having the request for the feature to launch external programs from within Gtuner IV
https://github.com/J2Kbr/GtunerIV/issues/321
You could put this private GTuner Air content submission and data management/handling into an external program. "GTuner Air PRM"  (private resource manager) or something shorter/more funky,
The program could use the design of the "Online Resource" in Gtuner IV for a "GTuner Air Private Resource" 
Having all of this in an external program that can be started from within gtuner IV via external program launch for the selected/opened script would save gtuner IV from getting more and more features and harder to use.

GTuner Air has already the option to set the  console tuner login.
A way to show the own private stuff only would be useful to make itd usage userfriendly.
One way I can think of is to add a button to switch between "Online Resource" and "Private Resource"
to the configuration of GTuner Air (the three bars at the top right corner).
Or split the "RESOURCES" tab at the bottom into something like this while markign the active one green as you do with the Resource / Library:
![grafik](https://user-images.githubusercontent.com/22262242/63407078-efd5ae00-c3eb-11e9-8003-4341d019965c.png)

**Comment by J2Kbr** [comment]
I believe to have found a good server-side only solution that will satisfy the described needs. 

When publishing, if the field `author` is set with value `Private` (case sensitive) will make the work (script, input translator, etc) private to the user who published.

On Gtuner IV a little icon of a lock is shown to indicate that work is private.

To list your private works, search for `Private`.

This is already working and does not require Gtuner IV or Gtuner Air update.

**Comment by Scachi** [comment]
Uhm.. this is kind of too complicated at the moment I think. 
- It all requires the user to know of this functionality. Some forum member requested some option like this for usage with GTuner Air so having it available in "Preferences" would be good. https://www.consoletuner.com/forum/viewtopic.php?f=2&t=12258&p=88558#p88424
- I can't upload using the same filename. For testing modifications of already existing scripts I have to rename it before upload. When testing went fine and I want to publish it I have to remember to rename it again.
- I have to change the author manually to "Private" or have to change it in the renamed file.
- I have to type in the word "private" in the online resource to find it


How I would like it to work:
- Having a checkbox "Publish Active Work: [ ] as Private"
  - Show the "Private" Upload option and Resource Tab only on activated setting "Private Uploads" in GTuner Preferences. A hint somewhere is required for finding them in GTuner Air with login required + search for "private" until implemented more directly somehow.
  - Using the checkbox will append "_private" or "_prv" or whatever to the filename for being able to reuse the filename for the private use and set the author to "Private" automatically.
  
- The Online Resource showing a tab "Private" by default. Clicking on it will show the results filtered to "Private".  
  - [optionaly prefered] Show the "Private" tab & Upload option only on activated setting "Private Uploads" in Preferences
  - Show the information of having to type in "private" in the search  in gtuner air to have access to these upload
  - On no match found one could show some basic information what it is/can be used for.
  - Show the "Private" tab only when one has an existing "Private" upload
  - Show the "Private" tab only on existing  Gtuner.cfg  [Advanced] entry: `private=True`

**Comment by Scachi** [comment]
Are you aware of my last comment ?
I am not sure if you prefer a discussion first at the forum or if I should open a new issue with this improvement request.

Forget the script file renaming thing, I can handle it myself.

Minimized to this it would be a very cool, userfriendly and fully integrated feature:
Add an "Upload as Private" checkbox (that puts in the "Private" author name automatically) to the Publish Wizard and a "Private" tab in the Online Resource 
when "Private Uploads" checkbox is enabled in the Preferences. That checkbox could be added to the "ConsoleTuner" entry as the login is required for this feature to be usable.

To minimize it more forget the "Private tab" in the Online Resource and add the information to search for "private" to the checkbox in the Consoletuner setting, mockup:
![private_publishing_mockup](https://user-images.githubusercontent.com/22262242/65258997-3827df00-db04-11e9-9b97-7ea855a0b45c.jpg)

**Comment by J2Kbr** [comment]
Forgot to reopen, thank you for remind me about this.

**Comment by J2Kbr** [comment]
Hi Sachi. I've been debating with myself about the Private publishing. The reasons some users would like make a work private are completely understandable. However, I am afraid that add an option to default all published works to private would decrease the amount of public/downloadable contents. Gtuner IV, from conception, was built around the idea of create and sharing and -I believe- this is one of the main motivations that brings new users to the Titan community. Hope for you understanding. Thanks.

**Comment by Scachi** [comment]
Yeah, its alright. I understand that. Thank you for the feedback.
