### ISSUE TITLE
Feature Request: Analog Stick Adjustment in Input Translator

### ISSUE THREAD

**Issue by kid4life79** [J2Kbr/GtunerIV#332]
If it's possible, a way to edit both analog sticks' deadzone and curve settings. A must for new custom controllers that are being released where stick tension can be set.

**Comment by J2Kbr** [comment]
The main purpose of Input Translators for gamepads is customize the input mappings. Advanced operations such as the ones you listed can be performed via GPC script. The GPC scripting language offers a full set of math/trigonometric functions that can be used to adjust deadzone and/or response curve of analog sticks.

**Comment by kid4life79** [comment]
Sorry, I posted more of the details on the Community Forum and left out that I understood you could use a GPC. When I posted this you couldn't use the GPC and a Gamepack together and you can use the Input Translator and the Gamepack together. I don't know if the new beta of Guner IV offers a solution, I know you closed a lot of the threads? My current work around is to use a T1 with an analog stick script and then a Game pack on the T2 but I would rather use one device than depend on both.
