### ISSUE TITLE
Bug: Using "External Tools" from the "GPC Script IDE" without script -> Crash

### ISSUE THREAD

**Issue by Scachi** [J2Kbr/GtunerIV#333]
Thank you so much for the External Tools.
I have found a bug. Calling the external tools from the GPC Script IDE panel without having any script opened will crash GTuner IV.
I am using it to open my IC-Bytetable program. https://github.com/J2Kbr/GtunerIV/issues/321#issuecomment-524885932 No idea if my program is causing this ?

**Comment by J2Kbr** [comment]
Can you see in the output panel the full command execution before crash? To check if it is correct or not. With no file opened, $CURR_FILE$ is a empty string.

**Comment by J2Kbr** [comment]
Also, try pass a dummy argument  along the empty $CURR_FILE$ to check if still crashes.

`"$CURR_FILE$" -dummy`

**Comment by J2Kbr** [comment]
Fixed, releasing a revision right now.
