### ISSUE TITLE
Issue with automatic fold

### ISSUE THREAD

**Issue by Scachi** [J2Kbr/GtunerIV#334]
I really like the automatic fold feature and already make use of it. https://github.com/J2Kbr/GtunerIV/issues/319

One issue that may need some improvement if possible is when trying to fold a commented block inside of a function.
Right now it does seem to do some nasty nesting folding. Unfolding the content isn't easy too.

Example code:
```
// foldinator
void SomeFunction(uint8 mode) { 

	printf("example only");
	
/*^ combobox values item list
	item	0	= Do Nothing
	item	1	= Slot 0
	item	2	= Slot 1
	item	3	= Slot 2
	item	4	= Slot 3
*/	
	
	printf("example only");
	
}
```

After opening the script it folds the commented block but also the rest of the function.
This is what it looks like:
![grafik](https://user-images.githubusercontent.com/22262242/63802526-2000dd80-c913-11e9-8352-a0f09d431d05.png)

Pressing the unfold of the commented block will unfold the block, still hiding the rest of the function that wasn't supposed to be folded.
![grafik](https://user-images.githubusercontent.com/22262242/63802567-3149ea00-c913-11e9-91bf-ad42c8df46cd.png)

I have to click fold & unfold on the function to show all content again.
![grafik](https://user-images.githubusercontent.com/22262242/63802589-3e66d900-c913-11e9-9e2f-72961e6c870f.png)

**Comment by J2Kbr** [comment]
Issue fixed on Gtuner IV 1.05, thank you for reporting.
