### ISSUE TITLE
GTuner IV 1.5.3.0 : Interactive Configuration - IC is getting strechted now 

### ISSUE THREAD

**Issue by Scachi** [J2Kbr/GtunerIV#335]
Was it doing this before too ? 
It looks a bit strange now for short ICs:

![grafik](https://user-images.githubusercontent.com/22262242/64469291-8bc32180-d12f-11e9-945e-962803d51d89.png)

**Comment by J2Kbr** [comment]
Issue fixed on Gtuner IV 1.05 revision 1
