### ISSUE TITLE
Invalid Link: Gtuner->Help->Gtuner Documentation 

### ISSUE THREAD

**Issue by Scachi** [J2Kbr/GtunerIV#336]
Gtuner Documentation points to non existent wiki topic
https://www.consoletuner.com/wiki/index.php?id=t2:gtuner_iv_software
The page name is "gtuner_iv" without suffic "_software"
https://www.consoletuner.com/wiki/index.php?id=t2:gtuner_iv

**Comment by J2Kbr** [comment]
Fixed on Gtuner IV 1.05 revision 1. Thank you for reporting this broken link.
