### ISSUE TITLE
File Explorer doesn't refresh the target directory when copying a file via dragndrop

### ISSUE THREAD

**Issue by Scachi** [J2Kbr/GtunerIV#337]
When copying a fie to an empty directory via drag n drop in the GTuner IV File Explorer it doesn't refresh the content of the target directory.
I have to hit the fresh button but that collapses the whole structure and I have to reopen it to the state before.

Is it possible to do an automatic refresh of the drop directory ?
Or on press of the refresh button store the current flag (collapsed or not) and restore it then so it keeps the same directory expanded as they were before hitting the button.

**Comment by J2Kbr** [comment]
After researching, this seems related with a open bug for QFileSystemModel (not updating files) from the Qt framework. I am afraid we will need wait the fix from the Qt framework in order to get this solved on Gtuner IV.
