### ISSUE TITLE
Automatically toggle to "Device Memory Slots" when you plug in the T2

### ISSUE THREAD

**Issue by PablosScripts** [J2Kbr/GtunerIV#34]
I've had the "Device Configuration" tab open and a few times I've plugged it in and not seen the slots appear, and proceeded to disconnect / reconnect the T2 thinking it was a faulty connection. I only then realized I needed to manually switch back to the "Device Memory Slot" tab. It's silly I know, but a small usability improvement that might help some people.

**Comment by J2Kbr** [comment]
The selected UI panes are saved and restored between sessions. If you have the "Device Memory Slot", it will be the one shown when plugging the device, instead of "Device Configuration".
