### ISSUE TITLE
2x GTuner IV using KMG Capture with 2x T2 on Switch - only one T2 works

### ISSUE THREAD

**Issue by Scachi** [J2Kbr/GtunerIV#340]
Looks like there is a problem with using
2x GTuner IV with KMG Capture with 2x T2 on Switch.
As soon as the second one gets connetced the first one stops working on the Switch.
Reported by CTK :
https://www.consoletuner.com/forum/viewtopic.php?f=25&t=13501&p=89452#p89099

Hist latest post https://www.consoletuner.com/forum/viewtopic.php?f=25&t=13501&p=89452#p89452

Picture from his latest post:
![grafik](https://user-images.githubusercontent.com/22262242/64558311-d74e1900-d343-11e9-883e-f1189f7509b3.png)

**Comment by J2Kbr** [comment]
Moved to Titan Two firmware issues: https://github.com/J2Kbr/TitanTwo/issues/234
