### ISSUE TITLE
Feature Request : Option to disable the F6/Assembly hotkey or disable it by default

### ISSUE THREAD

**Issue by Scachi** [J2Kbr/GtunerIV#342]
I think the only one using the .gps files are the more experienced persons / devs.
I often hit the F6/Assembly key by mistake when I want to hit F5, generating that file and having to delete it again.

It is fine when you don't want to make it optional. I will learn to better aim for the F5 key then ;-)

**Comment by J2Kbr** [comment]
On Gtuner IV 1.08 (yet to be released) you can add to gtuner.cfg file the following to disable this shortcut.
```
[Advanced]
assembly_shortcut=false
```
