### ISSUE TITLE
Online Resource : Improve display for <tags> like <ul>

### ISSUE THREAD

**Issue by Scachi** [J2Kbr/GtunerIV#345]
As an example:
Using a list I can't get a good loking result as it keeps to add a lot of spacing, looks almost like a linebreak. It happens with all kind of `<tags>`

You can download "USB HID GPad2KM" from the Online Resource to view the source file.
Example Code "USB HID GPad2KM_or.gph":

```
/*** Online Resource Info
<shortdesc>
USB-HID : Convert a PS4/Xbox gamepad to work as Mouse/Keyboard using Output Protocol 'USB Multi Interface HID'.
Features:<ul><li>Stick to Mouse movement mapping with optional alternative sensitivity (ADS)</li>
<li>Button to Mouse button mapping</li>
<li>Stick to Keyboard mapping (WSAD movement)</li>
<li>Button to Keyboard mapping</li>
<li>All mappings fully customizable via Interactive Configuration</li>
</ul>
</shortdesc>
<keywords>USB-HID, USB Multi Interface HID, Computer, Mouse, Keyboard, Gamepad on PC</keywords>
<docurl>https://www.consoletuner.com/forum/viewtopic.php?f=23&t=13612#p89885</docurl>
***/
```

Result:
![grafik](https://user-images.githubusercontent.com/22262242/65307055-35ba9900-db87-11e9-9261-ce330d31f394.png)

**Comment by J2Kbr** [comment]
You refer to the space between the _Features:_ and the first item of the list? this is the normal behavior for the `<ul>` tag. However, it can be changed if needed. In this case, the changes are applied on the server (no needed for Gtuner IV update).

**Comment by Scachi** [comment]
Yes, that is the space I am talking about.
I was thinking that this space was less on a regular browser but you are right, this is the default spacing on firefox too. I am closing this issue. Thank you.
