### ISSUE TITLE
GPC IDE Search : Escape regex when strg+f / search with code/text selected

### ISSUE THREAD

**Issue by Scachi** [J2Kbr/GtunerIV#346]
At the moment the text selected in the GPC IDE will be used 1:1 as the search.
When I select an array like "bLED[0]" it will fail to find it as it doesn't escape the special regex chars.

Can we get the search using text selected working always by escaping the regex chars in this case ?

**Comment by J2Kbr** [comment]
Fixed with solution suggested on #348 .
