### ISSUE TITLE
Feature Request: GPC IDE Search : Option to disable/enable use of regex

### ISSUE THREAD

**Issue by Scachi** [J2Kbr/GtunerIV#348]
I really like the regexp search but I think a more user friendly way would be to have it not enabled by default. 
It confuses people that don't know about regexp, wondering why they can't find what they are searching for.
https://www.consoletuner.com/forum/viewtopic.php?f=26&t=13728

in addition to https://github.com/J2Kbr/GtunerIV/issues/346

Adding a checkbox to the "Find options" for "[ ] use regexp" or "[ ] regular expression" or something like this would be nice for easier search usage and still have the power of using regexp when required.
Or  a checkbox in Preferences -> Script Editor to enable it.

**Comment by J2Kbr** [comment]
Gtuner IV 1.06 adds option to explicit enable regular expressions on find and replace.
