### ISSUE TITLE
Feature Request: config control

### ISSUE THREAD

**Issue by prototypeGtuner** [J2Kbr/GtunerIV#349]
The predefined config is a good feature but it's not possible to save a byte to an other. That would be useful to do something like that:

control = config
item = copy byte 01 to 02
item = copy byte 02 to 01

**Comment by J2Kbr** [comment]
Could you please give a scenario where this operation would be necessary? Thanks.

**Comment by prototypeGtuner** [comment]
If you have found a good value and want to save it to reload later while trying other values. If you want to overwrite the value with a previous one when testing.

**Comment by prototypeGtuner** [comment]
I have an other scenario where this operation would be useful. In my Modpack for Uncharted there is three options for the rapid fire and four options for the anti recoil for three weapons. A way to apply the same settings for all weapons would be nice to save some time.

**Comment by J2Kbr** [comment]
Operation COPY FROM INDEX added on Gtuner IV 1.08 (to be released soon).

Here is how this works:
`GIVICFG:#02@04` Copy value from position hex 04 to position hex 02
`GIVICFG:#02@101112` Copy values from positions hex 10, 11, 12 to positions hex 02, 03, 04
