### ISSUE TITLE
Add a "Refresh" option to the "Online Resources" page

### ISSUE THREAD

**Issue by PablosScripts** [J2Kbr/GtunerIV#35]
When I know someone has published something and I want to go and immediately check it, the only way to refresh right now is to change the "Order By" filter and then change it back again. A refresh button would be better, here's my quick mockup: 

https://i.imgur.com/RpUytwG.jpg

**Comment by J2Kbr** [comment]
Refresh button added on Gtuner IV 0.93 Beta
