### ISSUE TITLE
Gamepacks

### ISSUE THREAD

**Issue by houstonalx** [J2Kbr/GtunerIV#351]
My mods keep turning off and I’m not disabling them myself, when I found out how to re-enable them they don’t enable. So i don’t find out until a gun fight that my pistol isn’t using rapid fire. I have to unplug it so many times. Please fix this. I don’t like the runtime operations. If I wanted the mods off I would use number 0 or unplug.

**Comment by dontatmee** [comment]
> I have to unplug it so many times. Please fix this. I don’t like the runtime operations. If I wanted the mods off I would use number 0 or unplug.

This is not a GtunerIV Issue.

You should post your feedback/Issues on the forums in the appropriate section.
https://www.consoletuner.com/forum/viewforum.php?f=16
