### ISSUE TITLE
IC Preview Window gets reopened at a lower y position each time

### ISSUE THREAD

**Issue by Scachi** [J2Kbr/GtunerIV#353]
Using Win10pro x64, opening the IC Preview with F9, then closing it, and reopen it again, the window will get openend at a lower y position on the screen each time (looks like the title bar width), getting closing to the bottom of the screen each time.
I had the same issue with some of my own programs. Once it was caused by not having a QT object name set for a dialog, another time I had a "stay on top" feature implemented and I needed to set the reload position after applying the stay on top flag.

**Comment by J2Kbr** [comment]
The Qt framework for next Gtuner IV release was updated from version 5.12 to version 5.14 and, it seems, to have solved this issue. I will close, please comment if the problem persists after updating your Gtuner IV to 1.07. Thanks.
