### ISSUE TITLE
Suggestion - validation error if mixing HID vs. controller methods

### ISSUE THREAD

**Issue by PablosScripts** [J2Kbr/GtunerIV#354]
I was converting a PC script to a controller one. I missed one instance of mouse_status() and it took me ages to see it. I can't think of any scenario where you'd have the two (I think??) so it makes sense that if you see a mix of controller and HID methods the user could be alerted? 

This is an extremely rare use case though so I don't think it deserves a high priority.

**Comment by J2Kbr** [comment]
Hi Pablo, The use of `mouse_status()`, `key_status()` with regular controller functions (`set_val()`, `get_val()`, etc) are relatively common. I make use of those in most my personal script (play with mouse and PS Navigator). Many utilizes foot-switches and others keyboard/mouse based devices to assist the controller gameplay (in special with solution for disabled individuals).
