### ISSUE TITLE
Missing function error could be clearer

### ISSUE THREAD

**Issue by PablosScripts** [J2Kbr/GtunerIV#355]
I was missing a function and I received the following error saying "Identifier not declared". It took me a while to realise what was wrong, I'm wondering if could be made "Function not declared" or "Function missing" or something? Maybe "Identifier" makes sense in a general programming or Gtuner context so if this is the case feel free to just close this. 

![image](https://user-images.githubusercontent.com/22415147/73120090-f03b2c00-3fbd-11ea-8169-f3fd7c1ace0c.png)

**Comment by J2Kbr** [comment]
When the parser (second pass) first encounters an identifier, it consults the symbols table generated by the lexer (first pass) to obtain information about the identifier context (is it a variable? function? or combo?). If the identifier is not found in the symbols table, the parser shows the error message you posted above. It does not look ahead in the code to try infer what would possible be the type of the identifier before print the error message.

If your suggestion was just an error message change I would do without problem :). however, it is something more complex to implement.
