### ISSUE TITLE
Space missing between ".gpc" file extension and bracket (

### ISSUE THREAD

**Issue by PablosScripts** [J2Kbr/GtunerIV#356]
![warning](https://user-images.githubusercontent.com/22415147/73364958-8c876a80-42ff-11ea-9381-a40019804edd.PNG)

**Comment by J2Kbr** [comment]
This pattern `<filename>(<line>): <error>` was adopted at early stages of development. After taking a look if it would be possible add the space, I realize this pattern is used/expected in so many others parts of the code (preprocessor, stages 1 and 2 of compiler, assembler, output panel). I am afraid the attempt to change this will break the functionality on other parts of Gtuner IV. Hopefully you will understand. ;)
