### ISSUE TITLE
.py files Menu-File-Save / Save As not allowing .py file extension

### ISSUE THREAD

**Issue by Scachi** [J2Kbr/GtunerIV#358]
You probably have this already on your list, not sure if I should submit .py / vision scripting problems already or posting issues later only.

I can open the .py files fine and saving via hotkey ctrl+s seems to be working too,
but the Top Menu Dialog File->Save and "Save a Copy  As" isn't working as it only allows .gpc and .gph file extension.

**Comment by J2Kbr** [comment]
In the "Save as type" combobox of Save As Dialog window, select "GCV Script file (*.py)".

**Comment by Scachi** [comment]
Most (if not all) applications do pre-select the .extension according to the current opened file extension when doing a save as or save copy as. This is why I didn't thought about using the combobox in this case at all.
When I have a .py file openend and currently active in the GPC IDE pane I expect the save as/ save copy as dialog to have the .py extension already selected as the correct file type.
For a .gpc/.gph file the pre-selected one should be .gpc/.gph
Can you please add this functionality to make it as easy as possible for the user to use  ?

**Comment by J2Kbr** [comment]
Implemented auto select corresponding file type as suggested. Thank you.
