### ISSUE TITLE
Computer Vision: Export frame to image file x shift

### ISSUE THREAD

**Issue by Scachi** [J2Kbr/GtunerIV#359]
Doing a export with my "Pengo 4K HDMI Grabber"  result in an image not matching the preview/image shown in the Computer Vision pane.
The X-Axis seems to be off 88pixel 

Shown in GTuner: 
![image](https://user-images.githubusercontent.com/22262242/74593714-6c111d00-502e-11ea-9355-be8730843f8d.png)

Saved file:
![image](https://user-images.githubusercontent.com/22262242/74593716-7a5f3900-502e-11ea-9855-5fb7638e4157.png)

**Comment by dontatmee** [comment]
I noticed this issue too when trying all available resoulutions with my card https://www.consoletuner.com/forum/viewtopic.php?f=2&t=14717&start=50#p95418

**Comment by Scachi** [comment]
In Version  1.07 beta-10, 18-02-2020 it seems to working correct now for me.
No x-shift anymore.
![Primary Slot_acre](https://user-images.githubusercontent.com/22262242/74870210-a691f700-5359-11ea-9b9c-e752d7c1a9f9.png)

**Comment by J2Kbr** [comment]
Correct Scachi, This issue was fixed on 1.07B.
