### ISSUE TITLE
KMG Capture + Xbox Wireless adapter + Elite Series 2

### ISSUE THREAD

**Issue by J2Kbr** [J2Kbr/GtunerIV#361]
Moved from: https://github.com/J2Kbr/TitanTwo/issues/249

AJSinc commented on Dec 13, 2019
> Every time I try to connect my elite to my PC with the KMG capture box open and capturing, the controller will turn on for 2 seconds then turn off. If I close the KMG capture window the controller connects to the computer fine.

**Comment by J2Kbr** [comment]
Couldn't reproduce with Elite Serie 1. Googling about this issue encountered several similar reports. The suggestions goes from repair the controller with the Wireless Adapter and/or update the controller's firmware.

**Comment by twodice** [comment]
I have the same problem with the elite series 1, but it's reproducible. 

- Connect XB1 elite series 1 with wireless adapter
- Open Gtuner (1.8 beta)
(note: order of these two steps does not seem to matter
- Start KMG capture for gamepad/joystick for all gamepad/joystick
- Everything works fine
- Disconnect xbox controller by unplugging receiver, then reattach receiver
- Controller will connect and enumerate and appear to work fine until you press any button or move any stick - then it disconnects
- It won't remain connected until I stop KMG capture - if I reenable it then it will disconnect on the next button press
- This continues until Gtuner is restarted

This can be worked around by restarting Gtuner every time I plug the adapter in, but it's pretty weird. This behavior happens even if I disable KMG capture before removing the adapter - it doesn't have to be enabled to cause it to start disconnecting.

**Comment by twodice** [comment]
Interesting note: this doesn't happen if I also have a wired controller plugged in.

edit: If I have 2 controllers plugged in (one wired, one wireless via adapter), the triggers only work on one of them. All of the other buttons seem to work fine on both.

**Comment by J2Kbr** [comment]
Gtuner IV 1.08B-10 now monitors the captured devices connection and will automatic exit from capture mode if detected device disconnection.
