### ISSUE TITLE
Can't "save as" /"save a copy as" .py files

### ISSUE THREAD

**Issue by Scachi** [J2Kbr/GtunerIV#363]
The file extensions is correctly selected automatically but I can't save as or  a .py file:
```
Save As Error: Unable to save 'Fortnite_Test.py' as C:/Users/sc/Documents/T2/___T2_My_Stuff/Fortnite/ft1.py
```

another try to d: (where I have write access too): 
```
Save As Error: Unable to save 'Fortnite_Test.py' as D:/123.py
```
Saving it as .gph or .gpc works fine.

**Comment by J2Kbr** [comment]
Issue found, the fix will be available in the next beta revision release. Thank you
