### ISSUE TITLE
External tools, rewording suggestions

### ISSUE THREAD

**Issue by PablosScripts** [J2Kbr/GtunerIV#368]
Suggestions to tighten up some of the descriptions: 

"following the format" change to: "using the following format"

"examples" to "examples include" or "for example"

"Optional separator" to "An optional separator"

![image](https://user-images.githubusercontent.com/22415147/76942838-7d618800-6952-11ea-8c5f-fa51507a1491.png)

**Comment by J2Kbr** [comment]
Suggestions incorporated in the next Gtuner IV release. Thank you.
