### ISSUE TITLE
Error updating to the latest version of GTIV

### ISSUE THREAD

**Issue by PablosScripts** [J2Kbr/GtunerIV#369]
After getting this error I downloaded a new copy and it worked fine. However you should be aware that not all users may experience a successful upgrade. 

![image](https://user-images.githubusercontent.com/22415147/76943935-43918100-6954-11ea-8343-bd49a726f372.png)

**Comment by J2Kbr** [comment]
The 1.07 release has also updated the [Qt framework](https://www.qt.io/) which Gtuner IV is based on. This requires update basically all Gtuner installation and, in some circumstances, may fail due a bug in ‘Gupdater.exe’ helper application from previous version. This bug has also been fixed on 1.07. In case of error after the update procedure, the solution is redownload  Gtuner IV from the ConsoleTuner website:

https://www.consoletuner.com/titan-two-downloads/
