### ISSUE TITLE
Allow us to open hyperlinks from the Doc URL

### ISSUE THREAD

**Issue by PablosScripts** [J2Kbr/GtunerIV#37]
I just noticed this incredible feature, it's a good way to showcase what your script can do. But I'm unable to go to full screen view, or open it by clicking on the link. I think it would be really good to be able to do this. Here's what I'm referring to: 

https://i.imgur.com/02REUr0.png

**Comment by PablosScripts** [comment]
I notice you can click on the icon called "Doc". Since you can embed more than just Docs (a video in this case), maybe it should be renamed "More Info" or something like that?

**Comment by J2Kbr** [comment]
The purpose of "Doc URL" is provide an hyperlink to an documentation page (or info page) for the script. The link can be accessed by the icon "DOC" in the script list. As you mentioned, this field also provides other features, but those are for restrict use.
