### ISSUE TITLE
Compiler Error Using "goto"

### ISSUE THREAD

**Issue by CrispyPixels** [J2Kbr/GtunerIV#371]
```
main
{
	goto EndOfMain;
	
	EndOfMain:
	
}
```
Will fail to compile returning "GPC error: test.gpc(7): syntax error, unexpected B_E '}'."
```
main
{
	goto EndOfMain;
	
	EndOfMain:
	0;
}
```
Placing any instruction after the label will let the program compile successfully.

**Comment by J2Kbr** [comment]
In the GPC script language (as well as in C/C++) is required labels belong to a statement, therefore a simple semicolon `;` after your label can circumvent the problem you are running in to, since that counts as a statement.

Example:
```
main {
	goto EndOfMain;
	//
        // script code here
        //
	EndOfMain:;
}
```
