### ISSUE TITLE
Feature Request: Port or Device as part of conditional for scripting

### ISSUE THREAD

**Issue by 01BinaryDigit** [J2Kbr/GtunerIV#372]
Not sure if this is something others may want, but with the ability of having multiple different input devices connected at the same time for the T2, I found myself wanting to do a conditional check of which Port or Input device is sending an input.

As of right now it seems that checking for inputs (button presses, analog stick movements, accel or gyro) results in checking a "virtual" controller that all input devices write to, without being able to identify what device is sending an input or even which port it is being sent from.

Would it be possible to extend this to be able to check what device is sending an input?

This would have the additional benefit of expanding the API and enchancing flexibility, while also being able to have combos, conditionals and other code-based operations only take affect when initiated by a specific input device.

This could be extended on the "get_actual" method and check the sending port
E.G.
`if(get_actual(PORT_BT_A, BUTTON_5) >= 75.5) {
        set_val(BUTTON_5, 100.0);
}`

Or could be separate function that can be used separately
E.G.
`if(get_input(PROTOCOL_XB1) {
    if (get_actual(BUTTON_5) >= 75.5) {
        set_val(BUTTON_5, 100.0);
    }
}`

**Comment by dontatmee** [comment]
This issue/request was brought up on the forums, a while back. 

https://www.consoletuner.com/forum/viewtopic.php?f=27&t=9046&p=65290&#p65359
> **_J2kBr wrote:_**
this is not currently possible. the inputs from controllers are accessible only after the merging and normalization process.
>
> what I have in mind to implement is the ability to read the HID reports from connected controllers based on the input port, allowing what you are asking. Something similar to what we have for keyboard and mouse with key_status and mouse_status.

**Comment by 01BinaryDigit** [comment]
I did a quick search but couldn't find the thread you linked.  That is exactly what I was looking for and hoping to be implemented, too!  Big thanks for linking it to me.

Would it be prefered that I close this?  Or left for the owner to tag and close, or for tracking updates on this sort of feature that is stated to be on its way?

**Comment by dontatmee** [comment]
Keep it open.

As that post on the forums is almost 2 years old.

**Comment by J2Kbr** [comment]
Feature implemented on Gtuner IV and Titan Two firmware versions 1.08 (to be released soon).

Added new GPC function `get_port()` to retrieve the port which originated the normalized input value.

Example:
```
main {
    // If BUTTON_16 is active ...
    if(get_actual(BUTTON_16)) {
        // and if the value is comming from USB-B ...
        if(get_port(BUTTON_16) == PORT_USB_B) {
            // don't forward the input to the console.
            set_val(BUTTON_16, 0.0);
        }
    } 
}
```
