### ISSUE TITLE
Suggestion for basic API

### ISSUE THREAD

**Issue by NeoTechni** [J2Kbr/GtunerIV#373]
If you subclass the window to listen for Windows events, you can make it extremely easy for us to send inputs to the program to send to the console. All we'd have to do is ask Windows for the hWnd of the main window, and send messages to it.

In particular, I'd like this so I can make a program to automatically recreate patterns for Animal Crossing on Switch, by sending a lot of button presses

**Comment by dontatmee** [comment]
This should already be possible using the KMG Capture tool in GtunerIV.

Just have your app send virtual keystrokes, and then with the KMG capture tool, these keys will be sent directly to the T2. 

Listen for keys from inside your gpc scripts by using the key_status() function,

**Comment by dontatmee** [comment]
If you're trying to communicate the other way. T2 To PC. You can utilize the built-in python compiler/Computer Vision.

look for this script in the online resources https://www.consoletuner.com/greslib/?w982 to get an idea of how it works,

**Comment by J2Kbr** [comment]
Thank you _dontatmee_ for pointing out two possible solutions for this request.
