### ISSUE TITLE
gTuner IDE locks file for editing

### ISSUE THREAD

**Issue by kmcnaught** [J2Kbr/GtunerIV#375]
If a script file is open in gTuner, it is locked for editing to all other applications. This is not usual behaviour for a text editor, and makes version control workflows much harder. For instance, I use git to version control my scripts, and I'll regularly want to stash my changes or revert to an earlier version, and I always have to close and reopen script files before doing so. It would be really useful if the file wasn't always locked and was able to be updated with changes from elsewhere.

**Comment by J2Kbr** [comment]
Thank you for posting a suggestion. Gtuner IV does not intentionally locks access to the file. However, while opened in the editor, the file handle is kept opened for performance reasons.

By right-clicking the tabbar, is possible reload the file contents in case was changed from another application.
![reload](https://user-images.githubusercontent.com/21229433/80288123-29de1900-870c-11ea-8f85-7d5e7eda7fe7.png)

**Comment by kmcnaught** [comment]
Thanks for your reply. The problem is that I am unable to make changes in any other applications while the file is open in gTuner. If I try to edit and save changes in Notepad or Sublime Text 2, I get the error "`The process cannot access the file because it is being used by another process`". If I make changes via git, I get the error "`Unlink of file 'ConsoleController.gpc' failed. Should I try again? (y/n)`". I assume this is because the file handle is kept open, and also therefore you are never going to be in a position to be able to reload any changes. 

I'm using Windows 10 (10.0.18362 Build 18362).

**Comment by J2Kbr** [comment]
Understood, I will check what can be done.

**Comment by Scachi** [comment]
I have the same issue. I am running winmerge often to check for changes between older script version (where I can't remember what I have changed) and I need to close them in GTuner IV to be able to run winmerge on those files then.
My ic-bytetable app run fine on opened files in GTuner IV, but my app is just using read mode for those files.

**Comment by J2Kbr** [comment]
With Gtuner 1.08B revision 2 the file handle of opened files are kept closed, so other applications can have write access.
