### ISSUE TITLE
Interactive Configuration: display of ul li tags adds extra lines

### ISSUE THREAD

**Issue by Scachi** [J2Kbr/GtunerIV#376]
Example:
```
<ul>
  <li>Coffee</li>
  <li>Tea</li>
  <li>Milk</li>
</ul>
```
I would expect this: ( from https://www.w3schools.com/tags/tag_ul.asp )
![image](https://user-images.githubusercontent.com/22262242/80423925-13d58180-88e1-11ea-9f35-a843a0ce3a3e.png)

But I get this:  (from my IC, same code used as above)
![image](https://user-images.githubusercontent.com/22262242/80423999-2c459c00-88e1-11ea-955a-929254d85ebc.png)

Can this be fixed / improved ?
ul (opening or closing arg) may add a linebreak already, nested lists are having this issue in every line.
```
<ul>
    <li>File: z__default.git</li>
    <ul>
        <li> HIP + ADS : the mouse xy movement (default for hip, alternate for ads)</li>
        <li> HIP : mouse mapping</li>
        <li> HIP : keyboard mapping</li>
    </ul>
    <li>File: z_ads.git</li>
    <ul>
    <li> ADS : mouse mapping</li>
    <li> ADS : keyboard mapping</li>
    </ul>
</ul>
```

![image](https://user-images.githubusercontent.com/22262242/80424278-ad9d2e80-88e1-11ea-8b7b-50a763e0a215.png)

The current implementation of automatically adding line breaks works fine for a lot of IC stuff, but it is messing up quite a bit for tables and similar html tags.
Maybe it is possible to add a check for 'html' tag in a multiline shodrtdesc entry to disable that automatic handling by the user, that new line insert it driving me crazy almost every script.

```
<html>
some multi line section 
in here 
where no automatic linebreaks are done at all
</html>
```
so the above will appear as a single line then in that case. This way I can use all supported html tags without having to care about what gtuner does and what I expect from normal html tags.
Or add a "htmlshortdesc" tag, or add some flag for the IC creator to use to disable auto linebreaks for the whole IC shortdesc entries if this is easier.
Or something like:

```
htmldesc      = <<<MULTILINE
no auto linebreak within this section
MULTILINE

```

**Comment by J2Kbr** [comment]
Hi Scachi. I believe to have fixed the issue, here is the result with your example code above:
![image](https://user-images.githubusercontent.com/21229433/96166361-43f6f800-0ef4-11eb-892c-506488e5a5e3.png)
Will be available on Gtuner 1.08B-10. If after the update you still encounter problems, we then create the special `htmldesc` config key.
