### ISSUE TITLE
GPC Script IDE: Automatic remove unreferenced/unused symbols

### ISSUE THREAD

**Issue by Scachi** [J2Kbr/GtunerIV#377]
Thank you for your hard work !

Added as a reminder, according to your forum post, you are planning to do this already:
https://www.consoletuner.com/forum/viewtopic.php?f=2&t=15250&p=98347#p98322

Forum Post:
Is it possible to free up parts that I don't need to save scriptsize ?
For example here I am using 4 files but only use specific parts of them:
```
#import "z__default.git"   //mm_hip        kmap_hip        mxyc_hip (default) mxyc_ads (alternate)
#import "z_ads.git"        //mm_ads        kmap_ads
#import "z_inventory.git"  //mm_inventory  kmap_inventory
#import "z_softaim.git"    //mm_softaim    kmap_softaim
```

Compiling it give me this:
`GPC: Unreferenced: z__default_cmap, z_ads_cmap, z_ads_mxyc, z_inventory_cmap, z_inventory_mxyc, z_softaim_cmap, z_softaim_mxyc
`
Can they be automatically removed when a script isn't using them to free up script space ?

**Comment by J2Kbr** [comment]
Gtuner IV 1.08B-2 implements garbage collection of unused constant variables, functions and combos.
