### ISSUE TITLE
KMG capture does not work when connected via Windows Remote Desktop

### ISSUE THREAD

**Issue by twodice** [J2Kbr/GtunerIV#382]
Works fine (other than the [other issue](https://github.com/J2Kbr/GtunerIV/issues/361)) when running locally, but if I connect over remote desktop it can't find the controller and selecting all controllers doesn't read any input.

**Comment by J2Kbr** [comment]
Please follow the guide linked below to use gamepads over remove connection with Windows Remote Desktop.

https://www.gavpugh.com/2018/10/03/using-game-controllers-over-a-remote-desktop-session/
