### ISSUE TITLE
GTuner Text2Speech language selection

### ISSUE THREAD

**Issue by Scachi** [J2Kbr/GtunerIV#383]
Is it possible to set the language the text2speech feature, printf("SPEECH:.."); , uses ?
My Win 10 System language is german and it sounds like the speeach system is trying to use german language for the speech instead of the language set within GTuner IV [EN] "English".
Most scripts do use english language and with german speech output most words do sound horrible.

**Comment by prototypeGtuner** [comment]
+1 same for me. It speaks english words with a french accent. Like me lol, not good !

**Comment by J2Kbr** [comment]
Gtuner IV 1.08B-10 explicit sets English language for TextToSpeech, instead of use the system default language.
