### ISSUE TITLE
Issue with copy from index 

### ISSUE THREAD

**Issue by prototypeGtuner** [J2Kbr/GtunerIV#384]
I like to use this feature and it works well with Gtuner IV but it doesn't work with Gtuner Air for me.

Here is how i do:

#0C@0607#0E@0809 #12@0607#14@0809 #18@0607#1A@0809 #1E@0607#20@0809...

**Comment by prototypeGtuner** [comment]
Maybe it's because my Gtuner Air is not up to date, idk which version that i have but it's not the last because i'm not able to update. Maybe i should uninstall before install but IF i uninstall i'm afraid to not being able to reinstall the previous...

Maybe i should have posted this thread in the Gtuner Air section.

**Comment by J2Kbr** [comment]
You are correct in the assumption. I've already implemented this feature on Gtuner Air. However, it was not yet released. It is expected new release of Gtuner Air go live as soon as Gtuner IV 1.08 is released.
