### ISSUE TITLE
GTuner IV Beta 1.8.1.6 - Input Translator - F1 dblclick to combobox value not working

### ISSUE THREAD

**Issue by Scachi** [J2Kbr/GtunerIV#385]
I like the feature of the beta where I can select the console specific buttons names in the input translator.

The issue with using that is the F1 button list isn't setting the combobox values anymore on double clicking on a list entry.
Setting it to the default "GPC Designators" the list double click to combobo value is working correctly.

![image](https://user-images.githubusercontent.com/22262242/90107833-b8bd8280-dd49-11ea-9a81-c4cce2a48eb7.png)

**Comment by J2Kbr** [comment]
F1 double-click selection now also works with console specific combo-boxes (Gtuner IV 1.08B-10).
