### ISSUE TITLE
old laptop, forcing -gl-angle or -gl-software to start gtuner = black online resource ?

### ISSUE THREAD

**Issue by Scachi** [J2Kbr/GtunerIV#386]
I know that the online resource not showing up is caused often by a firewall or security software/setting.
In this case I have disable the firewall, no other security software is installed/enabled.

GTuner IV (current stable) refuses to start up, using the command line arguments  -gl-angle or -gl-software gtuner IV start, but the Online Resource window stays black
and on startup of gtuner the output panel still mentions "libgles"

is it possible that gtuner still tries to use opengl for rendering the online resource ?

**Comment by J2Kbr** [comment]
The Online Resources depends on an external process (QtWebEngineProcess.exe located at lib sub-directory).

Starting from Gtuner IV 1.08B-10, forcing the OpenGL engine via command line also sets an environment variable to inform the QtWebEngineProcess to use the same OpenGL engine.
