### ISSUE TITLE
Computer Vision : Starting a script always returns the same script name in the stopped message

### ISSUE THREAD

**Issue by Scachi** [J2Kbr/GtunerIV#389]
When I run a cv script "123test456" and start the script "Video Input Check" 
via command `printf("GCMD:ComputerVision.Start:Video Input Check");`

The output panels always write the scripts name that is about to be started as the one that is stopped and not the real one running at the moment:
```
Computer Vision: GCV script 'Video Input Check' stopped
Computer Vision: GCV script 'Video Input Check' running
```
GTuner Beta 1.8.1.9

**Comment by J2Kbr** [comment]
Fixed on Gtuner 1.08B-10. Thank you for reporting.
