### ISSUE TITLE
GTuner doesnt open .gpc files when double clicked

### ISSUE THREAD

**Issue by T3ap0T** [J2Kbr/GtunerIV#390]
[[ I have .gpc filetype to open with GTuner
[[ When I double click a .gpc file a new instance of GTuner gets launched without the file opened but previous files re still cached in the IDE
]] Im assuming an argument isnt getting passed
[ I had no problem with this before the latest update. ]

**Comment by J2Kbr** [comment]
Feature added to Gtuner IV 1.08B-10.
`Check the command line arguments at startup and open all compatible files found.`
