### ISSUE TITLE
Gtuner shows OpenCV Python module not found when using CUDA opencv

### ISSUE THREAD

**Issue by InputSense** [J2Kbr/GtunerIV#391]
Gtuner looks in the site-packages\cv2 folder for the module cv2.cp38-win_amd64. When building CUDA OpenCV,  cv2.cp38-win_amd64 is placed into the site-packages folder directly. Scripts still import the module just fine, but gtuner shows not found when checking the preferences>Computer Vision tab. The fix is to create a folder called cv2 and copy/paste cv2.cp38-win_amd64 into it. 

This is purely a visual bug since gtuner scripts still import the original cv2 module from site-packages.

**Comment by J2Kbr** [comment]
Starting from Gtuner IV 1.08B-10, if the sub-directory "cv2" does not exists, try find the CV module in the "site-packages" directory.
