### ISSUE TITLE
GTuner File Explorer : Option to show all files

### ISSUE THREAD

**Issue by Scachi** [J2Kbr/GtunerIV#392]
Hi,

as with the computer vision there is now access to more files than just .gpc and .py
I really would like to be able to see all files in the directories.. like the template .png files a cv script uses and more... not only .gpc .gbc .py

GTuner IV doesn't need to be able to open all file types, maybe show them greyed out when gtuner itself doesn't know them or let them use the windows/os default file handling take over for those files,

**Comment by J2Kbr** [comment]
Option to show all files added to Gtuner IV 1.08B-10. Incompatible files are grayed out.
