### ISSUE TITLE
Buffer size/line count of "Output Panel"

### ISSUE THREAD

**Issue by Scachi** [J2Kbr/GtunerIV#397]
What is the current limiting factor for the scroll back buffer ?
is there any way to increase the lines the Output Panel is able to scroll back ?
Like an advanced .cfg file entries or something like that ?

**Comment by J2Kbr** [comment]
On next Gtuner IV release, the Output Panel maximum number of rows can be customized via config file: "Gtuner.cfg"

Under `[Environment]`, add the line:
`outputpanel_maxrows=256`

256 is the default value, you can change to any value you want. Please note too much rows can potentially slow down the output panel.
