### ISSUE TITLE
MacOS | Gtuner IV doesn't properly request camera permissions

### ISSUE THREAD

**Issue by misterpyrrhuloxia** [J2Kbr/GtunerIV#399]
EDIT:
I've changed the title of this issue to report an _actual_ bug with Gtuner IV, i.e. Gtuner doesn't properly request camera permissions from MacOS.

I've put my original issue in a quote block below. Following that is more detail on the Gtuner bug that led to my problem as well as my workaround for the meantime.

> Forum post:  https://www.consoletuner.com/forum/viewtopic.php?f=25&t=17393&p=108777#p108777
> 
> My setup:
> 
> Gtuner IV:  1.10.3.1
> Titan Two:  1.10.3.1
> MacBook Pro (Retina, 15-inch, Mid 2015)
> MacOS 11.1 Big Sur
> 2.8 GHz Quad-Core Intel Core i7
> 16 GB ram
> 
> T2 > OUT > PC
> T2 > PROG > Macbook Pro
> PC GPU > HDMI 2.0 cable > AverMedia Live Gamer Ultra capture card > USB 3.1 C to A cable > MacBook Pro
> PC GPU > DisplayPort cable > gaming monitor
> 
> I am trying to set up my MacBook Pro to do Gtuner CV capture. In Windows, the capture card is recognized as a second display. I can duplicate my display and I can extend it. While it's set to extended, I even set the capture card to output in 1920x1080@60Hz. Regardless of whether Windows is set to duplicate display or extend it, and regardless of what resolution I set Windows to output the capture card to while it's in extended mode, Gtuner completely crashes the moment I click on 'Detect Devices' in the Gtuner CV video input config options. It should be noted that no matter which configuration I set Windows to, OBS on my Macbook can detect and use the capture card perfectly.

---

@J2Kbr found in a Gtuner crashlog file that I sent him that Gtuner doesn't properly request camera permissions from the OS, which leads to MacOS terminating Gtuner when you try to hit `Detect Devices` in CV. In the meantime, I'm using a hackjob workaround to at least get Gtuner temporary camera permissions. I do this by launching Gtuner from the terminal with this command:
```bash
/Applications/GtunerIV.app/Contents/MacOS/Gtuner
```

Then when I hit Detect Devices, Gtuner properly requested camera permissions- except it was the terminal requesting the permissions from the OS, not Gtuner. But after granting the permissions, my capture card is detected. The annoying thing is that I have to run Gtuner from the terminal every single time. In addition to that, I have to hit Detect Devices again each time I run Gtuner.

Please update Gtuner to properly request camera permissions from MacOS.

**Comment by misterpyrrhuloxia** [comment]
Workaround found. Documented here:  https://www.consoletuner.com/forum/viewtopic.php?f=25&t=17393&p=108777#p108777

**Comment by misterpyrrhuloxia** [comment]
I've updated this issue description and title to reflect the bug that needs to be addressed to fix the underlying problem I was experiencing.

**Comment by J2Kbr** [comment]
Feature implemented, to be released on next Gtuner IV update. Thanks.
