### ISSUE TITLE
pmem_load(); Blocking Slots From Loading

### ISSUE THREAD

**Issue by MMachor** [J2Kbr/GtunerIV#4]
pmem_load(); in the init block is stopping scripts from loading.  The script will compile fine, but when loaded to a slot on the Titan Two it will not allow that slot to be accessed.  A few people were having issues loading scripts and I've narrowed it down to this so far.  Script loaded fine with everything else, but when that single line was added the slot was no longer available.

**Comment by J2Kbr** [comment]
The firmware programmed at the factory, shipped to the beta users, does not have implemented the pmem_\* functions, causing the device to abort the script execution. This will be fixed with the release of a updated beta firmware.
