### ISSUE TITLE
KMG Capture - KMG capturing and playing on the same pc with USB HID protocol using mouse & keyboard

### ISSUE THREAD

**Issue by Scachi** [J2Kbr/GtunerIV#402]
Issue: When using KMG capturing on the same PC for playing PC games via USB HID script on that PC running GTuner IV itself it looks like the mouse output of the T2 gets read by the T2 again messing up the mouse controls when using a simple passthru script like this in combination with the autohotkey posted at the forum to start kmg capture without loosing focus of the current game:
```
init{
  mousemapping(); // clears defaultt T2 mouse mappings
  keymapping(); // clears default T2 keyboard mappings
}
main{
  mouse_passthru(); // forward mouse input to output
  key_passthru(); // forward keyboard input to output
}
```
forum ahk script: https://www.consoletuner.com/forum/viewtopic.php?f=25&t=15568&p=100145

Using this with output connected to the same PC the mouse is doing "ghost movements" in the direction of the last input

No idea if this is possible or if this is the cause of the problem at all ...
 is it possible to not refeed the T2 mouse output back into the T2, filter that mouse output out ?

Is it possible at all to use kmg capture on the same pc with usb hid somehow without the game reading all inputs, so the game just gets the output of the T2 ?

This is the forum post about the issue: https://www.consoletuner.com/forum/viewtopic.php?f=23&t=9889&start=60#p108816

**Comment by J2Kbr** [comment]
On the next Gtuner IV release, the KMG Capture filters (ignore) the Titan Two Multi HID Interface output (mouse, keyboard and joystick).
