### ISSUE TITLE
Cannot execute more than one CV instance

### ISSUE THREAD

**Issue by scw000000** [J2Kbr/GtunerIV#404]
I have two titan2s, two video capture cards, and two consoles, and I cannot make both of them running CV on the same machine.

what happens when I try to run 2nd cv is that it will make the first one stop, and both instances will display the same screen

I tried with different combinations, such as video capture device + video capture device, video capture device + window capture (through OBS preview), don't have any luck so far

**Comment by J2Kbr** [comment]
Request implemented. The next Gtuner IV release now allows each instance to capture a distinct video input.
