### ISSUE TITLE
Keyboard and mouse capture no longer works

### ISSUE THREAD

**Issue by thatmodelguy** [J2Kbr/GtunerIV#410]
after the latest update 4/2/2021 the keyboard and mouse capture no longer functions. When capture mode is pressed it is no longer sending reports to the device and refuses to exit out of capture mode

**Comment by J2Kbr** [comment]
Please let me know if you have the device configured to "USB Multi HID interface" and with the output connected to the PC where Gtuner + KMG Capture is running. 

I ask because the last update added a filter for "USB Multi HID interface" inputs (from the Titan Two) to the KMG Capture, meaning the keyboard/mouse/joystick inputs generated by the Titan Two are ignored by KMG Capture. This change was made to avoid inputs loopback while using KMG Capture.

**Comment by thatmodelguy** [comment]
Device is connected to the computer running gtuner. I changed it over from PlayStation 4 to USB Multi HID interface and am still getting the same result. Below it shows one packet sent for about a second and then go straight to zero and stop sending them.

Edit: I have the PC program micro USB running to the computer and the output running to the PlayStation. I assume the output you are talking about would be the PC program port and not the output that runs to the console? I'm running it like I always do when I use the capture software.

**Comment by thatmodelguy** [comment]
After doing a little more testing I think I figured out what's going on. My physical mouse and keyboard are being recognized but whatever changed in the update makes it so it no longer recognizes my smartnav mouse I normally use and my macro program glovepie which I use for pressing keys. Somebody else reported this on the forums but not sure if they're using a similar setup is me or if their physical mouse and keyboard is still affected. Is there a setting I should be using to get it to recognize my equipment besides this? Otherwise I wouldn't be able to use this device anymore. gtuner 1v 1.7.3.1 still allowed mouse capture to function even though it had issues with speech recognition. Is there a place to still download this version until things get resolved?

edit:I forgot to mention the only way the hardwired mouse and keyboard worked when using capture was setting output protocol to PlayStation five or PlayStation four controller. USB multi-HID interface wasn't responding at all.

**Comment by J2Kbr** [comment]
Hi, I believe to have found and fixed the issue. A new Gtuner IV update will be released today. Thanks.

**Comment by thatmodelguy** [comment]
I tested it out just now and it working for me and seems to be back to normal. Thank you much! It still having issues with speech recognition but I wrote up a report about that on the other post to keep it organized.
