### ISSUE TITLE
Gtuner causing conflict with speech recognition

### ISSUE THREAD

**Issue by thatmodelguy** [J2Kbr/GtunerIV#411]
while using Windows speech recognition to navigate G tuner it causes severe delay in speech recognition response and eventually causes it to stop responding altogether. After entering into capture mode with keyboard and mouse capture and then exiting it causes speech recognition to turn off. If the Titan 2 device is unplugged or unselected from the top right corner of the program the program seems to run fine until the Titan device is reconnected and then the problem persists.Not a big problem for the average user but for disabled users it makes things quite difficult

**Comment by J2Kbr** [comment]
This issue possible is related with #410. Let's first fix the issue from #410 and then, if didn't solve what you reported here, please add a comment to this issue. Thanks.

**Comment by thatmodelguy** [comment]
This issue was happening since the last build of Gtuner so it wasn't necessarily the current build that caused the conflict with speech recognition. I was just hoping it would fix the problem but it seems to have gotten a little worse. I reported it a while back in the forums but didn't know I was supposed to reported here so maybe it got overlooked. I suppose if the connection method was updated in the last build that would probably be the problem. Anyway, you know what you're doing, I'm just guessing at it =) Thanks for the help

**Comment by thatmodelguy** [comment]
I tested the new version just now and capture mode is fixed and working properly. It still doesn't want to work with Windows speech recognition though. With the new version it doesn't seem to let Windows speech recognition work at all but seems to have no problem with a voice macro script I made in gloves pie to navigate the program(I also tested Dragon speech and even though it's a pain to navigate with its unaffected as well). If you set Titan 2 to disconnected at the top right corner of the program Windows speech will stop glitching out and start working as normal again. As soon as you switch it back it gets stuck in an infinite loop processing or just which is itself off. So it seems to be some kind of conflict between when the device is connected to the program and Windows speech is running.

**Comment by J2Kbr** [comment]
Thank you for the feedback. I am reopening this issue and will be checking soon.

**Comment by thatmodelguy** [comment]
I just bought a mad Catz fight pad to get around the timeout with the PlayStation five and I noticed Windows speech recognition wasn't seeming to be glitching out like it has been. Something with switching the controller seems to have fixed the problem where speech recognition is working normally again. I have no idea what but I tested G tuner by opening and closing it several times also using capture mode and it hasn't messed up so far. I was originally using a official PlayStation four controller when I reported this. It may have been the controller, the cord connecting it, or maybe disconnecting all the cords from the Titan and reconnecting for the new controller that helped. Before switching the controller disconnecting the other controller would make the program run normal so maybe it was a hardware issue? Either way, it seems to be working properly now.

**Comment by J2Kbr** [comment]
Thank you for the update. I tried reproduce the issue but on my computer the speech recognition worked as expected. Not sure how the DS4 controller could cause that. I am glad you found a solution for the problem. Thank you again for keeping this issue updated.
