### ISSUE TITLE
control the segment display

### ISSUE THREAD

**Issue by Scachi** [J2Kbr/GtunerIV#42]
For scripts it could be very useful to have control over the segment display for a more detailed visual feedback if possible.
Like displaying the values of variables when adjusting settings in-script with button combinations
or when trying to track the players character selection in fighting games and stuff like that.
Sometime using just the color led isn't enough for the feedback.

**Comment by J2Kbr** [comment]
Feature implemented on Gtuner IV 0.96B and Titan Two FW 0.78B.

GPC command: `display_overlay(uint8 mask, uint16 timeout);`

where `mask` is an bitmask for each segment of the led display
and `timeout` is how long in ms the overlay should be displayed until it resets to the "system" status (ie. memory slot number)

Gtuner IV 0.96B also has an header file (`display.gph`) with defines for each led segment and pre-built bitmasks for common characters, such number and letters.
