### ISSUE TITLE
Interactive config - cfgdesc - group controls

### ISSUE THREAD

**Issue by Scachi** [J2Kbr/GtunerIV#43]
Please add the ability to group controls in the interactive config for a result like this : 
[http://www.consoletuner.com/forum/viewtopic.php?f=23&t=4572&p=36132#p36125](http://www.consoletuner.com/forum/viewtopic.php?f=23&t=4572&p=36132#p36125)

**Comment by hhezart** [comment]
+1

**Comment by J2Kbr** [comment]
Feature added to Gtuner IV 0.93 Beta.
See Configuration Descriptor Example version 1.5 for more details.

**Comment by prototypeGtuner** [comment]
Is it possible to use spaces within a group?

**Comment by J2Kbr** [comment]
Not yet, please refer to the following bug tracker:
https://github.com/J2Kbr/GtunerIV/issues/53
