### ISSUE TITLE
cfgdesc Interactive Configurator themes

### ISSUE THREAD

**Issue by PablosScripts** [J2Kbr/GtunerIV#46]
Just for you to keep a track of so you don't forget: 

http://www.consoletuner.com/forum/viewtopic.php?f=23&t=4849#p37053

**Comment by prototypeGtuner** [comment]
The link is dead but it would be good to have a "save defined settings" and "restore defined settings" boxes near the "Restore Defaults" box.

**Comment by J2Kbr** [comment]
I have just checked the linked topic and most of requests there are already implemented, with exception of CSS customization. Gtuner IV utilizes QWidgets for the GUI controls, which supports CSS. However, Gtuner Air is build with QtQuick which has other language for styling (not CSS). CSS, unfortunately, cannot be supported on both applications.
