### ISSUE TITLE
Allow a script to keep the persistent data (interactive configuration settings) on update

### ISSUE THREAD

**Issue by Scachi** [J2Kbr/GtunerIV#49]
The T2 can handle very large and complex script with a lot of interactive configuration options.
When updating a script, drag&drop it onto the same slot where the old version is stored should give the script-author the possibility to keep the users save interactive configuration.
So the user doesn't need to do all the configuration again just because of a small bugfix in the script that didn't changed anything in the persistent data structure.

Maybe this can be done via the version number of the script and a "MinVersion" setting (in a comment) the script author can adjust.
If the variable is lower than or equal to the slots script version (and the script name matches) then keep the current persistent data ELSE erase it.

Example:
Slot scripts version 1.01
Updated scripts new version 1.02 - defined "MinVersion" 1.00 = keep data
Updated scripts new version 1.05 - defined "MinVersion" 1.00 = keep data
Updated scripts new version 1.10 - defined "MinVersion" 1.10 = erase data
Updated scripts new version 1.20 - NOT defined "MinVersion"  = erase data

**Comment by PablosScripts** [comment]
This is a really great idea!

**Comment by J2Kbr** [comment]
For the same reasons expressed in #96, the implementation of this suggestion is not -currently- possible.

However, starting from Gtuner IV 1.00RC, if before drop an script into the memory slot, the user press and hold the **Ctrl** key, the persistent memory will NOT be reset and the current configurations will be kept.

Hopefully this solution can, in some extent, serve as alternative to the above suggestion.
