### ISSUE TITLE
Bug or feature ? Interactive configuration shared by scriptname+versionnumber

### ISSUE THREAD

**Issue by Scachi** [J2Kbr/GtunerIV#50]
Having the same script in multiple slots with the same version number seems to work fine.
I use this for The Division and my different characters with different weapon (anti recoil settings).
The scripts in slot 1,2,3,4 are all the same name an version number.

I tested some new features for my script and added a cfgdesc setting without changing the scrips version number.

I saved the new script (same version number) to slot 8. Opening the interactive configuration showed the new checkbox, changing this setting also changes the script behaviour like it should.
Now (without updating the script in slot1) I opened the interactive configuration of slot 1 and there the new checkbox also shows up, but changing this settings doesn't change the scripts behaviour (which is fine).
This seems to indicate that the interactive configuration is saved by name&versionnumber, the script itself by slot-number.

Is this like it should be or should the interactive configuration be saved by slotnumber like the script seems to be?

**Comment by J2Kbr** [comment]
This is a "feature". As you noticed, the configuration descriptor is not stored on the device's memory slot (on device), but cached locally (on computer) by Gtuner. The cache filename is computed using MD5 from script name, script version and author. Changing any of these values will generate a new configuration descriptor cache file.

When Gtuner retrieves the memory slot metadata from the device, it also checks if there is any matching configuration descriptor hash to enable the interactive configuration interface.

PS: Storing locally based on the memory slot number would not work when utilizing more than one device, or when using multiple computers (or smartphones/tablets) to update the device's memory slots.
