### ISSUE TITLE
GPC Script IDE - error message displaying old function name 'event_actived'

### ISSUE THREAD

**Issue by Scachi** [J2Kbr/GtunerIV#52]
This piece of invalid code gives an error in the Ouput Panel complaining about the old function name 
"event_actived" - that should be "event_active" now.

`if ( event_active(PS4_INVALID))`

GPC error: Test.gpc(9): Identifier not declared 'PS4_INVALID'.
GPC error: Test.gpc(9): Illegal operation 'event_actived'.

**Comment by J2Kbr** [comment]
Fixed this and few others on Gtuner IV 0.93 Beta.
