### ISSUE TITLE
cfgdesc - allow us to add a space between groups

### ISSUE THREAD

**Issue by PablosScripts** [J2Kbr/GtunerIV#53]
Please see the following image: 

https://i.imgur.com/HKy6VId.jpg

**Comment by J2Kbr** [comment]
The space control in the interactive configuration is a "special" component linked with the base layout layer, not allowing (without changes) be included in the top GUI layers (ie. a groupbox). However, I was about to make all changes needed when realize there is an much easy and already working option. You can add the tag `<br>` at the beginning of the description of the second grouped component to have the same effect. :)
