### ISSUE TITLE
Add F-key shortcut to preview cfgdesc menu

### ISSUE THREAD

**Issue by PablosScripts** [J2Kbr/GtunerIV#54]
When I'm testing this it's a bit annoying to have to keep going up to the menu. It would be good to be able to hit an F-key shortcut like we can with compiling (F5).

**Comment by PablosScripts** [comment]
Oops sorry I meant to say F7, but you know what I mean:)

**Comment by J2Kbr** [comment]
Added on Gtuner IV 0.94B -- (F9)
side note:
F5 -> build and run
F6 -> Assembler code
F7 ->Compile
F9 -> Preview GDC
