### ISSUE TITLE
Online Resources - ability to filter / sort by items created by me

### ISSUE THREAD

**Issue by PablosScripts** [J2Kbr/GtunerIV#55]
Please see this screenshot for an example: 

https://i.imgur.com/9nKBlAJ.jpg

**Comment by J2Kbr** [comment]
To list all published works made by an author, do a search by the author name (ie. pablogroup). The resulting list can then be ordered by the available options shown in the posted picture.

**Comment by PablosScripts** [comment]
excellent that works perfectly:)
