### ISSUE TITLE
Provide option to partially disable scroll wheels when in Interactive Configurator menu

### ISSUE THREAD

**Issue by PablosScripts** [J2Kbr/GtunerIV#56]
When you are scrolling down the Interactive Configurator menu, if your mouse is hovering over a slider or spinbox control at the time, it will stop scrolling and it will begin changing the values. Is it possible to partially disable scrolling? Allow it to scroll the main scroll bar, but not change any cfgdesc values?

I have done this by accident before and didn't realize until I started playing the game.

**Comment by prototypeGtuner** [comment]
Yes it is a side effect but i like the way we can change mods with the wheel and to scroll down there is the side slider.

**Comment by PablosScripts** [comment]
I wonder if it's possible to make it so you need to click the specific panel first before you can scroll. This would give us the best of both worlds.

**Comment by prototypeGtuner** [comment]
Yes honestly it's annoying. I never had this issue while using Gtuner with win 7 but since win 8 and now win 10...

**Comment by J2Kbr** [comment]
Starting from Gtuner IV 0.95B, the configuration control must have focus (clicked) to accept mouse wheel events (as suggested above, by pablogroup).
