### ISSUE TITLE
Input Translator - better display of information

### ISSUE THREAD

**Issue by PablosScripts** [J2Kbr/GtunerIV#58]
I had to keep looking up a reference table I made to figure out what the button mappings were: 

https://docs.google.com/spreadsheets/d/1nto1HWEwLju3wxkcbx7vmAVaexlxmBLtQ31aDO6VK28/edit#gid=0

There are some great ideas in the following thread. For example, adding a picture of a controller behind it. 

http://www.consoletuner.com/forum/viewtopic.php?f=23&t=3609&p=26318&hilit=remapper#p26318

You could also study the way Sony and MS have implemented this if you need some more ideas: 

http://support.xbox.com/en-AU/xbox-one/accessories/customize-standard-controller-with-accessories-app

http://www.nextpowerup.com/news/18847/ps4-customizable-buttons-assignment-feature-is-truly-unique-accessibility-options-coming/

**Comment by Scachi** [comment]
A input selection combobox like in the Device Monitor would be a great help, so users can see the Button names they are used to to remap the buttons.

**Comment by J2Kbr** [comment]
With the improvements made on the GPC Input Reference (Gtuner IV 0.100B) #113, I believe this issue can be closed, at least temporarily until we have enough time to test if the solution provided by the new GPC Input Reference offers an satisfactory solution for this issue.
