### ISSUE TITLE
(Bug) Allow passing a variable into led_set();

### ISSUE THREAD

**Issue by CrispyPixels** [J2Kbr/GtunerIV#59]
Cannot currently set the LED to change with a variable. For example:
led_set(led,brightness,duty);
It brings up following warning:
GPC error:SuperRemaper2.gpc(21): syntax error, unexpected IDENTIFIER, expecting IDENT_FB_INDEX 'led'.

**Comment by J2Kbr** [comment]
Force explicit use of LED identifiers was actually an design choice (in fact more like an design needed). You can use the function below to workaround this limitation:

```
void ledset(uint8 ledidx, fix32 intensity, uint32 dutylenght) {
    switch(ledidx) {
        case 1: led_set(LED_1, intensity, dutylenght); break;
        case 2: led_set(LED_2, intensity, dutylenght); break;
        case 3: led_set(LED_3, intensity, dutylenght); break;
        case 4: led_set(LED_4, intensity, dutylenght); break;
    }
    return;
}
```
