### ISSUE TITLE
Dereference a pointer to store a value in its pointee doesn't work

### ISSUE THREAD

**Issue by hhezart** [J2Kbr/GtunerIV#6]
<pre>
void caller() {
    fix32 n = 0.0;

    callee(&n);

    // n should be 100.0-ish but it is still 0.0
}

void callee(fix32 *p) {
    *p = 100.0;
}
</pre>

**Comment by J2Kbr** [comment]
The pointer dereferencing is working, please check the code below:

main {
    fix32 n = 0.0;
    set_val(BUTTON_20, n); // shows 0.0
    callee(&n);
    set_val(BUTTON_21, n); // shows 100.0
}
void callee(fix32 *p) {
    *p = 100.0;
}

**Comment by hhezart** [comment]
OK, but it doesn't work if the caller is a func():

main {
    caller();
}

void caller() {
    fix32 n = 0.0;
    set_val(BUTTON_20, n); // shows 0.0
    callee(&n);
    set_val(BUTTON_21, n); // shows 100.0  
}

void callee(fix32 *p) {
    *p = 100.0;
}

**Comment by J2Kbr** [comment]
Confirmed. thank you for the extra information.

**Comment by J2Kbr** [comment]
Fixed on Gtuner IV 0.91 and Titan Two firmware 0.68
