### ISSUE TITLE
  GTuner + T2+SDCard = restart loop

### ISSUE THREAD

**Issue by Scachi** [J2Kbr/GtunerIV#61]
This happens for the 5th or 6th time for me now.

I stopped playing Ps4 yesterday with everything working fine, I could run GTuner on my pc and doing adjustments via interactive configurations without a problem.

Now, today, when I run GTuner (with the same SD card that did work fine yesterday) my Titan2 gets into a restart loop.
The device monitor display for the SD card circling information : not present -> initializing -> Present (1,85GB) -> Device information are empty/grey and the T2 RESTARTS (PS4 is reporting "Controller disconnected").
This happens over and over again but only when running GTuner. The SD card slots never showing the scripts they are containing.

Without GTuner I can run all script from the SD card slots (each slot containing a script) without any problems, everything is working fine.

I am using a 2GB SD card, this happened to me with other SD cards as well.
I am able to stop the reboot loop by: backup the content of the Sd card, reformatting, and copying back the content.
Removing the SD card stops the restart loop, so this has something to do with the GTuner reading information from the sd card.

Forum links:
http://www.consoletuner.com/forum/viewtopic.php?f=23&t=4986&p=37978#p37978

**Comment by Scachi** [comment]
It looks like a reformat isn't needed. Using a usb reader, I just did copy the data from the sd card to my desktop, deleted one memory slot data on the sd card and restored this slot back from the backup. Now I can start gtuner again without the restart loop.

Only two slots data files had an modification date (slot 6 & 7), I deleted the one (both .gbc & .gpm) with the newest modification date (7) and copied it back.

**Comment by J2Kbr** [comment]
As per your comment in the forums ( http://www.consoletuner.com/forum/viewtopic.php?p=38943#p38943 ) I am closing this issue.

Please create a new comment in case it need be reopened.

I any case, this issue is very likely to be related with the watchdog and long sd-card operations. Therefore, starting from firmware 0.78B the watchdog will be disabled during potential long sd-card operations.

Thanks.
