### ISSUE TITLE
Register / Forgot Password option needed

### ISSUE THREAD

**Issue by PablosScripts** [J2Kbr/GtunerIV#62]
Now that you can upload scripts directly to the app itself, it's entirely conceivable that you might have users that almost never visit the main website / forum. 

Therefore you need a link in the app for them to register and reset their passwords. Please see the following (crude!) mockup:

https://i.imgur.com/Ieix1AV.jpg

**Comment by J2Kbr** [comment]
Implemented on Gtuner IV 0.95B.
