### ISSUE TITLE
Add note about allowed markup tags allowed

### ISSUE THREAD

**Issue by PablosScripts** [J2Kbr/GtunerIV#63]
I notice a lot of descriptions are pretty rough. This is probably because people are unaware they can use some basic html markup. Here's my crude mockup: 

https://i.imgur.com/RF56Sas.jpg

**Comment by J2Kbr** [comment]
Added to Gtuner IV 0.95B as placeholder text. (grayed-out text show as long as the input field is empty).
Similar placeholder text were also added to "Keywords" and "Doc URL" input fields.
