### ISSUE TITLE
File Explorer panel - option to filter by Date Modifed

### ISSUE THREAD

**Issue by PablosScripts** [J2Kbr/GtunerIV#66]
Right now you can only sort by Name, alphabetically ascending and descending. 

When I'm working on a number of scripts, and I already have a huge library of existing scripts, alphabetically doesn't help me at all. What I really need is to see the last modified files at the top of the list. 

Two options to achieve this: 

1) Add a right click "Sort by > Date modified", or;

2) Add a second column "Date Modified", which can be sorted

**Comment by J2Kbr** [comment]
Second column "Date Modified" was added to Gtuner 0.95B. To show the extra column check the correspondent option on Preferences -> Environment.

**Comment by PablosScripts** [comment]
I don't think this works. I suspect it is sorted by file creation date, not date modified / last updated.

I opened an old file, made a change, sorted the list, but the file I created long ago still shows at the top of the list!

**Comment by J2Kbr** [comment]
I double checked and the second column is showing the Modified Date. The File Explorer pane is an component that runs in an separated thread and it may take a while until it refreshes the listed file info, that would explain why you have not observed the modified date update.

By revisiting this issue, I took the opportunity to keep the directories on top also when sorting by Modified Date - Gtuner IV 0.100B

**Comment by PablosScripts** [comment]
Still don't think this works unfortunately, please see the screenshot below:

![not ordered](https://user-images.githubusercontent.com/22415147/37447035-1b4f1f54-2874-11e8-94fb-30658f11afa6.png)
