### ISSUE TITLE
(Feature Request) GtunerIV Layouts

### ISSUE THREAD

**Issue by prototypeGtuner** [J2Kbr/GtunerIV#67]
Most of the time i use Gtuner IV in dual screen mode and it's awesome to use but when i go back in one screen mode i have to rearrange all windows to set how i like.

Would it be possible to save different profiles/layouts and change it on the fly ? And select the layouts in the View menu or a drop down menu in the View menu ?

**Comment by J2Kbr** [comment]
Feature added to Gtuner 0.95B.
New items on menu View: Save Layout (Crtl+F11) and Restore Layout (F11).

**Comment by prototypeGtuner** [comment]
Thank you it works perfectly and it's useful. But would it be possible to save at least 2 custom layouts? Maybe saved in different files that can be acceded from the view menu?

This is a very low priority request, it's just wishes and questions. In fact i would like to have one for one screen mode and a second for two screens mode.
