### ISSUE TITLE
Error when trying to publish a script (updating an existing script, now it's missing entirely from the Online Resources

### ISSUE THREAD

**Issue by PablosScripts** [J2Kbr/GtunerIV#68]
This has happened to me twice. 

I have observed two things: 

1) My script has gone missing altogether. 

2) One of my other scripts reverted back to an older version!

**Comment by J2Kbr** [comment]
Added server-side extra measurements to prevent scripts to revert back. Currently a published scripts is not really deleted, but flagged as deleted. After the beta period this behavior will be changed to actual delete the files and database entries.
