### ISSUE TITLE
Incorrect header / title

### ISSUE THREAD

**Issue by PablosScripts** [J2Kbr/GtunerIV#69]
https://i.imgur.com/j6vZWpM.jpg

**Comment by J2Kbr** [comment]
Next to RUN toolbar button is an indication of which work will be used by the RUN command, and not a reference to the active pane. For example: you are on the code editor and change the active pane to the device monitor, in this scenario you can still click on RUN to load the GPC script into Titan Two without need go back to the code editor pane.
