### ISSUE TITLE
Add option to have "Replace existing published work: " checked by default

### ISSUE THREAD

**Issue by PablosScripts** [J2Kbr/GtunerIV#70]
I understand why it's unchecked by default, but for experienced users, would you be able to add an option to have this ticked all the time? It gets a bit frustrating having to keep ticking it when I'm making a bunch of updates.

**Comment by J2Kbr** [comment]
Starting from Gtuner IV 0.95B, manually including the following pair key/value into the Advanced section of Gtuner.cfg will automatically check the replace work checkbox.

```
[Advanced]
publish_replace=true
```
