### ISSUE TITLE
Menu dropdowns don't work

### ISSUE THREAD

**Issue by PablosScripts** [J2Kbr/GtunerIV#71]
Presumably these are intended to be dropdown menus, e.g. click arrow, select new file type (gbc vs gpc vs gph etc) but they don't work. 

https://i.imgur.com/RggY6QI.jpg

solution: either fix it or remove the little arrow (if you never intended them to be dropdowns)

**Comment by Scachi** [comment]
They do work for me. You have to click on them but keep the mouse button pressed down until the sub-menu opens.

**Comment by J2Kbr** [comment]
Scachi is right. It is required click and hold a little bit. This behavior is defined by this Qt component.

**Comment by PablosScripts** [comment]
Ah I see, I got it. It's a little bit weird, I have never seen a desktop app do this before. I guess it's just carried over from mobile UX paradigms. All good.
