### ISSUE TITLE
Option to change how files are downloaded?

### ISSUE THREAD

**Issue by PablosScripts** [J2Kbr/GtunerIV#72]
My documents folder has become quite messy. I wonder if it's possible to provide us with configurable options to change how they are stored?

https://i.imgur.com/Xg6I4w1.jpg

options include: 

1) download and store in the same folder, don't group them into sub-folders
2) automatically overwrite older version
3) prompt user to decide whether to overwrite or rename
4) keep older versions (and automatically append a date / time stamp or version number to the end or something)
5) keep latest version in the same folder, then move all older ones into a sub-folder called "Archived" or something

**Comment by J2Kbr** [comment]
If the work already exists locally, a message window is shown for action selection (Replace, Create Copy or Cancel) - Added to Gtuner IV 0.100B
