### ISSUE TITLE
Add option to customize PS4 controller speaker sound

### ISSUE THREAD

**Issue by PablosScripts** [J2Kbr/GtunerIV#73]
placeholder

http://www.consoletuner.com/forum/viewtopic.php?f=23&t=5026&start=10#p38499

**Comment by AJSinc** [comment]
I know this topic is old, but this would still be really nice. And an option to mess with your own audio, so we could script features such as push to talk / push to mute!

**Comment by J2Kbr** [comment]
With more knowledge on how the audio works on DS4 controllers, implementing this feature would require too much processing power from the Titan Two device. We have planned have push and audible notifications on Gtuner Air, which -I believe- can be used for the same purposes as this requested feature could be used.
