### ISSUE TITLE
Option to disable rumble for a specific port

### ISSUE THREAD

**Issue by Scachi** [J2Kbr/GtunerIV#77]
Is it possible to add an option to the GTuner "Device Configuration" to disable rumble on port B ?

User with multiple connected controllers (Port A Xbox, Port B PS4) for crossover gaming may want this option to stop the second controller (used for auth) from dancing around their table.
So the user don't need to edit the scripts, what isn't possible at all when using scripts published as bytecode.

Like requested here : http://www.consoletuner.com/forum/viewtopic.php?f=27&t=5195&p=38879#p38878

**Comment by omasseau** [comment]
Indeed it would be really great to have this option :)
It can be really annoying to have controller B vibrating on the table.

**Comment by J2Kbr** [comment]
Starting from Gtuner IV 0.95B and Titan Two FW 0.78B, the FFB can enabled/disabled on each input port as global configuration. The global configuration can be overwritten by scripts, and will be restored when the script unload.
