### ISSUE TITLE
Idea - have the app prompt an "Add shortcut to Start Menu" dialogue when opening the app (for the first time only)

### ISSUE THREAD

**Issue by PablosScripts** [J2Kbr/GtunerIV#79]
This is a *tiny* feature that new users might appreciate. Very low priority obviously.

**Comment by PablosScripts** [comment]
It just occurs to me this is probably technically unfeasible since you can move the root folder anywhere you please?

**Comment by J2Kbr** [comment]
Correct. By moving the folder would break the start menu link. And also: an "portable application" should keep everything within its directory and avoid change the system.

Later, if we implemented "installers" for each port, the menu link will be automatically created.
