### ISSUE TITLE
Array subscript doesn't work with variables

### ISSUE THREAD

**Issue by hhezart** [J2Kbr/GtunerIV#8]
<pre>
const int8 somearray[] = {0, 0, 5, 40, 20, 50, -20, 40, 0, 45, 5, 65};
int i = 2 * 2;
result = somearray[i]; // keeps returning 0, wrong value
result = somearray[4]; // numeric literal 4 returns the right value!
</pre>

Update: removing the const fixed the problem.

<pre>
non-const does a memcpy and subscript works
    MCPY    23E3,<000D>,000C
    ....
    LCW!    23E3
vs const where data seg is loaded but subscript doesn't work 
    LCW!    <000D>
</pre>

**Comment by J2Kbr** [comment]
Bug report duplicated with issue 5. Closed.
