### ISSUE TITLE
Meta data search not working

### ISSUE THREAD

**Issue by PablosScripts** [J2Kbr/GtunerIV#80]
Please see the attached test: 

https://i.imgur.com/1zpqgGV.jpg

**Comment by J2Kbr** [comment]
Fixed on consoletuner server. Minimum word length for indexing is now 3.

In your example, both gta and "gta v" now return results.

Note: There are still some stop-words that will be ignored, a table of stop-words can be found here:
"Stopwords for MyISAM Search Indexes"
http://dev.mysql.com/doc/refman/5.7/en/fulltext-stopwords.html
