### ISSUE TITLE
function declaration argument order with pointers

### ISSUE THREAD

**Issue by Scachi** [J2Kbr/GtunerIV#81]
Hi,

I get a GPC compile error when I try to declare the function with the arguments in this order:
void ButtonSave(uint8 *src, uint8 ps)
Error: GPC error: Magicka2_Scachi.gpc(1473): Variable declaration syntax error 'ps'.

but this works:
void ButtonSave(uint8 ps, uint8 *src)

Shouldn't both compile correctly ?

[Forum post](http://www.consoletuner.com/forum/viewtopic.php?f=26&t=5205)

**Comment by J2Kbr** [comment]
Correct, coincidentally this is a bug I just fixed (yesterday), for Gtuner 0.95B.
I noticed that when making examples for the GPC script language reference [here](http://www.consoletuner.com/wiki/index.php?id=t2:gpc_language_reference). :)
