### ISSUE TITLE
Usability improvement to how scripts are "installed" from the Online Resource page

### ISSUE THREAD

**Issue by PablosScripts** [J2Kbr/GtunerIV#84]
Please see the following link for mockups and discussion: 

http://www.consoletuner.com/forum/viewtopic.php?f=23&t=4981&p=38394&hilit=https%3A%2F%2Fi.imgur.com%2FmkMccBA.jpg#p38394

**Comment by J2Kbr** [comment]
Feature added to Gtuner IV 0.100B
