### ISSUE TITLE
Interactive Configuration - combobox & collapsible for "groups" of settings

### ISSUE THREAD

**Issue by Scachi** [J2Kbr/GtunerIV#87]
The interactive configuration dialog can get a bit long.
I am trying to add profiles to my division script to support all 4 possible players character with one script to save memory slots. I have four in use for The Division alone. My Division script is available in GTuners Online Resource fo see all the options.
So I have some repeating settings (anti recoil, fire modes) for each profile making the dialog even longer.

Being able to "group" (not as with group=true, may be different ungrouped settings I want have in one collapsible "group") different configuration settings as collapsible and make them shown collapsed by default will make it much easier to overview all the settings and edit the settings for one specific profile.

I'll try to add a mockup screenshot to better show what I am thinking of.
![interactive_mockup](https://cloud.githubusercontent.com/assets/22262242/20484235/8d59c6be-aff6-11e6-92f1-bd1e89031c66.png)
The Profile#1 is the customizeable text to show for the collapsible button.
All the options betweens the green arrows should the be collapsible. Providing the collapsible thing with a default = collapsed to show as collapsed as default would be a great addition.

**Comment by PablosScripts** [comment]
Good suggestion. I wonder if another approach to this is to have a single dropdown menu at the top, which allows you to select between your various profiles? This might be a cleaner solution?

**Comment by Scachi** [comment]
Your dropdown idea is good, it saves more space.
What about that:

+ Combobox for stuff like Profiles to view/hide multiple settings depending on the combobox value.

+ Collapsible for stuff like "Advanced settings" (most user don't need but some would like to adjust, the requirement for multiple settings in one collapsible field is still there) 

+ Collapsible for a "read more" link as an example: For the instructions how to use the script.
Having a good manual/instruction for the script included and readable within the interactive config gui is great, but the long text might only be read once by the user so making it collapsed would really save a lot space.

All that stuff still should be able to group=true so I can use the "Adanced settings" collapsible within each profile for the last four "Vertical" anti recoil in the screenshot above. They are somewhat hard to configure but great to have for that game. The Division has something like a second recoil curve that kicks in after some time on some weapons with a high capacity mag. Most people probably never used this setting, but I can't live without that ;-)

**Comment by PablosScripts** [comment]
Love all those ideas!

**Comment by J2Kbr** [comment]
Option to create collapsible sections was added to Gtuner IV 1.00RC.

Set `collapsible = 1`  to create an collapsible group with initial state expanded
Set `collapsible = 2`  to create an collapsible group with initial state collapsed

If in the same section `group = true`, the `collapsible` option is ignored.
