### ISSUE TITLE
Idea - provide the option to completely block all input from the authenticating controller

### ISSUE THREAD

**Issue by PablosScripts** [J2Kbr/GtunerIV#92]
This has happened to me many times: 

1) I'm using a mouse and keyboard

2) The authenticating controller (located well away from where I'm sitting because I use a mouse) has shuffled around a little bit, or someone has moved it, which causes one of the buttons to be pushed in (always happens to the triggers for example). 

3) I spend 10 mins wondering why my T2 / mouse / PS4 is acting up, unplug everything, restart everything, only to realize it's because my authenticating controller is being triggered. 

I wonder if you can make a setting to have it blocked off completely?

**Comment by prototypeGtuner** [comment]
Yes i like it, often i have to unplug The Titans when i want to try combos without send the outputs to the console. A way to block inputs and/or outputs like the rumble in the device configuration would be useful!

**Comment by prototypeGtuner** [comment]
The best way i've found to do that is by changing the output protocol, by script or through Gtuner.
And now with the new remaper functions it does what you want.

**Comment by J2Kbr** [comment]
prototype is correct, the ability of make remaps based on the input ports can be used for this purpose.
