### ISSUE TITLE
Support for both Doc and Video links in Online Resources

### ISSUE THREAD

**Issue by PablosScripts** [J2Kbr/GtunerIV#93]
As you've seen in my Rainbow Six Siege script, I have a demo video which I think is quite important in communicating some of the key features, which are very difficult to describe textually. But the downside is that I lose the ability to link to a Doc. Would it be possible to support both?

**Comment by J2Kbr** [comment]
the support for both is already present. please PM me on the forums, so I can explain and keep this privately.
