### ISSUE TITLE
Add GPC1 to GPC2 script converter

### ISSUE THREAD

**Issue by PablosScripts** [J2Kbr/GtunerIV#94]
You could use the backwards compatibility header file but the regular joe user isn't going to bother with this. It would also double as a very powerful marketing point for people looking to make an upgrade.

**Comment by J2Kbr** [comment]
Gtuner IV 1.00RC has full backward compatibility with Titan One script code by just adding `#include <titanone.gph>` at the beginning of the code. This header file is provided with the software and does not need to be downloaded.

This header also flags the GPC compiler to make it aware the code after it is from Titan One, so script codes containing `define`, `data`  segment, `remap`, `unmap` and `function` are correctly evaluated.

The script execution should be exactly as on the Titan One. Precisely timed `combos` may need to add `wait(10);` at its end, as the Titan One runs scripts at 10ms interval, and the Titan Two runs below 1ms.

The Titan One compiler is forgiven with the _statement terminator_ `;`, the Titan Two compiler isn't. So a code missing _statement terminators_ that compiles fine on Gtuner Pro will not on Gtuner IV.

**Comment by NeoTechni** [comment]
I can't get this code to do anything: (this is for use on a special controller that has weird mappings)

#include <titanone.gph> //so remap works 
remap BUTTON_9  -> BUTTON_1; 	//guide/home button
remap BUTTON_15 -> BUTTON_17; 	//X to square
remap BUTTON_16 -> BUTTON_15; 	//B to circle
remap BUTTON_17 -> BUTTON_16; 	//A to cross
remap PADDLE_1  -> BUTTON_9; 	//right/white switch up to L3
remap PADDLE_2  -> BUTTON_6;	//right/white switch down to R3
