### ISSUE TITLE
Menu filters not retained after navigating to a different tab

### ISSUE THREAD

**Issue by PablosScripts** [J2Kbr/GtunerIV#95]
Something about navigating around was annoying me for a while but I couldn't put my finger on it. Something was off about the usability. Now I realised what it was! 

Steps to replicate: 

1) Change the filter from the default of "Relevance" to say, "Publish Date". 

2) Click on a different tab (e.g. "Macro Files"), now navigate back to the default "ALL" tab. 

Expected outcome: 

-- The filter "Publish Date" is retained. 

Actual outcome: 

-- The filter reverts back to the filter "Relevance". 

I think the only thing that should revert the filter back to the default is clicking on the Refresh button (the little circle arrow on the far right).

**Comment by J2Kbr** [comment]
Starting from Gtuner IV 1.00RC, `Order By` and `Sort By` are not reset during the current session, not even if `Reload` is clicked, as reload have the meaning of just refresh the page contents. Thanks for this suggestion. :)
